import { auth, db } from './firebase-config.js';
import { addDoc, collection, getDocs } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';

const ROLE=window.IMS_ROLE||'admin',CAN_EDIT=['manager','superadmin'].includes(ROLE),byId=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cls='w-full bg-slate-950 border border-slate-700 rounded-lg px-3 py-2.5 text-sm';
const norm=s=>String(s??'').trim().replace(/\s+/g,' ').toLowerCase(),now=()=>new Date().toISOString();
let busy=false;
async function settings(){const s=await getDocs(collection(db,'settings'));return s.docs.map(d=>({id:d.id,...d.data()}));}
function field(label,html){return `<label class="block text-xs text-slate-400"><span class="block mb-1">${label}</span>${html}</label>`}
async function mount(){if(!CAN_EDIT||byId('imsClassificationMaster')||!/Global Settings/i.test(byId('pageTitle')?.textContent||''))return;const root=byId('appContent');if(!root)return;const all=await settings();if(byId('imsClassificationMaster')||!/Global Settings/i.test(byId('pageTitle')?.textContent||''))return;const cats=all.filter(x=>x.type==='category'&&x.status!=='inactive');const sec=document.createElement('section');sec.id='imsClassificationMaster';sec.className='bg-slate-900 border border-slate-800 rounded-2xl p-4 sm:p-5 shadow-xl mt-5';sec.innerHTML=`<h2 class="font-bold mb-1">Brand / Model / Grade / Specification</h2><p class="text-xs text-slate-500 mb-4">Add the hierarchy once. Existing master values are not deleted or renamed.</p><form id="imsClassMasterForm" class="grid sm:grid-cols-2 xl:grid-cols-[180px_1fr_1fr_1fr_1fr_auto] gap-2 items-end">${field('Category',`<select id="cmCategory" required class="${cls}"><option value="">-- Category --</option>${cats.map(x=>`<option>${esc(x.value)}</option>`).join('')}</select>`)}${field('Brand',`<input id="cmBrand" class="${cls}" placeholder="Optional">`)}${field('Model',`<input id="cmModel" class="${cls}" placeholder="Optional">`)}${field('Grade',`<input id="cmGrade" class="${cls}" placeholder="Optional">`)}${field('Specification',`<input id="cmSpec" class="${cls}" placeholder="Optional">`)}<button id="cmSaveBtn" class="bg-emerald-700 px-4 py-2.5 rounded-lg text-xs font-bold">Add</button></form><div id="cmList" class="mt-4 grid md:grid-cols-2 xl:grid-cols-4 gap-2"></div>`;root.appendChild(sec);byId('imsClassMasterForm').onsubmit=save;renderList(all);}
function renderList(all){const m=byId('cmList');if(!m)return;const types=['brand','model','grade','specification'];m.innerHTML=types.map(t=>`<div><div class="text-xs font-bold uppercase text-slate-500 mb-2">${t}</div>${all.filter(x=>x.type===t).slice().sort((a,b)=>String(a.value).localeCompare(String(b.value))).map(x=>`<div class="bg-slate-950 border border-slate-800 rounded-lg p-2 mb-2 text-xs"><div class="text-slate-500">${esc([x.category,x.brand,x.model,x.grade].filter(Boolean).join(' · '))}</div><div class="font-semibold">${esc(x.value)}</div><div class="${x.status==='inactive'?'text-amber-400':'text-emerald-400'}">${esc(x.status||'active')}</div></div>`).join('')||'<div class="text-xs text-slate-600">None</div>'}</div>`).join('');}
async function addIfMissing(all,type,data){if(!data.value)return;const found=all.some(x=>x.type===type&&norm(x.value)===norm(data.value)&&norm(x.category||'')===norm(data.category||'')&&norm(x.brand||'')===norm(data.brand||'')&&norm(x.model||'')===norm(data.model||'')&&norm(x.grade||'')===norm(data.grade||''));if(found)return;const rec={type,...data,normalizedValue:norm(data.value),status:'active',createdAt:now(),createdBy:auth.currentUser?.email||''};const r=await addDoc(collection(db,'settings'),rec);all.push({id:r.id,...rec});}
async function save(e){e.preventDefault();if(busy)return;const category=byId('cmCategory').value,brand=byId('cmBrand').value.trim(),model=byId('cmModel').value.trim(),grade=byId('cmGrade').value.trim(),spec=byId('cmSpec').value.trim();if(!brand&&!model&&!grade&&!spec)return alert('Enter at least Brand, Model, Grade or Specification.');busy=true;const btn=byId('cmSaveBtn');if(btn){btn.disabled=true;btn.textContent='Saving...';}try{const all=await settings();if(brand)await addIfMissing(all,'brand',{category,value:brand});if(model)await addIfMissing(all,'model',{category,brand,value:model});if(grade)await addIfMissing(all,'grade',{category,brand,model,value:grade});if(spec)await addIfMissing(all,'specification',{category,brand,model,grade,value:spec});renderList(all);byId('cmBrand').value='';byId('cmModel').value='';byId('cmGrade').value='';byId('cmSpec').value='';alert('Classification master updated.');}catch(err){console.error(err);alert(err?.message||String(err));}finally{busy=false;if(btn){btn.disabled=false;btn.textContent='Add';}}}
let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(()=>mount().catch(()=>{}),25)}).observe(document.body,{childList:true,subtree:true});mount().catch(()=>{});
