import { auth, db, firebaseConfig } from './firebase-config.js';
import { onAuthStateChanged, signOut, getAuth, createUserWithEmailAndPassword } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-auth.js';
import { collection, addDoc, getDocs, doc, getDoc, setDoc, updateDoc, runTransaction, writeBatch, query, where } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';
import { initializeApp, deleteApp } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-app.js';

const ROLE = window.IMS_ROLE || 'admin';
const CAN_EDIT_ITEM = ['manager','superadmin'].includes(ROLE);
const CAN_MANAGE_MASTER = ['manager','superadmin'].includes(ROLE);
const CAN_AUDIT = ['manager','superadmin'].includes(ROLE);
const CAN_MANAGE_USERS = ['manager','superadmin'].includes(ROLE);
const CAN_BACKUP = ROLE === 'superadmin';

let me = { email:'', role:ROLE, uid:'' };
let inventory=[], suppliers=[], clients=[], settings=[], movements=[], maintenance=[], documents=[], logs=[], audit=[], users=[];
let filteredLogs=[], filteredAudit=[];
let currentItemId='';
let logSort={field:'date',dir:'desc'};
let auditSort={field:'performedAt',dir:'desc'};

const nowISO=()=>new Date().toISOString();
const norm=s=>String(s??'').trim().replace(/\s+/g,' ').toLowerCase();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const byId=id=>document.getElementById(id);
const active=(type)=>settings.filter(x=>x.type===type && x.status!=='inactive');
const displayDate=v=>v?new Date(v).toLocaleString():'';
const valueOrDash=v=>v===undefined||v===null||v===''?'—':v;
function downloadText(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();URL.revokeObjectURL(a.href);a.remove();}

function traceComparable(v){if(v===undefined)return null;if(v===null||typeof v!=='object')return v;if(Array.isArray(v))return v.map(traceComparable);const o={};Object.keys(v).sort().forEach(k=>{if(!['uid','password'].includes(k))o[k]=traceComparable(v[k]);});return o;}
function changedFields(beforeValue,afterValue){const b=beforeValue&&typeof beforeValue==='object'&&!Array.isArray(beforeValue)?beforeValue:{value:beforeValue};const a=afterValue&&typeof afterValue==='object'&&!Array.isArray(afterValue)?afterValue:{value:afterValue};return [...new Set([...Object.keys(b||{}),...Object.keys(a||{})])].filter(k=>JSON.stringify(traceComparable(b?.[k]))!==JSON.stringify(traceComparable(a?.[k])));}
function friendlyAction(s){return String(s||'').toLowerCase().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}
async function writeAudit(actionType,module,targetType,targetName,beforeValue=null,afterValue=null,remark='',targetId='',metadata={}){
  const b=traceComparable(beforeValue),a=traceComparable(afterValue);
  const rec={traceVersion:3,actionType,module,targetType,targetName:String(targetName||''),targetId:String(targetId||''),summary:`${friendlyAction(actionType)}: ${targetName||targetType||module}`,beforeValue:b,afterValue:a,changedFields:changedFields(b,a),remark:String(remark||''),metadata:traceComparable(metadata),performedBy:me.email,performedByRole:me.role,performedAt:nowISO()};
  await addDoc(collection(db,'audit_traces'),rec);
}
async function writeLog(rec){
  const frozen={logVersion:2,date:nowISO(),performedBy:me.email,performedByRole:me.role,...traceComparable(rec)};
  await addDoc(collection(db,'operational_logs'),frozen);
}

function inferLocationType(balance){
 const s=norm(`${balance.locationType||''} ${balance.status||''} ${balance.location||balance.locationName||''}`);
 if(s.includes('supplier'))return 'supplier'; if(s.includes('client'))return 'client'; if(s.includes('maintenance'))return 'maintenance'; if(s.includes('transit'))return 'transit'; return 'warehouse';
}
function normalizeBalances(item){
 let b=Array.isArray(item.stockBalances)?item.stockBalances:[];
 if(!b.length){const q=Number(item.quantity??item.qty??1);if(q>0)b=[{qty:q,location:item.currentLocation||'Unknown',status:item.status||'At Warehouse'}];}
 return b.map(x=>({qty:Number(x.qty||0),locationType:x.locationType||inferLocationType(x),locationId:x.locationId||'',locationName:x.locationName||x.location||'Unknown',status:x.status||statusForType(x.locationType||inferLocationType(x))})).filter(x=>x.qty>0);
}
function statusForType(t,clientStatus='At Client'){return t==='supplier'?'At Supplier':t==='transit'?'In Transit':t==='client'?clientStatus:t==='maintenance'?'In Maintenance':'At Warehouse';}
function totalQty(item){return normalizeBalances(item).reduce((a,b)=>a+b.qty,0);}
function summarizeBalances(bal){const p=bal.filter(x=>Number(x.qty)>0);if(!p.length)return{status:'Disposed',location:'No Stock'};if(p.length===1)return{status:p[0].status||statusForType(p[0].locationType),location:p[0].locationName};return{status:'Multiple Locations',location:`${p.length} Locations`};}
function itemSnapshot(item){return {itemId:item.id,itemCode:item.itemCode,itemName:item.name,category:item.category,type:item.type,trackingType:item.trackingType||'legacy',unit:item.unit||'',supplierId:item.supplierId||'',supplierName:item.supplierName||''};}

const actionDefs={
 RECEIVE_SUPPLIER:{label:'Receive from Supplier',toType:'warehouse'},
 TRANSFER_WAREHOUSE:{label:'Transfer to Warehouse',toType:'warehouse'},
 DELIVER_CLIENT:{label:'Deliver to Client',toType:'client'},
 RETURN_CLIENT:{label:'Return from Client',toType:'warehouse'},
 SEND_MAINTENANCE:{label:'Send to Maintenance',toType:'maintenance'},
 RETURN_MAINTENANCE:{label:'Return from Maintenance',toType:'warehouse'}
};
function actionsForSource(t){return t==='supplier'?['RECEIVE_SUPPLIER']:t==='warehouse'?['DELIVER_CLIENT','TRANSFER_WAREHOUSE','SEND_MAINTENANCE']:t==='client'?['RETURN_CLIENT','SEND_MAINTENANCE']:t==='maintenance'?['RETURN_MAINTENANCE']:[];}

function shell(){
 document.body.innerHTML=`
 <div class="min-h-screen bg-slate-950 text-slate-100 lg:flex">
  <aside class="lg:w-64 lg:min-h-screen bg-slate-900 border-r border-slate-800 p-4 lg:sticky lg:top-0 lg:h-screen">
   <div class="flex items-center justify-between lg:block mb-4"><div><div class="text-xl font-black tracking-tight text-red-400">IMS</div><div class="text-[11px] text-slate-500 uppercase">${esc(ROLE)}</div></div><button id="logoutBtn" class="lg:hidden bg-slate-800 px-3 py-2 rounded-lg text-xs">Logout</button></div>
   <nav id="navTabs" class="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-1 gap-2"></nav>
   <div class="hidden lg:block mt-6 pt-4 border-t border-slate-800"><div id="currentUser" class="text-xs text-slate-400 break-all"></div><button id="logoutBtnDesktop" class="mt-3 w-full bg-red-600 hover:bg-red-500 py-2 rounded-lg text-xs font-bold">Logout</button></div>
  </aside>
  <main class="flex-1 p-3 sm:p-5 lg:p-7 overflow-x-hidden">
   <div class="max-w-7xl mx-auto"><div class="mb-5"><h1 id="pageTitle" class="text-xl sm:text-2xl font-bold">Main Workspace</h1><p id="pageSubtitle" class="text-xs text-slate-500 mt-1">Daily inventory work from one screen.</p></div><div id="appContent"></div></div>
  </main>
 </div>`;
 const tabs=[['workspace','Main Workspace','Daily inventory operations'],['logs','Logs / Records','Filter, sort, review and export'],['suppliers','Suppliers','Supplier business master'],['clients','Clients','Client business master'],['settings','Global Settings','Warehouses, units and categories']];
 if(CAN_AUDIT)tabs.push(['audit','Audit / Trace','Immutable system change history']);
 if(CAN_MANAGE_USERS)tabs.push(['users','User Management','Accounts and role control']);
 byId('navTabs').innerHTML=tabs.map(([id,label])=>`<button data-tab="${id}" class="navBtn text-left px-3 py-2.5 rounded-xl text-xs font-semibold bg-slate-800/50 hover:bg-slate-800">${label}</button>`).join('');
 document.querySelectorAll('.navBtn').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
 byId('logoutBtn').onclick=byId('logoutBtnDesktop').onclick=()=>signOut(auth).then(()=>location.href='index.html');
}
function setNav(tab,title,subtitle){document.querySelectorAll('.navBtn').forEach(b=>b.className=`navBtn text-left px-3 py-2.5 rounded-xl text-xs font-semibold ${b.dataset.tab===tab?'bg-red-600 text-white':'bg-slate-800/50 hover:bg-slate-800'}`);byId('pageTitle').textContent=title;byId('pageSubtitle').textContent=subtitle;}
function card(title,body,extra=''){return `<section class="bg-slate-900 border border-slate-800 rounded-2xl p-4 sm:p-5 shadow-xl ${extra}"><h2 class="font-bold text-sm sm:text-base mb-4">${title}</h2>${body}</section>`;}
const inputCls='w-full bg-slate-950 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-red-500';
const label=(txt,html)=>`<label class="block text-xs text-slate-400"><span class="block mb-1">${txt}</span>${html}</label>`;

function showTab(tab){
 if(tab==='workspace')renderWorkspace(); else if(tab==='logs')renderLogs(); else if(tab==='suppliers')renderBusinesses('supplier'); else if(tab==='clients')renderBusinesses('client'); else if(tab==='settings')renderSettings(); else if(tab==='audit')renderAudit(); else if(tab==='users')renderUsers();
}

function renderWorkspace(){
 setNav('workspace','Main Workspace','Register, move, arrive, maintain and review items from one page.');
 const stats={total:inventory.length,warehouse:0,transit:0,client:0,rental:0,maintenance:0,supplier:0};inventory.forEach(i=>normalizeBalances(i).forEach(b=>{if(b.locationType==='warehouse')stats.warehouse++;if(b.locationType==='transit')stats.transit++;if(b.locationType==='supplier')stats.supplier++;if(b.locationType==='maintenance')stats.maintenance++;if(b.locationType==='client'){stats.client++;if(b.status==='Rental')stats.rental++;}}));
 byId('appContent').innerHTML=`
 <div class="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-7 gap-2 mb-5">${[['Items',stats.total],['At Supplier',stats.supplier],['Warehouse',stats.warehouse],['Transit',stats.transit],['At Client',stats.client],['Rental',stats.rental],['Maintenance',stats.maintenance]].map(([a,b])=>`<button class="statLog bg-slate-900 border border-slate-800 rounded-xl p-3 text-left" data-status="${a==='Items'?'':a==='Warehouse'?'At Warehouse':a==='Transit'?'In Transit':a}"><div class="text-xl font-black">${b}</div><div class="text-[10px] text-slate-500">${a}</div></button>`).join('')}</div>
 <div class="grid xl:grid-cols-2 gap-5">
  ${card('Register Item',registerFormHtml())}
  ${card('Move Item',moveFormHtml())}
  ${card('Active Transit / Arrival',arrivalHtml())}
  ${card('Maintenance / Inspection',maintenanceHtml())}
 </div>
 ${card('Find Item',itemFinderHtml(),'mt-5')}
 <div id="itemDetailMount" class="mt-5"></div>`;
 bindWorkspace();
}
function registerFormHtml(){return `<form id="registerForm" class="grid sm:grid-cols-2 gap-3">
 ${label('Item Type',`<select id="itemType" class="${inputCls}"><option>Equipment</option><option>Part</option></select>`)}
 ${label('Tracking Type',`<select id="trackingType" class="${inputCls}"><option value="serialized">Serialized / Individual</option><option value="quantity">Quantity / Bulk</option></select>`)}
 ${label('Item Code / Serial Number',`<input id="itemCode" required class="${inputCls}">`)}
 ${label('Item Name',`<input id="itemName" required class="${inputCls}" placeholder="Temporary or final name">`)}
 ${label('Category',`<select id="itemCategory" required class="${inputCls}"><option value="">-- Category --</option>${active('category').map(x=>`<option>${esc(x.value)}</option>`).join('')}</select>`)}
 <div class="grid grid-cols-2 gap-2">${label('Quantity',`<input type="number" id="itemQty" min="0.0001" step="any" value="1" required class="${inputCls}">`)}${label('Unit',`<select id="itemUnit" required class="${inputCls}"><option value="">-- Unit --</option>${active('unit').map(x=>`<option>${esc(x.value)}</option>`).join('')}</select>`)}</div>
 ${label('Supplier',`<select id="itemSupplier" class="${inputCls}"><option value="">-- Optional --</option>${suppliers.filter(x=>x.status!=='inactive').map(x=>`<option value="${x.id}">${esc(x.companyName||x.supplierName)}</option>`).join('')}</select>`)}
 ${label('Initial Position',`<select id="initialPosition" class="${inputCls}"><option value="supplier">At Supplier</option><option value="warehouse">At Warehouse</option></select>`)}
 <div id="initialLocationWrap" class="sm:col-span-2"></div>
 <div class="sm:col-span-2 border-t border-slate-800 pt-3"><div class="text-xs font-semibold text-amber-400 mb-2">Initial Document References (optional)</div><div class="grid sm:grid-cols-2 gap-2">${label('Our PO',`<input id="regPO" class="${inputCls}" placeholder="PO reference">`)}${label('Supplier Invoice',`<input id="regSupplierInvoice" class="${inputCls}" placeholder="Invoice reference">`)}${label('Supplier DO',`<input id="regSupplierDO" class="${inputCls}" placeholder="DO reference">`)}${label('Other',`<input id="regOtherDoc" class="${inputCls}" placeholder="Type | Reference">`)}</div></div>
 ${label('Remark',`<textarea id="itemRemark" rows="2" class="${inputCls}"></textarea>`)}
 <div class="flex items-end"><button class="w-full bg-red-600 hover:bg-red-500 py-2.5 rounded-lg text-sm font-bold">Register Item</button></div>
 </form>`;}
function moveFormHtml(){return `<form id="moveForm" class="space-y-3">
 ${label('Item',`<select id="moveItem" class="${inputCls}"><option value="">-- Select Item --</option>${inventory.map(i=>`<option value="${i.id}">${esc(i.itemCode)} — ${esc(i.name)} (${totalQty(i)} ${esc(i.unit)})</option>`).join('')}</select>`)}
 <div class="grid sm:grid-cols-2 gap-3">${label('From',`<select id="moveSource" class="${inputCls}"><option value="">-- Source --</option></select>`)}${label('Action',`<select id="moveAction" class="${inputCls}"><option value="">-- Choose source first --</option></select>`)}</div>
 <div id="moveDestinationWrap"></div>
 <div class="grid grid-cols-2 gap-2">${label('Quantity',`<input type="number" id="moveQty" min="0.0001" step="any" class="${inputCls}">`)}${label('Unit',`<select id="moveUnit" class="${inputCls}"><option value="">-- Unit --</option>${active('unit').map(x=>`<option>${esc(x.value)}</option>`).join('')}</select>`)}</div>
 <div class="grid sm:grid-cols-2 gap-3">${label('Transit Mode',`<select id="moveMode" class="${inputCls}"><option>Land Transport</option><option>Sea Freight</option><option>Air Freight</option><option>Internal Transfer</option></select>`)}${label('Transport / Job Detail',`<input id="moveDetail" class="${inputCls}" placeholder="Truck, vessel, job, site...">`)}</div>
 <div id="moveDocsWrap"></div>
 ${label('Remark',`<textarea id="moveRemark" rows="2" class="${inputCls}"></textarea>`)}
 <button class="w-full bg-cyan-700 hover:bg-cyan-600 py-2.5 rounded-lg text-sm font-bold">Start Movement</button>
 </form>`;}
function arrivalHtml(){const activeMov=movements.filter(x=>x.status==='in_transit');return activeMov.length?`<div class="space-y-2">${activeMov.map(m=>`<div class="bg-slate-950 border border-slate-800 rounded-xl p-3"><div class="flex flex-col sm:flex-row sm:items-center justify-between gap-2"><div><div class="text-sm font-semibold">${esc(actionDefs[m.action]?.label||m.actionLabel||m.type)}</div><div class="text-xs text-slate-400">${esc(m.itemCode||'')} — ${esc(m.itemNameSnapshot||'')} · ${m.qty} ${esc(m.unit||'')}</div><div class="text-[11px] text-slate-500">${esc(m.fromName)} → ${esc(m.toName)}</div></div><button onclick="arriveMovement('${m.id}')" class="bg-emerald-600 hover:bg-emerald-500 px-4 py-2 rounded-lg text-xs font-bold">${esc(arrivalLabel(m.toType))}</button></div></div>`).join('')}</div>`:'<div class="text-sm text-slate-500">No active movements.</div>';}
function arrivalLabel(t){return t==='warehouse'?'Arrive at Warehouse':t==='client'?'Arrive at Client':t==='maintenance'?'Arrive at Maintenance':'Mark Arrived';}
const maintDocMap={
 'Inspection':['Inspection Report','Inspection Checklist','Test Report'],
 'Preventive Maintenance':['Preventive Maintenance Report','Service Checklist','Parts / Consumables Ref'],
 'Repair':['Repair Report','Service Report','Parts Replacement Ref'],
 'Calibration':['Calibration Certificate','Calibration Report','Test Result'],
 'Certification / Recertification':['Certificate','Recertification Report','Inspection Report'],
 'Testing':['Test Report','Test Certificate','Result Sheet'],
 'Service':['Service Report','Work Order','Parts / Consumables Ref'],
 'Other':['Main Document','Supporting Document','Additional Reference']
};
function maintenanceHtml(){const maintItems=inventory.filter(i=>normalizeBalances(i).some(b=>b.locationType==='maintenance'));return `<form id="maintenanceForm" class="space-y-3">
 ${label('Item at Maintenance',`<select id="maintItem" class="${inputCls}"><option value="">-- Select item --</option>${maintItems.map(i=>`<option value="${i.id}">${esc(i.itemCode)} — ${esc(i.name)}</option>`).join('')}</select>`)}
 <div class="grid sm:grid-cols-2 gap-3">${label('Maintenance Type',`<select id="maintType" class="${inputCls}">${Object.keys(maintDocMap).map(x=>`<option>${esc(x)}</option>`).join('')}</select>`)}${label('Result / Status',`<select id="maintResult" class="${inputCls}"><option>Scheduled</option><option>In Progress</option><option>Pass</option><option>Conditional</option><option>Fail</option><option>Completed</option></select>`)}</div>
 <div class="grid sm:grid-cols-2 gap-3">${label('Event Date',`<input type="date" id="maintDate" class="${inputCls}" value="${nowISO().slice(0,10)}">`)}${label('Next Due Date',`<input type="date" id="maintNextDue" class="${inputCls}">`)}</div>
 ${label('Provider',`<input id="maintProvider" list="maintProviders" class="${inputCls}" placeholder="Maintenance / inspection provider"><datalist id="maintProviders">${suppliers.map(s=>`<option value="${esc(s.companyName||s.supplierName)}">`).join('')}</datalist>`)}
 <div id="maintDocsWrap"></div>
 ${label('Other Document References',`<textarea id="maintOtherDocs" rows="2" class="${inputCls}" placeholder="One per line: Document Type | Reference Number"></textarea>`)}
 ${label('Remark / Work Details',`<textarea id="maintRemark" rows="2" class="${inputCls}"></textarea>`)}
 <button class="w-full bg-amber-600 hover:bg-amber-500 py-2.5 rounded-lg text-sm font-bold">Save Maintenance Event</button>
 </form>`;}
function itemFinderHtml(){return `<div class="grid sm:grid-cols-[1fr_auto] gap-2"><input id="itemFind" class="${inputCls}" placeholder="Search item code, name, supplier, location or document ref..."><button id="itemFindBtn" class="bg-slate-700 hover:bg-slate-600 px-5 py-2 rounded-lg text-sm font-bold">Search</button></div><div id="itemFindResults" class="mt-3 space-y-2"></div>`;}

function bindWorkspace(){
 document.querySelectorAll('.statLog').forEach(b=>b.onclick=()=>{window._initialLogStatus=b.dataset.status;renderLogs();});
 byId('trackingType').onchange=()=>{const q=byId('itemQty');if(byId('trackingType').value==='serialized'){q.value=1;q.readOnly=true;}else q.readOnly=false;};
 byId('initialPosition').onchange=renderInitialLocation;byId('itemSupplier').onchange=renderInitialLocation;renderInitialLocation();
 byId('registerForm').onsubmit=registerItem;
 byId('moveItem').onchange=refreshMoveSources;byId('moveSource').onchange=refreshMoveActions;byId('moveAction').onchange=refreshMoveDestination;byId('moveForm').onsubmit=startMovement;
 byId('maintType').onchange=renderMaintDocs;renderMaintDocs();byId('maintenanceForm').onsubmit=saveMaintenance;
 byId('itemFindBtn').onclick=findItems;byId('itemFind').onkeyup=e=>{if(e.key==='Enter')findItems();};
}
function renderInitialLocation(){const p=byId('initialPosition').value,w=byId('initialLocationWrap');if(p==='supplier'){const sid=byId('itemSupplier').value,s=suppliers.find(x=>x.id===sid);w.innerHTML=label('Initial Location',`<input id="initialLocation" readonly class="${inputCls}" value="${esc(s?.companyName||s?.supplierName||'Select a supplier above')}">`);}else w.innerHTML=label('Initial Warehouse',`<select id="initialLocation" class="${inputCls}"><option value="">-- Warehouse --</option>${active('warehouse').map(x=>`<option>${esc(x.value)}</option>`).join('')}</select>`);}
async function registerItem(e){e.preventDefault();const code=byId('itemCode').value.trim();if(inventory.some(i=>norm(i.itemCode)===norm(code))){alert('Item Code / Serial Number already exists.');return;}const qty=Number(byId('itemQty').value),unit=byId('itemUnit').value,name=byId('itemName').value.trim(),position=byId('initialPosition').value,sid=byId('itemSupplier').value,s=suppliers.find(x=>x.id===sid),loc=byId('initialLocation').value.trim();if(!qty||!unit||!name||!loc){alert('Complete item name, quantity, unit and initial location.');return;}if(position==='supplier'&&!s){alert('Select the supplier for an item initially at supplier.');return;}const ref=doc(collection(db,'inventory')),status=statusForType(position),newItem={type:byId('itemType').value,trackingType:byId('trackingType').value,itemCode:code,name,category:byId('itemCategory').value,quantity:qty,unit,status,currentLocation:loc,supplierId:sid||'',supplierName:s?.companyName||s?.supplierName||'',stockBalances:[{qty,locationType:position,locationId:position==='supplier'?sid:'',locationName:loc,status}],remark:byId('itemRemark').value.trim(),createdBy:me.email,createdAt:nowISO(),lastEditedBy:null,lastEditedAt:null};await setDoc(ref,newItem);const docs=[['Our PO',byId('regPO').value],['Supplier Invoice',byId('regSupplierInvoice').value],['Supplier DO',byId('regSupplierDO').value]].filter(x=>x[1].trim());const oth=byId('regOtherDoc').value.trim();if(oth){const [t,...r]=oth.split('|');docs.push([t.trim()||'Other',r.join('|').trim()||oth]);}for(const [t,r] of docs)await createDocRef({item:{id:ref.id,...newItem},context:'Supplier / Registration',docType:t,refNumber:r,eventId:ref.id});await writeLog({activity:'REGISTER_ITEM',activityLabel:'Register Item',status,fromType:'',fromName:'',toType:position,toName:loc,qty,unit,supplierId:sid||'',supplierName:s?.companyName||s?.supplierName||'',clientId:'',clientName:'',...itemSnapshot({id:ref.id,...newItem}),remark:newItem.remark,documents:docs.map(([docType,refNumber])=>({docType,refNumber}))});await writeAudit('CREATE_ITEM','Main Workspace','inventory',code,null,{name,category:newItem.category,qty,unit,status,location:loc,supplier:newItem.supplierName},newItem.remark,ref.id);await loadAll();renderWorkspace();alert('Item registered.');}
function refreshMoveSources(){const item=inventory.find(i=>i.id===byId('moveItem').value),sel=byId('moveSource');sel.innerHTML='<option value="">-- Source --</option>';if(item)normalizeBalances(item).filter(b=>b.locationType!=='transit').forEach((b,i)=>sel.insertAdjacentHTML('beforeend',`<option value="${i}">${esc(b.locationName)} — ${b.qty} ${esc(item.unit)} (${esc(b.status)})</option>`));byId('moveUnit').value=item?.unit||'';refreshMoveActions();}
function selectedMoveBalance(){const item=inventory.find(i=>i.id===byId('moveItem').value),idx=Number(byId('moveSource').value);return {item,balance:item?normalizeBalances(item).filter(b=>b.locationType!=='transit')[idx]:null};}
function refreshMoveActions(){const {balance}=selectedMoveBalance(),sel=byId('moveAction');sel.innerHTML='<option value="">-- Action --</option>'+actionsForSource(balance?.locationType).map(k=>`<option value="${k}">${actionDefs[k].label}</option>`).join('');refreshMoveDestination();}
function refreshMoveDestination(){const action=byId('moveAction').value,d=actionDefs[action],wrap=byId('moveDestinationWrap');if(!d){wrap.innerHTML='';byId('moveDocsWrap').innerHTML='';return;}let dest='';if(d.toType==='warehouse')dest=label('To Warehouse',`<select id="moveDestination" class="${inputCls}"><option value="">-- Warehouse --</option>${active('warehouse').map(x=>`<option value="${x.id}" data-name="${esc(x.value)}">${esc(x.value)}</option>`).join('')}</select>`);else if(d.toType==='client')dest=label('To Client',`<select id="moveDestination" class="${inputCls}"><option value="">-- Client --</option>${clients.filter(x=>x.status!=='inactive').map(x=>`<option value="${x.id}" data-name="${esc(x.companyName||x.clientName)}">${esc(x.companyName||x.clientName)}</option>`).join('')}</select><select id="clientPositionStatus" class="${inputCls} mt-2"><option>At Client</option><option>Rental</option></select>`);else dest=label('To Maintenance Provider',`<input id="moveDestination" list="maintProviders2" class="${inputCls}" placeholder="Provider / workshop"><datalist id="maintProviders2">${suppliers.map(s=>`<option value="${esc(s.companyName||s.supplierName)}">`).join('')}</datalist>`);wrap.innerHTML=dest;renderMoveDocs(action);}
function renderMoveDocs(action){const common= action==='RECEIVE_SUPPLIER'?['Supplier DO','Goods Receipt / GRN','Packing List']: action==='DELIVER_CLIENT'?['Client PO','Our Delivery Order (DO)','Our Invoice']: action==='RETURN_CLIENT'?['Return DO','Client Return Ref','Inspection Ref']: action==='SEND_MAINTENANCE'?['Service Request / Repair Order','Return / Dispatch DO','Inspection / Damage Ref']: action==='RETURN_MAINTENANCE'?['Service Report','Maintenance DO','Test / Release Ref']:['Transfer Note','Delivery / Transport Document','Other'];byId('moveDocsWrap').innerHTML=`<div class="border-t border-slate-800 pt-3"><div class="text-xs font-semibold text-amber-400 mb-2">Relevant Document References</div><div class="grid sm:grid-cols-2 gap-2">${common.map((t,i)=>label(t,`<input class="moveDoc ${inputCls}" data-type="${esc(t)}" placeholder="Reference number">`)).join('')}${label('Other',`<input id="moveOtherDoc" class="${inputCls}" placeholder="Document Type | Reference">`)}</div></div>`;}
async function startMovement(e){e.preventDefault();const {item,balance}=selectedMoveBalance(),action=byId('moveAction').value,d=actionDefs[action],qty=Number(byId('moveQty').value),unit=byId('moveUnit').value;if(!item||!balance||!d||qty<=0||qty>balance.qty){alert('Select valid item, source, action and quantity.');return;}if(unit!==item.unit){alert(`Unit must match the item's master unit (${item.unit}).`);return;}if(item.trackingType==='serialized'&&qty!==1){alert('Serialized items must move as quantity 1.');return;}let toId='',toName='';const dest=byId('moveDestination');if(d.toType==='maintenance'){toName=dest.value.trim();}else{toId=dest.value;toName=dest.selectedOptions[0]?.dataset.name||dest.selectedOptions[0]?.textContent||'';}if(!toName){alert('Select a destination.');return;}const clientStatus=d.toType==='client'?(byId('clientPositionStatus')?.value||'At Client'):statusForType(d.toType);const docs=[...document.querySelectorAll('.moveDoc')].map(x=>({docType:x.dataset.type,refNumber:x.value.trim()})).filter(x=>x.refNumber);const o=byId('moveOtherDoc')?.value.trim();if(o){const [t,...r]=o.split('|');docs.push({docType:t.trim()||'Other',refNumber:r.join('|').trim()||o});}
 const movementRef=doc(collection(db,'movements')),movementId=movementRef.id,transitName=`Transit to ${toName}`;
 await runTransaction(db,async tx=>{const ref=doc(db,'inventory',item.id),snap=await tx.get(ref);if(!snap.exists())throw new Error('Item missing');const cur=snap.data(),bal=normalizeBalances(cur),src=bal.find(b=>b.locationType===balance.locationType&&b.locationName===balance.locationName&&b.qty>=qty);if(!src)throw new Error('Source stock changed. Refresh and retry.');src.qty-=qty;let tr=bal.find(b=>b.locationType==='transit'&&b.locationId===movementId);if(tr)tr.qty+=qty;else bal.push({qty,locationType:'transit',locationId:movementId,locationName:transitName,status:'In Transit'});const clean=bal.filter(x=>x.qty>0),sum=summarizeBalances(clean);tx.update(ref,{stockBalances:clean,status:sum.status,currentLocation:sum.location,lastEditedBy:me.email,lastEditedAt:nowISO()});tx.set(movementRef,{movementId,itemId:item.id,itemCode:item.itemCode,itemNameSnapshot:item.name,categorySnapshot:item.category,supplierId:item.supplierId||'',supplierNameSnapshot:item.supplierName||'',action,actionLabel:d.label,fromType:balance.locationType,fromId:balance.locationId||'',fromName:balance.locationName,toType:d.toType,toId,toName,toStatus:clientStatus,qty,unit,mode:byId('moveMode').value,detail:byId('moveDetail').value.trim(),remark:byId('moveRemark').value.trim(),documents:docs,status:'in_transit',createdAt:nowISO(),createdBy:me.email,createdByRole:me.role});});
 for(const x of docs)await createDocRef({item,context:actionDefs[action].label,docType:x.docType,refNumber:x.refNumber,eventId:movementId});
 await writeLog({activity:action,activityLabel:d.label,status:'In Transit',fromType:balance.locationType,fromName:balance.locationName,toType:d.toType,toName,qty,unit,supplierId:item.supplierId||'',supplierName:item.supplierName||'',clientId:d.toType==='client'?toId:'',clientName:d.toType==='client'?toName:'',...itemSnapshot(item),remark:byId('moveRemark').value.trim(),documents:docs});
 await writeAudit('START_MOVEMENT','Main Workspace','movement',`${item.itemCode} ${d.label}`,null,{from:balance.locationName,to:toName,qty,unit,mode:byId('moveMode').value,documents:docs},byId('moveRemark').value.trim(),movementId);await loadAll();renderWorkspace();alert('Movement started and item is now in transit.');}
window.arriveMovement=async id=>{const m=movements.find(x=>x.id===id);if(!m)return;const ref=doc(db,'inventory',m.itemId);await runTransaction(db,async tx=>{const snap=await tx.get(ref);if(!snap.exists())throw new Error('Item missing');const cur=snap.data(),bal=normalizeBalances(cur),tr=bal.find(b=>b.locationType==='transit'&&b.locationId===m.movementId);if(!tr||tr.qty<m.qty)throw new Error('Transit balance missing');tr.qty-=m.qty;let dst=bal.find(b=>b.locationType===m.toType&&((m.toId&&b.locationId===m.toId)||b.locationName===m.toName));if(dst){dst.qty+=m.qty;dst.status=m.toStatus||statusForType(m.toType);}else bal.push({qty:m.qty,locationType:m.toType,locationId:m.toId||'',locationName:m.toName,status:m.toStatus||statusForType(m.toType)});const clean=bal.filter(x=>x.qty>0),sum=summarizeBalances(clean);tx.update(ref,{stockBalances:clean,status:sum.status,currentLocation:sum.location,lastEditedBy:me.email,lastEditedAt:nowISO()});tx.update(doc(db,'movements',id),{status:'arrived',arrivedAt:nowISO(),arrivedBy:me.email});});const item=inventory.find(i=>i.id===m.itemId)||{id:m.itemId,itemCode:m.itemCode,name:m.itemNameSnapshot,category:m.categorySnapshot,unit:m.unit,supplierId:m.supplierId,supplierName:m.supplierNameSnapshot};await writeLog({activity:'ARRIVAL',activityLabel:arrivalLabel(m.toType),status:m.toStatus||statusForType(m.toType),fromType:'transit',fromName:`Transit from ${m.fromName}`,toType:m.toType,toName:m.toName,qty:m.qty,unit:m.unit,supplierId:m.supplierId||'',supplierName:m.supplierNameSnapshot||'',clientId:m.toType==='client'?m.toId:'',clientName:m.toType==='client'?m.toName:'',...itemSnapshot(item),remark:m.remark||'',movementId:m.movementId});await writeAudit('ARRIVE_MOVEMENT','Main Workspace','movement',`${m.itemCode} ${arrivalLabel(m.toType)}`,{status:'In Transit',from:m.fromName,to:m.toName},{status:m.toStatus||statusForType(m.toType),location:m.toName,qty:m.qty,unit:m.unit},m.remark||'',m.movementId);await loadAll();renderWorkspace();};
function renderMaintDocs(){const t=byId('maintType')?.value||'Inspection',fields=maintDocMap[t]||maintDocMap.Other;byId('maintDocsWrap').innerHTML=`<div class="grid sm:grid-cols-3 gap-2">${fields.map(x=>label(x,`<input class="maintDoc ${inputCls}" data-type="${esc(x)}" placeholder="Reference number">`)).join('')}</div>`;}
async function saveMaintenance(e){e.preventDefault();const item=inventory.find(i=>i.id===byId('maintItem').value);if(!item){alert('Select an item currently at maintenance.');return;}const type=byId('maintType').value,result=byId('maintResult').value,eventDate=byId('maintDate').value,nextDue=byId('maintNextDue').value,provider=byId('maintProvider').value.trim(),remark=byId('maintRemark').value.trim();let docs=[...document.querySelectorAll('.maintDoc')].map(x=>({docType:x.dataset.type,refNumber:x.value.trim()})).filter(x=>x.refNumber);byId('maintOtherDocs').value.split('\n').map(x=>x.trim()).filter(Boolean).forEach(line=>{const [t,...r]=line.split('|');docs.push({docType:t.trim()||'Other',refNumber:r.join('|').trim()||line});});const ref=doc(collection(db,'maintenance_events'));await setDoc(ref,{eventId:ref.id,itemId:item.id,itemCode:item.itemCode,itemNameSnapshot:item.name,maintenanceType:type,eventType:type,eventStatus:result,eventDate,nextDueDate:nextDue,provider,remark,documents:docs,createdBy:me.email,createdByRole:me.role,createdAt:nowISO()});for(const x of docs)await createDocRef({item,context:`Maintenance / ${type}`,docType:x.docType,refNumber:x.refNumber,eventId:ref.id});await writeLog({activity:'MAINTENANCE_EVENT',activityLabel:`Maintenance — ${type}`,status:'In Maintenance',fromType:'maintenance',fromName:provider||'Maintenance',toType:'maintenance',toName:provider||'Maintenance',qty:'',unit:item.unit||'',supplierId:item.supplierId||'',supplierName:item.supplierName||'',clientId:'',clientName:'',...itemSnapshot(item),remark:`${result}${remark?` — ${remark}`:''}`,documents:docs,maintenanceResult:result,nextDueDate:nextDue});await writeAudit('CREATE_MAINTENANCE_EVENT','Main Workspace','maintenance',`${item.itemCode} — ${type}`,null,{result,eventDate,nextDueDate:nextDue,provider,documents:docs},remark,ref.id);await loadAll();renderWorkspace();alert('Maintenance event recorded.');}
function findItems(){const q=norm(byId('itemFind').value);const docItemIds=new Set(documents.filter(d=>norm(`${d.refNumber} ${d.docType}`).includes(q)).map(d=>d.itemId));const arr=inventory.filter(i=>!q||norm(`${i.itemCode} ${i.name} ${i.category} ${i.supplierName} ${JSON.stringify(normalizeBalances(i))}`).includes(q)||docItemIds.has(i.id));byId('itemFindResults').innerHTML=arr.slice(0,100).map(i=>`<button onclick="openItem('${i.id}')" class="w-full text-left bg-slate-950 hover:bg-slate-800 border border-slate-800 rounded-xl p-3"><div class="flex justify-between gap-3"><div><div class="font-semibold text-sm">${esc(i.itemCode)} — ${esc(i.name)}</div><div class="text-[11px] text-slate-500">${esc(i.category)} · ${esc(i.supplierName||'No supplier')}</div></div><div class="text-right"><div class="font-bold">${totalQty(i)} ${esc(i.unit||'')}</div><div class="text-[10px] text-slate-500">${esc(i.status||'')}</div></div></div></button>`).join('')||'<div class="text-sm text-slate-500">No matching items.</div>';}
window.openItem=id=>{currentItemId=id;const i=inventory.find(x=>x.id===id);if(!i)return;const bal=normalizeBalances(i),docs=documents.filter(d=>d.itemId===id).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))),maint=maintenance.filter(x=>x.itemId===id).sort((a,b)=>String(b.eventDate||b.createdAt).localeCompare(String(a.eventDate||a.createdAt))),itemLogs=logs.filter(x=>x.itemId===id||x.itemCode===i.itemCode).sort((a,b)=>String(b.date).localeCompare(String(a.date)));const docRows=docs.map(d=>{const replacement=documents.find(x=>x.id===d.supersededBy);return `<tr><td class="p-2">${esc(d.context)}</td><td class="p-2">${esc(d.docType)}</td><td class="p-2 font-mono">${d.status==='superseded'?`<s class="text-slate-500">${esc(d.refNumber)}</s>${replacement?` <span class="text-slate-500">→</span> <strong class="text-emerald-300">${esc(replacement.refNumber)}</strong>`:''}`:esc(d.refNumber)}</td><td class="p-2">${esc(d.status||'current')}</td><td class="p-2">${esc(d.createdAt?.slice(0,10)||'')}</td><td class="p-2">${CAN_EDIT_ITEM&&d.status!=='superseded'?`<button onclick="correctDoc('${d.id}')" class="bg-slate-700 px-2 py-1 rounded text-[10px]">Correct</button>`:''}</td></tr>`;}).join('');byId('itemDetailMount').innerHTML=card(`${esc(i.itemCode)} — ${esc(i.name)}`,`<div class="grid lg:grid-cols-3 gap-4"><div class="lg:col-span-2"><div class="grid sm:grid-cols-2 gap-2 text-xs"><div class="bg-slate-950 rounded-xl p-3"><div class="text-slate-500">Category</div><strong>${esc(i.category)}</strong></div><div class="bg-slate-950 rounded-xl p-3"><div class="text-slate-500">Supplier</div><strong>${esc(i.supplierName||'—')}</strong></div></div><div class="mt-3 bg-slate-950 rounded-xl p-3"><div class="font-semibold text-sm mb-2">Current Balances</div>${bal.map(b=>`<div class="flex justify-between py-1 border-b border-slate-900 text-xs"><span>${esc(b.locationName)} <span class="text-slate-500">(${esc(b.status)})</span></span><strong>${b.qty} ${esc(i.unit)}</strong></div>`).join('')}</div></div><div class="space-y-2">${CAN_EDIT_ITEM?`<button onclick="editItemName('${i.id}')" class="w-full bg-slate-700 hover:bg-slate-600 py-2 rounded-lg text-xs font-bold">Edit Item Name</button>`:''}<button onclick="addManualDoc('${i.id}')" class="w-full bg-violet-700 hover:bg-violet-600 py-2 rounded-lg text-xs font-bold">Add Document Reference</button></div></div>
 <div class="mt-5"><h3 class="text-sm font-bold mb-2">Documents</h3><div class="overflow-x-auto"><table class="w-full min-w-[850px] text-xs"><thead class="text-slate-500"><tr><th class="p-2 text-left">Context</th><th class="p-2 text-left">Type</th><th class="p-2 text-left">Reference</th><th class="p-2 text-left">Status</th><th class="p-2 text-left">Date</th><th></th></tr></thead><tbody>${docRows||'<tr><td colspan="6" class="p-3 text-slate-500">No document references.</td></tr>'}</tbody></table></div></div>
 <div class="grid lg:grid-cols-2 gap-4 mt-5"><div><h3 class="text-sm font-bold mb-2">Maintenance History</h3><div class="space-y-2 max-h-72 overflow-y-auto">${maint.map(x=>`<div class="bg-slate-950 rounded-xl p-3 text-xs"><div class="font-semibold">${esc(x.maintenanceType||x.eventType)} — ${esc(x.eventStatus)}</div><div class="text-slate-500">${esc(x.eventDate||'')} · ${esc(x.provider||'')}</div><div>${esc(x.remark||'')}</div></div>`).join('')||'<div class="text-xs text-slate-500">No maintenance events.</div>'}</div></div><div><h3 class="text-sm font-bold mb-2">Recent Item Record</h3><div class="space-y-2 max-h-72 overflow-y-auto">${itemLogs.slice(0,30).map(x=>`<div class="bg-slate-950 rounded-xl p-3 text-xs"><div class="font-semibold">${esc(x.activityLabel||friendlyAction(x.activity))}</div><div class="text-slate-500">${displayDate(x.date)} · ${esc(x.performedBy||'')}</div><div>${esc(x.fromName||'')} ${x.toName?`→ ${esc(x.toName)}`:''} ${x.qty!==''&&x.qty!==undefined?`· ${esc(x.qty)} ${esc(x.unit||'')}`:''}</div></div>`).join('')||'<div class="text-xs text-slate-500">No operational logs.</div>'}</div></div></div>`);byId('itemDetailMount').scrollIntoView({behavior:'smooth',block:'start'});};
window.editItemName=async id=>{const item=inventory.find(x=>x.id===id);if(!item||!CAN_EDIT_ITEM)return;const val=prompt('Edit item name',item.name);if(!val||val.trim()===item.name)return;const reason=prompt('Reason for changing item name (required)','');if(!reason?.trim())return;const old=item.name,newName=val.trim();await updateDoc(doc(db,'inventory',id),{name:newName,lastEditedBy:me.email,lastEditedAt:nowISO()});await writeLog({activity:'UPDATE_ITEM_NAME',activityLabel:'Update Item Name',status:item.status,fromName:item.currentLocation,toName:item.currentLocation,qty:totalQty(item),unit:item.unit,...itemSnapshot(item),itemName:newName,previousItemName:old,remark:reason.trim()});await writeAudit('UPDATE_ITEM_NAME','Main Workspace','inventory',item.itemCode,{name:old},{name:newName},reason.trim(),id);await loadAll();renderWorkspace();openItem(id);};

async function createDocRef({item,context,docType,refNumber,eventId=''}){if(!String(refNumber||'').trim())return null;const ref=doc(collection(db,'document_refs')),rec={itemId:item.id,itemCode:item.itemCode,itemNameSnapshot:item.name,categorySnapshot:item.category||'',supplierId:item.supplierId||'',supplierNameSnapshot:item.supplierName||'',context,docType:String(docType||'Other').trim(),refNumber:String(refNumber).trim(),eventId,status:'current',createdAt:nowISO(),createdBy:me.email,createdByRole:me.role};await setDoc(ref,rec);return {id:ref.id,...rec};}
window.addManualDoc=async itemId=>{const item=inventory.find(x=>x.id===itemId);if(!item)return;const context=prompt('Document context (e.g. Supplier, Client, Maintenance, Certification)','Other');if(!context)return;const type=prompt('Document type','Other');if(!type)return;const refNumber=prompt('Document reference number','');if(!refNumber?.trim())return;const rec=await createDocRef({item,context:context.trim(),docType:type.trim(),refNumber:refNumber.trim()});await writeLog({activity:'ADD_DOCUMENT_REF',activityLabel:'Add Document Reference',status:item.status,fromName:item.currentLocation,toName:item.currentLocation,qty:'',unit:item.unit,...itemSnapshot(item),remark:`${type}: ${refNumber}`,documents:[{docType:type,refNumber}]});await writeAudit('CREATE_DOCUMENT_REF','Documents','document_ref',`${item.itemCode} ${type}`,null,{context,type,refNumber},'',rec?.id||'');await loadAll();renderWorkspace();openItem(itemId);};
window.correctDoc=async docId=>{if(!CAN_EDIT_ITEM)return;const old=documents.find(x=>x.id===docId);if(!old||old.status==='superseded')return;const newRef=prompt('Correct document reference',old.refNumber);if(!newRef||newRef.trim()===old.refNumber)return;const reason=prompt('Reason for correction (required)','');if(!reason?.trim())return;const item=inventory.find(x=>x.id===old.itemId)||{id:old.itemId,itemCode:old.itemCode,name:old.itemNameSnapshot,category:old.categorySnapshot,supplierId:old.supplierId,supplierName:old.supplierNameSnapshot};const rec=await createDocRef({item,context:old.context,docType:old.docType,refNumber:newRef.trim(),eventId:old.eventId});await updateDoc(doc(db,'document_refs',docId),{status:'superseded',supersededBy:rec.id,supersededAt:nowISO(),supersededByUser:me.email,supersedeReason:reason.trim()});await updateDoc(doc(db,'document_refs',rec.id),{replaces:docId,correctionReason:reason.trim()});await writeLog({activity:'CORRECT_DOCUMENT_REF',activityLabel:'Correct Document Reference',status:item.status||'',fromName:item.currentLocation||'',toName:item.currentLocation||'',qty:'',unit:item.unit||'',...itemSnapshot(item),remark:reason.trim(),documents:[{docType:old.docType,oldRef:old.refNumber,newRef:newRef.trim()}]});await writeAudit('SUPERSEDE_DOCUMENT_REF','Documents','document_ref',`${old.itemCode} ${old.docType}`,{refNumber:old.refNumber,status:'current'},{refNumber:newRef.trim(),status:'current',oldStatus:'superseded'},reason.trim(),rec.id,{supersededId:docId});await loadAll();renderWorkspace();openItem(old.itemId);};

function renderLogs(){setNav('logs','Logs / Records','Historical operational truth: filter, sort, select and export exactly what you need.');const statusVals=[...new Set(logs.map(x=>x.status).filter(Boolean))].sort(),itemVals=inventory.map(i=>[i.id,`${i.itemCode} — ${i.name}`]),supplierVals=suppliers.map(x=>[x.id,x.companyName||x.supplierName]),clientVals=clients.map(x=>[x.id,x.companyName||x.clientName]);byId('appContent').innerHTML=`${card('Record Filters',`<div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-2">${label('Search',`<input id="logSearch" class="${inputCls}" placeholder="Item, ref, client, supplier, remark...">`)}${label('Status',`<select multiple id="logStatus" class="${inputCls} h-28"><option value="">All Statuses</option>${statusVals.map(x=>`<option ${window._initialLogStatus===x?'selected':''}>${esc(x)}</option>`).join('')}</select>`)}${label('Items',`<select multiple id="logItems" class="${inputCls} h-28"><option value="">All Items</option>${itemVals.map(([id,n])=>`<option value="${id}">${esc(n)}</option>`).join('')}</select>`)}${label('Suppliers',`<select multiple id="logSuppliers" class="${inputCls} h-28"><option value="">All Suppliers</option>${supplierVals.map(([id,n])=>`<option value="${id}">${esc(n)}</option>`).join('')}</select>`)}${label('Clients',`<select multiple id="logClients" class="${inputCls} h-28"><option value="">All Clients</option>${clientVals.map(([id,n])=>`<option value="${id}">${esc(n)}</option>`).join('')}</select>`)}${label('From Date',`<input type="date" id="logFrom" class="${inputCls}">`)}${label('To Date',`<input type="date" id="logTo" class="${inputCls}">`)}${label('Sort',`<select id="logSort" class="${inputCls}"><option value="date|desc">Date — newest</option><option value="date|asc">Date — oldest</option><option value="itemCode|asc">Item — A to Z</option><option value="status|asc">Status — A to Z</option><option value="supplierName|asc">Supplier — A to Z</option><option value="clientName|asc">Client — A to Z</option></select>`)}</div><div class="flex flex-wrap gap-2 mt-3"><button id="applyLogFilters" class="bg-red-600 px-4 py-2 rounded-lg text-xs font-bold">Apply Filters</button><button id="clearLogFilters" class="bg-slate-700 px-4 py-2 rounded-lg text-xs">Clear</button><button id="exportLogExcel" class="bg-emerald-700 px-4 py-2 rounded-lg text-xs font-bold">Export Filtered Excel</button><button id="exportLogCsv" class="bg-emerald-800 px-4 py-2 rounded-lg text-xs font-bold">Export Filtered CSV</button><button id="exportLogSelected" class="bg-cyan-700 px-4 py-2 rounded-lg text-xs font-bold">Export Selected Excel</button></div>`) }
 ${card('Operational Records',`<div id="logCount" class="text-xs text-slate-500 mb-2"></div><div class="overflow-auto max-h-[65vh] border border-slate-800 rounded-xl"><table class="w-full min-w-[1500px] text-xs"><thead class="sticky top-0 bg-slate-950 text-slate-400"><tr><th class="p-2"><input id="logSelectAll" type="checkbox"></th>${[['date','Date'],['itemCode','Item'],['itemName','Name'],['activityLabel','Activity'],['status','Status'],['fromName','From'],['toName','To'],['qty','Qty'],['unit','Unit'],['supplierName','Supplier'],['clientName','Client'],['performedBy','User'],['remark','Remark']].map(([f,n])=>`<th class="p-2 text-left cursor-pointer logSortHead" data-field="${f}">${n} ↕</th>`).join('')}</tr></thead><tbody id="logBody"></tbody></table></div>`)}`;window._initialLogStatus='';['logSearch','logStatus','logItems','logSuppliers','logClients','logFrom','logTo'].forEach(id=>byId(id).onchange=applyLogFilters);byId('logSearch').onkeyup=applyLogFilters;byId('applyLogFilters').onclick=applyLogFilters;byId('clearLogFilters').onclick=()=>renderLogs();byId('logSort').onchange=()=>{const [field,dir]=byId('logSort').value.split('|');logSort={field,dir};applyLogFilters();};document.querySelectorAll('.logSortHead').forEach(h=>h.onclick=()=>{logSort={field:h.dataset.field,dir:logSort.field===h.dataset.field&&logSort.dir==='asc'?'desc':'asc'};applyLogFilters();});byId('exportLogExcel').onclick=()=>exportLogs('excel',false);byId('exportLogCsv').onclick=()=>exportLogs('csv',false);byId('exportLogSelected').onclick=()=>exportLogs('excel',true);byId('logSelectAll').onchange=e=>document.querySelectorAll('.logRowCheck').forEach(x=>x.checked=e.target.checked);applyLogFilters();}
function selectedValues(id){return [...byId(id).selectedOptions].map(x=>x.value).filter(Boolean);}
function applyLogFilters(){const q=norm(byId('logSearch').value),statuses=selectedValues('logStatus'),items=selectedValues('logItems'),sups=selectedValues('logSuppliers'),cls=selectedValues('logClients'),from=byId('logFrom').value,to=byId('logTo').value;filteredLogs=logs.filter(x=>{const d=String(x.date||'').slice(0,10),hay=norm(JSON.stringify(x));return(!q||hay.includes(q))&&(!statuses.length||statuses.includes(x.status))&&(!items.length||items.includes(x.itemId))&&(!sups.length||sups.includes(x.supplierId))&&(!cls.length||cls.includes(x.clientId))&&(!from||d>=from)&&(!to||d<=to);});filteredLogs.sort((a,b)=>{const av=a[logSort.field]??'',bv=b[logSort.field]??'';const n=Number(av)-Number(bv);const c=(logSort.field==='qty'&&Number.isFinite(n))?n:String(av).localeCompare(String(bv));return logSort.dir==='asc'?c:-c;});byId('logCount').textContent=`${filteredLogs.length} record(s) shown from ${logs.length}.`;byId('logBody').innerHTML=filteredLogs.map(x=>`<tr class="border-t border-slate-900 hover:bg-slate-800/40"><td class="p-2"><input class="logRowCheck" value="${x.id}" type="checkbox"></td><td class="p-2 whitespace-nowrap">${esc(displayDate(x.date))}</td><td class="p-2 font-mono">${esc(x.itemCode||'')}</td><td class="p-2">${esc(x.itemName||x.itemNameSnapshot||'')}</td><td class="p-2">${esc(x.activityLabel||friendlyAction(x.activity))}</td><td class="p-2">${esc(x.status||'')}</td><td class="p-2">${esc(x.fromName||'')}</td><td class="p-2">${esc(x.toName||'')}</td><td class="p-2">${esc(x.qty??'')}</td><td class="p-2">${esc(x.unit||'')}</td><td class="p-2">${esc(x.supplierName||'')}</td><td class="p-2">${esc(x.clientName||'')}</td><td class="p-2">${esc(x.performedBy||'')}</td><td class="p-2 max-w-[250px]">${esc(x.remark||'')}</td></tr>`).join('')||'<tr><td colspan="14" class="p-5 text-center text-slate-500">No matching records.</td></tr>';}
function logExportRows(rows){return rows.map(x=>({Date:x.date,ItemCode:x.itemCode,ItemName:x.itemName||x.itemNameSnapshot,Category:x.category,Activity:x.activityLabel||friendlyAction(x.activity),Status:x.status,From:x.fromName,To:x.toName,Qty:x.qty,Unit:x.unit,Supplier:x.supplierName,Client:x.clientName,User:x.performedBy,Role:x.performedByRole,Remark:x.remark,Documents:(x.documents||[]).map(d=>`${d.docType}: ${d.refNumber||d.newRef||''}`).join(' | ')}));}
function exportLogs(format,selected){let rows=filteredLogs;if(selected){const ids=[...document.querySelectorAll('.logRowCheck:checked')].map(x=>x.value);rows=filteredLogs.filter(x=>ids.includes(x.id));if(!rows.length){alert('Select record rows first.');return;}}const data=logExportRows(rows),stamp=nowISO().slice(0,10);if(format==='csv'){const ws=XLSX.utils.json_to_sheet(data),csv=XLSX.utils.sheet_to_csv(ws);downloadText(`IMS_Records_${stamp}.csv`,csv,'text/csv');}else{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data),'Records');XLSX.writeFile(wb,`IMS_Records_${selected?'Selected':'Filtered'}_${stamp}.xlsx`);}writeAudit('EXPORT_RECORDS','Logs','record_export',selected?'Selected Records':'Filtered Records',null,{count:rows.length,format},'', '',{filterSort:logSort});}

function businessFields(kind,x={}){const pre=kind==='supplier'?'supplier':'client';return `<input type="hidden" id="bizId" value="${esc(x.id||'')}"><div class="grid sm:grid-cols-2 gap-3">${label('Company Name',`<input id="bizCompany" required class="${inputCls}" value="${esc(x.companyName||x[pre+'Name']||'')}">`)}${label('Registration No.',`<input id="bizReg" class="${inputCls}" value="${esc(x.registrationNo||'')}">`)}${label('Contact Person',`<input id="bizContact" class="${inputCls}" value="${esc(x.contactPerson||x.contact||'')}">`)}${label('Telephone',`<input id="bizTel" class="${inputCls}" value="${esc(x.tel||'')}">`)}${label('Mobile',`<input id="bizMobile" class="${inputCls}" value="${esc(x.mobile||'')}">`)}${label('Fax',`<input id="bizFax" class="${inputCls}" value="${esc(x.fax||'')}">`)}${label('Email',`<input type="email" id="bizEmail" class="${inputCls}" value="${esc(x.email||'')}">`)}${label('Website',`<input id="bizWebsite" class="${inputCls}" value="${esc(x.website||'')}">`)}<div class="sm:col-span-2">${label('Address',`<textarea id="bizAddress" rows="2" class="${inputCls}">${esc(x.address||'')}</textarea>`)}</div>${label('Country',`<input id="bizCountry" class="${inputCls}" value="${esc(x.country||'Malaysia')}">`)}${label('Business Code',`<input id="bizCode" class="${inputCls}" value="${esc(x.businessCode||'')}">`)}<div class="sm:col-span-2">${label('Remark',`<textarea id="bizRemark" rows="2" class="${inputCls}">${esc(x.remark||'')}</textarea>`)}</div></div>`;}
function renderBusinesses(kind){const data=kind==='supplier'?suppliers:clients,title=kind==='supplier'?'Suppliers':'Clients';setNav(kind,title,`${title} are business master records; operational work stays in Main Workspace.`);byId('appContent').innerHTML=`<div class="grid lg:grid-cols-2 gap-5">${card(`${kind==='supplier'?'Supplier':'Client'} Details`,`<form id="bizForm" class="space-y-3">${businessFields(kind)}<div class="flex gap-2"><button class="flex-1 bg-red-600 py-2.5 rounded-lg text-sm font-bold">Save ${title.slice(0,-1)}</button><button type="button" id="bizReset" class="bg-slate-700 px-4 rounded-lg text-xs">Clear</button></div></form>`)}${card(`${title} Directory`,`<input id="bizSearch" class="${inputCls}" placeholder="Search company, contact, email, phone..."><div id="bizList" class="mt-3 space-y-2 max-h-[70vh] overflow-y-auto"></div>`)}</div>`;byId('bizForm').onsubmit=e=>saveBusiness(e,kind);byId('bizReset').onclick=()=>renderBusinesses(kind);byId('bizSearch').onkeyup=()=>renderBizList(kind);renderBizList(kind);}
function renderBizList(kind){const data=kind==='supplier'?suppliers:clients,q=norm(byId('bizSearch')?.value||'');byId('bizList').innerHTML=data.filter(x=>!q||norm(JSON.stringify(x)).includes(q)).map(x=>`<div class="bg-slate-950 border border-slate-800 rounded-xl p-3"><div class="flex justify-between gap-2"><div><div class="font-semibold text-sm">${esc(x.companyName||x[kind+'Name'])}</div><div class="text-[11px] text-slate-500">${esc(x.contactPerson||x.contact||'')} · ${esc(x.tel||x.mobile||'')} · ${esc(x.email||'')}</div><div class="text-[10px] mt-1 ${x.status==='inactive'?'text-amber-400':'text-emerald-400'}">${x.status||'active'}</div></div><div class="flex gap-1"><button onclick="editBusiness('${kind}','${x.id}')" class="bg-slate-700 px-2 py-1 rounded text-[10px]">Edit</button>${CAN_MANAGE_MASTER?`<button onclick="toggleBusiness('${kind}','${x.id}')" class="bg-slate-700 px-2 py-1 rounded text-[10px]">${x.status==='inactive'?'Activate':'Deactivate'}</button>`:''}</div></div></div>`).join('')||'<div class="text-sm text-slate-500">No records.</div>';}
window.editBusiness=(kind,id)=>{const x=(kind==='supplier'?suppliers:clients).find(y=>y.id===id);if(!x)return;const form=byId('bizForm');form.innerHTML=`${businessFields(kind,x)}<div class="flex gap-2"><button class="flex-1 bg-red-600 py-2.5 rounded-lg text-sm font-bold">Save Changes</button><button type="button" onclick="renderBusinesses('${kind}')" class="bg-slate-700 px-4 rounded-lg text-xs">Cancel</button></div>`;form.onsubmit=e=>saveBusiness(e,kind);};
async function saveBusiness(e,kind){e.preventDefault();const id=byId('bizId').value,old=(kind==='supplier'?suppliers:clients).find(x=>x.id===id),company=byId('bizCompany').value.trim();if(!company)return;const rec={companyName:company,[kind+'Name']:company,registrationNo:byId('bizReg').value.trim(),contactPerson:byId('bizContact').value.trim(),contact:byId('bizContact').value.trim(),tel:byId('bizTel').value.trim(),mobile:byId('bizMobile').value.trim(),fax:byId('bizFax').value.trim(),email:byId('bizEmail').value.trim(),website:byId('bizWebsite').value.trim(),address:byId('bizAddress').value.trim(),country:byId('bizCountry').value.trim(),businessCode:byId('bizCode').value.trim(),remark:byId('bizRemark').value.trim(),status:old?.status||'active',updatedAt:nowISO(),updatedBy:me.email};if(old){const reason=prompt('Reason for editing this business record (required)','');if(!reason?.trim())return;await updateDoc(doc(db,kind+'_profiles',id),rec);await writeAudit('EDIT_BUSINESS',kind==='supplier'?'Suppliers':'Clients',kind,company,old,rec,reason.trim(),id);}else{rec.createdAt=nowISO();rec.createdBy=me.email;const ref=await addDoc(collection(db,kind+'_profiles'),rec);await writeAudit('CREATE_BUSINESS',kind==='supplier'?'Suppliers':'Clients',kind,company,null,rec,'',ref.id);}await loadAll();renderBusinesses(kind);}
window.toggleBusiness=async(kind,id)=>{if(!CAN_MANAGE_MASTER)return;const x=(kind==='supplier'?suppliers:clients).find(y=>y.id===id);if(!x)return;const status=x.status==='inactive'?'active':'inactive',reason=prompt(`Reason for ${status==='inactive'?'deactivating':'activating'} this business (required)`,'');if(!reason?.trim())return;await updateDoc(doc(db,kind+'_profiles',id),{status,updatedAt:nowISO(),updatedBy:me.email});await writeAudit('CHANGE_BUSINESS_STATUS',kind==='supplier'?'Suppliers':'Clients',kind,x.companyName||x[kind+'Name'],{status:x.status||'active'},{status},reason.trim(),id);await loadAll();renderBusinesses(kind);};

function renderSettings(){setNav('settings','Global Settings','Master values are never deleted; operational masters are created and activated/inactivated.');const master=(type,labelName)=>card(labelName,`<p class="text-[11px] text-slate-500 mb-3">Existing values are not renamed or deleted. If a value becomes obsolete, deactivate it; historical records keep their original snapshot.</p>${CAN_MANAGE_MASTER?`<form class="masterForm flex gap-2 mb-3" data-type="${type}"><input class="masterInput ${inputCls}" required placeholder="Add ${labelName.slice(0,-1)}"><button class="bg-red-600 px-4 rounded-lg text-xs font-bold">Add</button></form>`:''}<div class="space-y-2">${settings.filter(x=>x.type===type).map(x=>`<div class="bg-slate-950 border border-slate-800 rounded-lg p-2 flex justify-between items-center"><div><span class="text-sm">${esc(x.value)}</span> <span class="text-[10px] ${x.status==='inactive'?'text-amber-400':'text-emerald-400'}">${x.status||'active'}</span></div>${CAN_MANAGE_MASTER?`<button onclick="toggleMaster('${x.id}','${type}')" class="bg-slate-700 px-2 py-1 rounded text-[10px]">${x.status==='inactive'?'Activate':'Deactivate'}</button>`:'<span class="text-[10px] text-slate-500">View only</span>'}</div>`).join('')||'<div class="text-xs text-slate-500">No records.</div>'}</div>`);byId('appContent').innerHTML=`<div class="grid lg:grid-cols-3 gap-5">${master('warehouse','Warehouses')}${master('unit','Units')}${master('category','Categories')}</div>${CAN_BACKUP?card('System Backup / Recovery',`<p class="text-xs text-slate-400 mb-3">Backup is machine-readable recovery data, not a report. Restore only upserts records; it does not delete extra records.</p><div class="flex flex-wrap gap-2"><button id="downloadBackup" class="bg-cyan-700 px-4 py-2 rounded-lg text-xs font-bold">Download Full Backup JSON</button></div><div class="text-[10px] text-slate-500 mt-2">Firestore user profiles are backed up; Firebase Authentication passwords/accounts are not recreated by this file.</div>`,'mt-5'):''}`;document.querySelectorAll('.masterForm').forEach(f=>f.onsubmit=createMaster);if(CAN_BACKUP){byId('downloadBackup').onclick=downloadBackup;}}
async function createMaster(e){e.preventDefault();if(!CAN_MANAGE_MASTER)return;const type=e.currentTarget.dataset.type,val=e.currentTarget.querySelector('.masterInput').value.trim().replace(/\s+/g,' ');if(!val)return;if(settings.some(x=>x.type===type&&norm(x.value)===norm(val))){alert('This value already exists. Activate the existing record if needed.');return;}const ref=await addDoc(collection(db,'settings'),{type,value:val,normalizedValue:norm(val),status:'active',createdAt:nowISO(),createdBy:me.email});await writeAudit('CREATE_MASTER','Global Settings',type,val,null,{value:val,status:'active'},'',ref.id);await loadAll();renderSettings();}
window.toggleMaster=async(id,type)=>{if(!CAN_MANAGE_MASTER)return;const x=settings.find(s=>s.id===id);if(!x)return;const status=x.status==='inactive'?'active':'inactive',reason=prompt(`Reason for ${status==='inactive'?'deactivating':'activating'} ${x.value} (required)`,'');if(!reason?.trim())return;await updateDoc(doc(db,'settings',id),{status,updatedAt:nowISO(),updatedBy:me.email});await writeAudit('CHANGE_MASTER_STATUS','Global Settings',type,x.value,{status:x.status||'active'},{status},reason.trim(),id);await loadAll();renderSettings();};
const backupCollections=['settings','client_profiles','supplier_profiles','inventory','movements','maintenance_events','client_docs','supplier_docs','document_refs','operational_logs','audit_traces','users'];
async function downloadBackup(){const payload={imsBackupVersion:2,createdAt:nowISO(),createdBy:me.email,collections:{}};for(const c of backupCollections){const snap=await getDocs(collection(db,c));payload.collections[c]=[];snap.forEach(d=>payload.collections[c].push({id:d.id,data:d.data()}));}downloadText(`IMS_Backup_${nowISO().slice(0,10)}.json`,JSON.stringify(payload,null,2));await writeAudit('CREATE_SYSTEM_BACKUP','Global Settings','backup','Full System Backup',null,{collections:Object.fromEntries(Object.entries(payload.collections).map(([k,v])=>[k,v.length]))});}
async function restoreBackup(e){if(!CAN_BACKUP)return;const file=e.target.files[0];if(!file)return;let data;try{data=JSON.parse(await file.text());}catch{alert('Invalid JSON backup.');return;}if(!data?.imsBackupVersion||!data.collections){alert('Not a valid IMS backup file.');return;}if(!confirm('Restore this backup by upserting all contained records? Existing records not in the backup will NOT be deleted.'))return;for(const [c,rows] of Object.entries(data.collections)){if(!Array.isArray(rows))continue;for(let i=0;i<rows.length;i+=400){const batch=writeBatch(db);rows.slice(i,i+400).forEach(r=>batch.set(doc(db,c,r.id),r.data));await batch.commit();}}await writeAudit('RESTORE_SYSTEM_BACKUP','Global Settings','backup','System Backup Restore',null,{backupCreatedAt:data.createdAt,collections:Object.fromEntries(Object.entries(data.collections).map(([k,v])=>[k,Array.isArray(v)?v.length:0]))});await loadAll();renderSettings();alert('Backup restore completed by upsert.');}

function renderAudit(){if(!CAN_AUDIT)return;setNav('audit','Audit / Trace','Who changed what, when, and the exact before/after values.');const roleOptions=ROLE==='superadmin'?['admin','manager','superadmin']:['admin','manager'];byId('appContent').innerHTML=`${card('Audit Filters',`<div class="grid sm:grid-cols-2 lg:grid-cols-5 gap-2">${label('Search',`<input id="auditSearch" class="${inputCls}" placeholder="User, item, action, remark...">`)}${label('Role',`<select id="auditRole" class="${inputCls}"><option value="">All Visible</option>${roleOptions.map(r=>`<option value="${r}">${r==='manager'&&ROLE==='manager'?'My Actions':' '+r[0].toUpperCase()+r.slice(1)}</option>`).join('')}</select>`)}${label('Module',`<select id="auditModule" class="${inputCls}"><option value="">All Modules</option>${[...new Set(audit.map(x=>x.module).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join('')}</select>`)}${label('From Date',`<input type="date" id="auditFrom" class="${inputCls}">`)}${label('To Date',`<input type="date" id="auditTo" class="${inputCls}">`)}</div><div class="flex gap-2 mt-3"><button id="auditExport" class="bg-violet-700 px-4 py-2 rounded-lg text-xs font-bold">Export Filtered Excel</button><button id="auditExportSelected" class="bg-cyan-700 px-4 py-2 rounded-lg text-xs font-bold">Export Selected Excel</button></div>`) }
 ${card('System Audit',`<div id="auditCount" class="text-xs text-slate-500 mb-2"></div><div class="overflow-auto max-h-[68vh] border border-slate-800 rounded-xl"><table class="w-full min-w-[1250px] text-xs"><thead class="sticky top-0 bg-slate-950 text-slate-400"><tr><th class="p-2"><input id="auditSelectAll" type="checkbox"></th>${[['performedAt','Date'],['performedBy','User'],['performedByRole','Role'],['module','Module'],['actionType','Action'],['targetName','Target'],['changedFields','Changed'],['remark','Remark']].map(([f,n])=>`<th class="p-2 text-left cursor-pointer auditSortHead" data-field="${f}">${n} ↕</th>`).join('')}<th class="p-2">Details</th></tr></thead><tbody id="auditBody"></tbody></table></div>`)}`;['auditSearch','auditRole','auditModule','auditFrom','auditTo'].forEach(id=>byId(id).onchange=applyAuditFilters);byId('auditSearch').onkeyup=applyAuditFilters;document.querySelectorAll('.auditSortHead').forEach(h=>h.onclick=()=>{auditSort={field:h.dataset.field,dir:auditSort.field===h.dataset.field&&auditSort.dir==='asc'?'desc':'asc'};applyAuditFilters();});byId('auditSelectAll').onchange=e=>document.querySelectorAll('.auditRowCheck').forEach(x=>x.checked=e.target.checked);byId('auditExport').onclick=()=>exportAudit(false);byId('auditExportSelected').onclick=()=>exportAudit(true);applyAuditFilters();}
function applyAuditFilters(){const q=norm(byId('auditSearch').value),role=byId('auditRole').value,module=byId('auditModule').value,from=byId('auditFrom').value,to=byId('auditTo').value;filteredAudit=audit.filter(x=>{const d=String(x.performedAt||'').slice(0,10);let roleOk=!role||x.performedByRole===role;if(ROLE==='manager'&&role==='manager')roleOk=x.performedBy===me.email;return(!q||norm(JSON.stringify(x)).includes(q))&&roleOk&&(!module||x.module===module)&&(!from||d>=from)&&(!to||d<=to);});filteredAudit.sort((a,b)=>{const av=Array.isArray(a[auditSort.field])?a[auditSort.field].join(', '):a[auditSort.field]??'',bv=Array.isArray(b[auditSort.field])?b[auditSort.field].join(', '):b[auditSort.field]??'',c=String(av).localeCompare(String(bv));return auditSort.dir==='asc'?c:-c;});byId('auditCount').textContent=`${filteredAudit.length} visible audit record(s).`;byId('auditBody').innerHTML=filteredAudit.map(x=>`<tr class="border-t border-slate-900"><td class="p-2"><input class="auditRowCheck" value="${x.id}" type="checkbox"></td><td class="p-2 whitespace-nowrap">${esc(displayDate(x.performedAt))}</td><td class="p-2">${esc(x.performedBy)}</td><td class="p-2">${esc(x.performedByRole)}</td><td class="p-2">${esc(x.module)}</td><td class="p-2">${esc(friendlyAction(x.actionType))}</td><td class="p-2">${esc(x.targetName)}</td><td class="p-2">${esc((x.changedFields||[]).join(', ')||'—')}</td><td class="p-2 max-w-[250px]">${esc(x.remark||'')}</td><td class="p-2"><button onclick="auditDetail('${x.id}')" class="bg-slate-700 px-2 py-1 rounded text-[10px]">View</button></td></tr>`).join('')||'<tr><td colspan="10" class="p-4 text-center text-slate-500">No audit records.</td></tr>';}
window.auditDetail=id=>{const x=audit.find(y=>y.id===id);if(!x)return;alert(`${x.summary||friendlyAction(x.actionType)}\n\nBefore:\n${JSON.stringify(x.beforeValue,null,2)}\n\nAfter:\n${JSON.stringify(x.afterValue,null,2)}\n\nRemark: ${x.remark||'—'}\nBy: ${x.performedBy} (${x.performedByRole})\nAt: ${x.performedAt}`);};
function exportAudit(selected){let rows=filteredAudit;if(selected){const ids=[...document.querySelectorAll('.auditRowCheck:checked')].map(x=>x.value);rows=rows.filter(x=>ids.includes(x.id));if(!rows.length){alert('Select audit rows first.');return;}}const out=rows.map(x=>({Date:x.performedAt,User:x.performedBy,Role:x.performedByRole,Module:x.module,Action:friendlyAction(x.actionType),Target:x.targetName,Changed:(x.changedFields||[]).join(', '),Before:JSON.stringify(x.beforeValue),After:JSON.stringify(x.afterValue),Remark:x.remark||''}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(out),'Audit');XLSX.writeFile(wb,`IMS_Audit_${selected?'Selected':'Filtered'}_${nowISO().slice(0,10)}.xlsx`);writeAudit('EXPORT_AUDIT','Audit','audit_export',selected?'Selected Audit Export':'Filtered Audit Export',null,{count:rows.length});}

function renderUsers(){if(!CAN_MANAGE_USERS)return;setNav('users','User Management','No user deletion. Accounts are activated/inactivated; role changes are traced.');byId('appContent').innerHTML=`<div class="grid lg:grid-cols-3 gap-5">${card('Create Account',`<form id="userForm" class="space-y-3">${label('Email',`<input type="email" id="userEmail" required class="${inputCls}">`)}${label('Temporary Password',`<input type="password" id="userPassword" minlength="8" required class="${inputCls}">`)}${label('Role',`<select id="userRole" class="${inputCls}">${(ROLE==='manager'?['admin']:['admin','manager','superadmin']).map(x=>`<option>${x}</option>`).join('')}</select>`)}<button class="w-full bg-red-600 py-2.5 rounded-lg text-sm font-bold">Create Account</button></form>`)}${card('Account Directory',`<div class="lg:col-span-2"><div class="overflow-x-auto"><table class="w-full min-w-[700px] text-xs"><thead class="text-slate-500"><tr><th class="p-2 text-left">Email</th><th class="p-2">Role</th><th class="p-2">Status</th><th class="p-2">Created</th><th class="p-2">Actions</th></tr></thead><tbody>${users.map(u=>`<tr class="border-t border-slate-800"><td class="p-2">${esc(u.email)}</td><td class="p-2 text-center">${esc(u.role)}</td><td class="p-2 text-center">${esc(u.status||'active')}</td><td class="p-2 text-center">${esc(u.createdAt?.slice(0,10)||'')}</td><td class="p-2 text-center">${(ROLE==='superadmin'||u.role==='admin')&&u.uid!==me.uid?`<button onclick="toggleUser('${u.id}')" class="bg-slate-700 px-2 py-1 rounded text-[10px]">${u.status==='inactive'?'Activate':'Deactivate'}</button>${ROLE==='superadmin'?` <button onclick="changeRole('${u.id}')" class="bg-violet-700 px-2 py-1 rounded text-[10px]">Role</button>`:''}`:'—'}</td></tr>`).join('')}</tbody></table></div></div>`)}</div>`;byId('userForm').onsubmit=createUserAccount;}
async function createUserAccount(e){e.preventDefault();const email=byId('userEmail').value.trim().toLowerCase(),password=byId('userPassword').value,role=byId('userRole').value;if(ROLE==='manager'&&role!=='admin')return;if(password.length<8){alert('Password must be at least 8 characters.');return;}let app;try{app=initializeApp(firebaseConfig,`ims-provision-${Date.now()}`);const a=getAuth(app),cred=await createUserWithEmailAndPassword(a,email,password);await setDoc(doc(db,'users',cred.user.uid),{uid:cred.user.uid,email,role,status:'active',createdAt:nowISO(),createdBy:me.email});await writeAudit('CREATE_USER','User Management','user',email,null,{role,status:'active'},'',cred.user.uid);await loadAll();renderUsers();alert('Account created.');}catch(err){alert('Create user failed: '+err.message);}finally{if(app)try{await deleteApp(app);}catch{}}}
window.toggleUser=async id=>{const u=users.find(x=>x.id===id);if(!u||u.uid===me.uid)return;if(ROLE==='manager'&&u.role!=='admin')return;const status=u.status==='inactive'?'active':'inactive',reason=prompt(`Reason for ${status==='inactive'?'deactivating':'activating'} ${u.email} (required)`,'');if(!reason?.trim())return;await updateDoc(doc(db,'users',id),{status});await writeAudit('CHANGE_USER_STATUS','User Management','user',u.email,{status:u.status||'active'},{status},reason.trim(),id);await loadAll();renderUsers();};
window.changeRole=async id=>{if(ROLE!=='superadmin')return;const u=users.find(x=>x.id===id);if(!u||u.uid===me.uid)return;const role=prompt('New role: admin, manager or superadmin',u.role);if(!['admin','manager','superadmin'].includes(role)||role===u.role)return;const reason=prompt('Reason for role change (required)','');if(!reason?.trim())return;await updateDoc(doc(db,'users',id),{role});await writeAudit('CHANGE_USER_ROLE','User Management','user',u.email,{role:u.role},{role},reason.trim(),id);await loadAll();renderUsers();};

async function loadCollection(name){const arr=[];const snap=await getDocs(collection(db,name));snap.forEach(d=>arr.push({id:d.id,...d.data()}));return arr;}
async function loadAuditVisible(){if(!CAN_AUDIT){audit=[];return;}if(ROLE==='superadmin'){audit=await loadCollection('audit_traces');}else{const [a,o]=await Promise.all([getDocs(query(collection(db,'audit_traces'),where('performedByRole','==','admin'))),getDocs(query(collection(db,'audit_traces'),where('performedBy','==',me.email)))]);const m=new Map();[a,o].forEach(s=>s.forEach(d=>m.set(d.id,{id:d.id,...d.data()})));audit=[...m.values()].filter(x=>x.performedByRole==='admin'||x.performedBy===me.email);}audit.sort((a,b)=>String(b.performedAt).localeCompare(String(a.performedAt)));}
function legacyOperationalLogs(){const out=[];inventory.forEach(i=>(i.lifecycleHistory||[]).forEach((h,n)=>out.push({id:`legacy-${i.id}-${n}`,legacy:true,date:h.timestamp,activity:h.action||'LEGACY',activityLabel:h.action||'Legacy Activity',status:h.status||i.status,fromName:h.from||'',toName:h.to||h.location||'',qty:h.qty??'',unit:h.unit||i.unit,itemId:i.id,itemCode:i.itemCode,itemName:i.name,category:i.category,supplierId:i.supplierId||'',supplierName:i.supplierName||'',clientId:'',clientName:'',performedBy:h.user||'',performedByRole:'',remark:h.note||'',documents:h.documentRefs||[]})));return out;}
async function loadAll(){[inventory,suppliers,clients,settings,movements,maintenance,documents,users]=await Promise.all(['inventory','supplier_profiles','client_profiles','settings','movements','maintenance_events','document_refs','users'].map(loadCollection));const newLogs=await loadCollection('operational_logs');logs=[...newLogs,...legacyOperationalLogs()].sort((a,b)=>String(b.date).localeCompare(String(a.date)));await loadAuditVisible();}

onAuthStateChanged(auth,async user=>{if(!user){location.href='index.html';return;}const snap=await getDoc(doc(db,'users',user.uid));if(!snap.exists()||snap.data().role!==ROLE||snap.data().status==='inactive'){await signOut(auth);location.href='index.html';return;}me={uid:user.uid,email:snap.data().email||user.email||'',role:snap.data().role};shell();byId('currentUser').textContent=me.email;try{await loadAll();showTab('workspace');}catch(err){console.error(err);byId('appContent').innerHTML=`<div class="bg-red-950/50 border border-red-900 rounded-xl p-4 text-sm">Failed to load IMS data: ${esc(err.message)}</div>`;}});
