import './rental-status-sync.js';
import './sortable-tables.js';
import { auth, db } from './firebase-config.js';
import { collection, doc, getDoc, getDocs, updateDoc } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';

const byId=id=>document.getElementById(id);
const cls='w-full bg-slate-950 border border-slate-700 rounded-lg px-3 py-2.5 text-sm';
let pending=null;
const now=()=>new Date().toISOString();
const money=n=>Number(n||0).toFixed(2);

function applicable(){return ['RECEIVE_SUPPLIER','DELIVER_CLIENT'].includes(byId('moveAction')?.value||'')}
function render(){const form=byId('moveForm');if(!form)return;let box=byId('imsMovementInvoice');if(!applicable()){box?.remove();return;}if(box)return;box=document.createElement('div');box.id='imsMovementInvoice';box.className='border-t border-slate-800 pt-3';box.innerHTML=`<div class="text-xs font-semibold text-emerald-400 mb-2">Invoice Details (optional)</div><div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-2"><label class="text-xs text-slate-400">Invoice Number<input id="mvInvoiceNumber" class="${cls} mt-1" placeholder="Invoice no."></label><label class="text-xs text-slate-400">Invoice Date<input id="mvInvoiceDate" type="date" class="${cls} mt-1" value="${now().slice(0,10)}"></label><label class="text-xs text-slate-400">Item Invoice Amount<input id="mvInvoiceAmount" type="number" min="0" step="0.01" class="${cls} mt-1" placeholder="0.00"></label><label class="text-xs text-slate-400">Accounting Invoice Total<input id="mvInvoiceTotal" type="number" min="0" step="0.01" class="${cls} mt-1" placeholder="0.00"></label></div><div class="grid sm:grid-cols-2 gap-2 mt-2"><label class="text-xs text-slate-400">Item Description<input id="mvInvoiceDescription" maxlength="160" class="${cls} mt-1" placeholder="Short description"></label><label class="text-xs text-slate-400">Invoice Side<select id="mvInvoiceSide" class="${cls} mt-1"><option value="client">Client</option><option value="supplier">Supplier</option></select></label></div><div id="imsRentalPeriod" class="mt-2"></div><div class="text-[10px] text-slate-500 mt-1">For several item/source lines under one invoice, use the same invoice number and accounting total. The Invoice tab groups them automatically.</div>`;const remark=byId('moveRemark')?.closest('label');(remark||form.lastElementChild)?.before(box);syncSide();renderRental();}
function syncSide(){const s=byId('mvInvoiceSide');if(s)s.value=byId('moveAction')?.value==='RECEIVE_SUPPLIER'?'supplier':'client'}
function renderRental(){const mount=byId('imsRentalPeriod');if(!mount)return;const rental=byId('moveAction')?.value==='DELIVER_CLIENT'&&byId('clientPositionStatus')?.value==='Rental';mount.innerHTML=rental?`<div class="grid sm:grid-cols-2 gap-2"><label class="text-xs text-slate-400">Rental From<input id="mvPeriodFrom" type="date" class="${cls} mt-1" required></label><label class="text-xs text-slate-400">Rental To<input id="mvPeriodTo" type="date" class="${cls} mt-1" required></label></div>`:'';}
async function profile(){const u=auth.currentUser;if(!u)return null;const s=await getDoc(doc(db,'users',u.uid));return s.exists()?s.data():null}
function capture(e){if(e.target?.id!=='moveForm'||!applicable())return;const invoiceNumber=byId('mvInvoiceNumber')?.value.trim()||'';if(!invoiceNumber){pending=null;return;}const amount=Number(byId('mvInvoiceAmount')?.value||0),total=Number(byId('mvInvoiceTotal')?.value||0),periodFrom=byId('mvPeriodFrom')?.value||'',periodTo=byId('mvPeriodTo')?.value||'';if(amount<0||total<0){e.preventDefault();e.stopImmediatePropagation();alert('Invoice amounts cannot be negative.');return;}if(total>0&&amount>total){e.preventDefault();e.stopImmediatePropagation();alert('Item Invoice Amount cannot exceed Accounting Invoice Total.');return;}if(periodFrom&&periodTo&&periodTo<periodFrom){e.preventDefault();e.stopImmediatePropagation();alert('Rental To cannot be before Rental From.');return;}const itemId=byId('moveItem')?.value||'',action=byId('moveAction')?.value||'',dest=byId('moveDestination'),partyId=dest?.value||'',partyName=dest?.selectedOptions?.[0]?.dataset?.name||dest?.selectedOptions?.[0]?.textContent?.trim()||dest?.value||'';pending={capturedAt:Date.now(),itemId,action,invoiceNumber,invoiceDate:byId('mvInvoiceDate')?.value||now().slice(0,10),invoiceAmount:amount,invoiceTotal:total,invoiceDescription:byId('mvInvoiceDescription')?.value.trim()||'',invoiceSide:byId('mvInvoiceSide')?.value||'',invoicePartyId:partyId,invoicePartyName:partyName,periodFrom,periodTo,currency:'MYR'};setTimeout(persist,700);setTimeout(persist,1800)}
async function persist(){if(!pending)return;try{const p=await profile();if(!p)return;const snap=await getDocs(collection(db,'movements'));const candidates=snap.docs.map(d=>({id:d.id,...d.data()})).filter(m=>m.itemId===pending.itemId&&m.action===pending.action&&m.createdBy===(p.email||auth.currentUser?.email||'')&&m.status==='in_transit'&&!m.invoiceNumber).sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')));const m=candidates[0];if(!m)return;if(Date.now()-new Date(m.createdAt||0).getTime()>60000)return;const key=`${pending.invoiceSide}|${pending.invoicePartyId}|${pending.invoiceNumber}`.toLowerCase();await updateDoc(doc(db,'movements',m.id),{invoiceGroupKey:key,invoiceNumber:pending.invoiceNumber,invoiceDate:pending.invoiceDate,invoiceAmount:pending.invoiceAmount,invoiceTotal:pending.invoiceTotal,invoiceDescription:pending.invoiceDescription,invoiceSide:pending.invoiceSide,invoicePartyId:pending.invoicePartyId,invoicePartyName:pending.invoicePartyName,currency:'MYR',periodFrom:pending.periodFrom,periodTo:pending.periodTo,clientTransactionType:pending.periodFrom||pending.periodTo?'Rental':(m.toStatus||''),invoiceStatus:'Active'});pending=null;}catch(err){console.warn('IMS invoice metadata attachment failed:',err)}}
document.addEventListener('submit',capture,true);document.addEventListener('change',e=>{if(['moveAction','clientPositionStatus'].includes(e.target?.id)){setTimeout(()=>{render();syncSide();renderRental()},0)}},true);let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(render,20)}).observe(document.body,{childList:true,subtree:true});render();
