import {auth,db} from '../../firebase-config.js';
import {addDoc,collection,doc,getDoc,getDocs,runTransaction} from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';
import {can} from '../../ims-permissions.js';

const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').trim().replace(/\s+/g,' ').toLowerCase();
const now=()=>new Date().toISOString();
const cls='w-full min-w-0 bg-slate-950 border border-slate-700 rounded-lg px-3 py-2.5 text-sm';
const VALID=new Set(['At Supplier','Available','Reserved','At Client','Maintenance','Inspection','Not Available','In Transit','Missing','Stolen']);
const ACTIONS={
 RECEIVE_SUPPLIER:{label:'Receive from Supplier',from:'supplier',to:'warehouse',toStatus:'Available',refType:'wellora_po',legacyType:'wellora',refLabel:'Wellora PO'},
 TRANSFER_WAREHOUSE:{label:'Transfer Warehouse / Location',from:'warehouse',to:'warehouse',toStatus:'Available',refType:'internal_transfer',legacyType:'internal_transfer',refLabel:'Internal Transfer No.'},
 DELIVER_CLIENT:{label:'Rental / Send to Client',from:'warehouse',to:'client',toStatus:'At Client',refType:'client_po',legacyType:'client',refLabel:'Client PO'},
 RETURN_CLIENT:{label:'Return from Client',from:'client',to:'warehouse',toStatus:'Available',refType:'receiving_no',legacyType:'receiving',refLabel:'Receiving No.'}
};
let inventory=[],settings=[],businesses=[],movements=[],groups=[],saving=false;

const roles=x=>Array.isArray(x.businessRoles)?x.businessRoles:[];
const isRole=(x,r)=>roles(x).length?roles(x).includes(r):x.sourceKind===r;
const partyName=x=>x?.companyName||x?.supplierName||x?.clientName||'';
const action=()=>ACTIONS[$('bmAction')?.value||'DELIVER_CLIENT'];
function balances(i){return(Array.isArray(i.stockBalances)?i.stockBalances:[]).filter(x=>Number(x.qty||0)>0).map(x=>({...x,qty:Number(x.qty||0),locationName:x.locationName||'Unknown',status:VALID.has(x.status)?x.status:'Not Available'}));}
function summary(b){const p=b.filter(x=>x.qty>0),priority=['In Transit','Maintenance','Inspection','At Client','Reserved','Missing','Stolen','Not Available','At Supplier','Available'];return!p.length?{status:'Not Available',location:'No Stock'}:{status:priority.find(s=>p.some(x=>x.status===s))||'Not Available',location:p.length===1?p[0].locationName:`${p.length} Locations`};}
function warehouses(){return settings.filter(x=>x.type==='warehouse'&&x.status!=='inactive').map(x=>({id:x.id,name:x.value})).filter(x=>x.name).sort((a,b)=>a.name.localeCompare(b.name));}
function suppliers(){return businesses.filter(x=>isRole(x,'supplier')).sort((a,b)=>partyName(a).localeCompare(partyName(b)));}
function clients(){return businesses.filter(x=>isRole(x,'client')).sort((a,b)=>partyName(a).localeCompare(partyName(b)));}
function itemType(item){return settings.find(x=>x.type==='item_type'&&x.id===item?.itemTypeId)||settings.find(x=>x.type==='item_type'&&norm(x.value)===norm(item?.type));}
function singleItem(item){return itemType(item)?.quantityMode==='single';}
async function load(){
 const[a,b,c,d,e]=await Promise.all(['inventory','settings','client_profiles','supplier_profiles','movements'].map(n=>getDocs(collection(db,n))));
 inventory=a.docs.map(x=>({id:x.id,...x.data()}));settings=b.docs.map(x=>({id:x.id,...x.data()}));
 businesses=[...c.docs.map(x=>({id:x.id,sourceKind:'client',...x.data()})),...d.docs.map(x=>({id:x.id,sourceKind:'supplier',...x.data()}))].filter(x=>x.status!=='inactive');
 movements=e.docs.map(x=>({id:x.id,...x.data()}));
 try{const g=await getDocs(collection(db,'movement_groups'));groups=g.docs.map(x=>({id:x.id,...x.data()})).filter(x=>x.status!=='closed');}catch(err){groups=[];console.warn('Movement groups unavailable; new group creation still attempted on save.',err);}
}
function reservationRecords(){const map=new Map();for(const item of inventory.filter(i=>i.activeReservation&&i.activeReservation.status!=='Cancelled')){const r=item.activeReservation,id=r.reservationId||item.id;if(!map.has(id))map.set(id,{id,reservation:r,lines:[]});map.get(id).lines.push({item,reservation:r,qty:Number(r.lineQty||r.qty||1)});}return[...map.values()].map(g=>({...g,total:g.lines.reduce((n,l)=>n+l.qty,0)}));}
function selectedReservation(){const id=$('bmReservation')?.value||'';return reservationRecords().find(x=>x.id===id)||null;}
function reservedIds(){return new Set((selectedReservation()?.lines||[]).map(x=>x.item.id));}
function source(){const e=$('bmSource'),o=e?.selectedOptions?.[0];return e?.value?{id:e.value,name:o?.dataset?.name||o?.textContent?.trim()||''}:null;}
function destination(){const e=$('bmDestination'),o=e?.selectedOptions?.[0];return e?.value?{id:e.value,name:o?.dataset?.name||o?.textContent?.trim()||''}:null;}
function sameLocation(b,l){return b&&l&&((b.locationId&&String(b.locationId)===String(l.id))||norm(b.locationName)===norm(l.name));}
function sourceList(){const a=action();if(a.from==='warehouse')return warehouses();if(a.from==='supplier')return suppliers().map(x=>({id:x.id,name:partyName(x)}));return clients().map(x=>({id:x.id,name:partyName(x)}));}
function destinationList(){const a=action(),s=source();if(a.to==='warehouse')return warehouses().filter(x=>!s||String(x.id)!==String(s.id));return clients().map(x=>({id:x.id,name:partyName(x)}));}
function options(list,label){return`<option value="">-- ${esc(label)} --</option>${list.map(x=>`<option value="${esc(x.id)}" data-name="${esc(x.name)}">${esc(x.name)}</option>`).join('')}`;}
function eligibleBalance(item){const a=action(),s=source();if(!s)return null;return balances(item).find(b=>{if(!sameLocation(b,s))return false;if(a.from==='supplier')return b.locationType==='supplier'&&b.status==='At Supplier';if(a.from==='client')return b.locationType==='client'&&b.status==='At Client';if(a.from==='warehouse'){if(b.locationType!=='warehouse')return false;if(b.status==='Available')return true;return a.to==='client'&&reservedIds().has(item.id)&&b.status==='Reserved';}return false;})||null;}
function selectedIds(){return new Set([...document.querySelectorAll('.bmLine')].map(x=>x.dataset.itemId).filter(Boolean));}
function availableItems(){const used=selectedIds();return inventory.filter(i=>!used.has(i.id)&&eligibleBalance(i)).sort((a,b)=>String(a.alias||a.itemCode||'').localeCompare(String(b.alias||b.itemCode||''),undefined,{numeric:true,sensitivity:'base'}));}
function refreshPicker(){const e=$('bmItemPicker');if(!e)return;const cur=e.value;e.innerHTML='<option value="">-- Available Item --</option>'+availableItems().map(i=>{const b=eligibleBalance(i);return`<option value="${i.id}">${esc(i.alias||'No Wellora SN')} — ${esc(i.name||'')} — ${b.qty} ${esc(i.unit||'')}</option>`;}).join('');if([...e.options].some(o=>o.value===cur))e.value=cur;}
function lineHtml(item){const b=eligibleBalance(item),locked=singleItem(item),max=locked?1:b.qty;return`<div class="bmLine border border-slate-800 rounded-xl p-3" data-item-id="${item.id}"><div class="grid sm:grid-cols-[1.05fr_1.8fr_.65fr_.65fr_auto] gap-2 items-end"><div><div class="text-[11px] text-slate-500">Wellora SN</div><div class="font-semibold text-cyan-300">${esc(item.alias||'—')}</div></div><div><div class="text-[11px] text-slate-500">Description / IMS Item ID</div><div class="text-sm">${esc(item.name||'')}</div><div class="font-mono text-[11px] text-slate-500">${esc(item.itemCode||'')}</div></div><div><div class="text-[11px] text-slate-500">Available</div><div class="text-sm">${b.qty} ${esc(item.unit||'')}</div></div><label class="text-xs text-slate-400">Qty<input class="bmQty ${cls} mt-1" type="number" min="1" max="${max}" step="1" value="1" ${locked?'readonly':''}></label><button type="button" class="bmRemove bg-slate-800 px-3 py-2.5 rounded-lg text-xs">Remove</button></div>${locked?'<div class="text-[10px] text-slate-600 mt-1">Single-unit item type — quantity locked at 1.</div>':''}</div>`;}
function addItem(){const id=$('bmItemPicker')?.value,item=inventory.find(x=>x.id===id);if(!item||!eligibleBalance(item))return;const w=$('bmLines');w.insertAdjacentHTML('beforeend',lineHtml(item));const row=w.lastElementChild;row.querySelector('.bmRemove').onclick=()=>{row.remove();refreshPicker();};$('bmItemPicker').value='';refreshPicker();}
function clearItems(){if($('bmLines'))$('bmLines').innerHTML='';refreshPicker();}
function field(l,b,extra=''){return`<label class="block min-w-0 text-xs text-slate-400 ${extra}">${l}${b}</label>`;}
function groupType(g){return g.referenceType||g.poType||'';}
function groupNumber(g){return g.referenceNumber||g.internalTransferNumber||g.receivingNumber||g.poNumber||'';}
function groupMatches(g,a){const t=groupType(g);return t===a.refType||t===a.legacyType;}
function groupCandidates(){const a=action();return groups.filter(g=>groupMatches(g,a)).sort((x,y)=>String(y.updatedAt||y.createdAt||'').localeCompare(String(x.updatedAt||x.createdAt||'')));}
function groupLabel(g){const n=groupNumber(g)||'No Reference',party=g.partyName||((g.fromName&&g.toName)?`${g.fromName} → ${g.toName}`:'');return`${n}${party?' · '+party:''} · ${g.batchCount||0} batch(es)`;}
function referenceMeta(){const a=action();if(a.refType==='internal_transfer')return{title:'Internal Transfer Group',group:'Transfer Group',note:'One Internal Transfer No. can contain multiple warehouse-transfer batches.'};if(a.refType==='receiving_no')return{title:'Receiving Group',group:'Receiving Group',note:'One Receiving No. can contain multiple client-return batches.'};return{title:'PO Movement Group',group:'PO Group',note:'One PO can contain multiple movement batches.'};}
function referenceHtml(){const a=action(),m=referenceMeta(),list=groupCandidates();return`<section class="border border-cyan-900/50 rounded-xl p-3 space-y-3"><div class="font-semibold text-sm text-cyan-300">${m.title}</div><div class="grid sm:grid-cols-[220px_320px] gap-2 items-end">${field(m.group,`<select id="bmGroupMode" class="${cls} mt-1"><option value="new">New ${a.refLabel}</option><option value="existing">Existing ${a.refLabel}</option></select>`)}<label id="bmExistingWrap" class="hidden block min-w-0 text-xs text-slate-400">Existing ${a.refLabel}<select id="bmExistingGroup" class="${cls} mt-1"><option value="">-- Select Existing --</option>${list.map(g=>`<option value="${g.id}">${esc(groupLabel(g))}</option>`).join('')}</select></label></div><div id="bmNewRefWrap" class="max-w-xs">${field(a.refLabel,`<input id="bmReference" class="${cls} mt-1" placeholder="${a.refLabel}">`)}</div><div id="bmGroupInfo" class="text-[11px] text-slate-500">${m.note}</div></section>`;}
function reservationHtml(){if(action().to!=='client')return'';const rs=reservationRecords();return`<section class="border border-slate-800 rounded-xl p-3"><div class="font-semibold text-sm mb-2">Reservation (Optional)</div>${field('Reservation',`<select id="bmReservation" class="${cls} mt-1"><option value="">No Reservation</option>${rs.map(r=>`<option value="${r.id}">${esc(r.reservation.clientName||'')} · ${esc(r.reservation.reference||'PO pending')} · ${r.total} reserved</option>`).join('')}`,'max-w-xl')}<div id="bmReservationInfo" class="text-[11px] text-slate-500 mt-2">Reserved items, substitutes, fewer units or extra Available units may be moved.</div></section>`;}
function logisticsHtml(){return`<section class="border border-slate-800 rounded-xl p-3"><div class="font-semibold text-sm mb-3">Logistics</div><div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-2">${field('Logistics Provider',`<select id="bmLogisticsProvider" class="${cls} mt-1"><option value="">Optional / Internal</option>${suppliers().map(x=>`<option value="${x.id}" data-name="${esc(partyName(x))}">${esc(partyName(x))}</option>`).join('')}</select>`)}${field('Contact Person',`<input id="bmContactPerson" class="${cls} mt-1">`)}${field('Contact Number',`<input id="bmContactNumber" class="${cls} mt-1">`)}${field('Transport / Vessel No.',`<input id="bmTransportNo" class="${cls} mt-1">`)}${field('Logistics / Delivery Reference',`<input id="bmLogisticsRef" class="${cls} mt-1">`)}${field('ETA / Movement Date',`<input id="bmMovementDate" type="date" class="${cls} mt-1">`)}${field('Delivery Ticket / DO',`<input id="bmDeliveryTicket" class="${cls} mt-1">`)}${field('Receiving Ticket',`<input id="bmReceivingTicket" class="${cls} mt-1">`)}</div></section>`;}
function commercialHtml(){if(action().to!=='client')return'';return`<section class="border border-emerald-900/50 rounded-xl p-3"><div class="font-semibold text-sm text-emerald-400 mb-3">Client Commercial / Rental</div><div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-2">${field('PO Total Amount',`<input id="bmPOAmount" type="number" min="0" step="0.01" class="${cls} mt-1">`)}${field('Currency',`<input id="bmCurrency" value="MYR" class="${cls} mt-1">`)}${field('Use From',`<input id="bmPeriodFrom" type="date" class="${cls} mt-1">`)}${field('Due / Use To',`<input id="bmPeriodTo" type="date" class="${cls} mt-1">`)}</div></section>`;}
function formHtml(defaultAction='DELIVER_CLIENT'){const a=ACTIONS[defaultAction];return`<form id="batchMoveForm" data-ims-movement-module="4" class="space-y-4"><section class="border border-slate-800 rounded-xl p-3"><div class="font-semibold text-sm mb-3">Movement</div><div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-2">${field('Movement Type',`<select id="bmAction" class="${cls} mt-1">${Object.entries(ACTIONS).map(([k,v])=>`<option value="${k}" ${k===defaultAction?'selected':''}>${v.label}</option>`).join('')}</select>`)}${field(a.from==='warehouse'?'Source Warehouse':a.from==='supplier'?'Source Supplier':'Source Client',`<select id="bmSource" class="${cls} mt-1"></select>`)}${field(a.to==='warehouse'?'Destination Warehouse':'Destination Client',`<select id="bmDestination" class="${cls} mt-1"></select>`)}</div></section><div id="bmReferenceWrap"></div><div id="bmCommercialWrap"></div><div id="bmReservationWrap"></div><section class="border border-slate-800 rounded-xl p-3 space-y-3"><div><div class="font-semibold text-sm">Available Items</div><div class="text-[11px] text-slate-500">Filtered by the selected source and stock status.</div></div><div class="grid sm:grid-cols-[minmax(0,1fr)_auto] gap-2 items-end">${field('Available Item',`<select id="bmItemPicker" class="${cls} mt-1"><option value="">-- Select source first --</option></select>`)}<button id="bmAddItem" type="button" class="bg-slate-700 px-4 py-2.5 rounded-lg text-sm">+ Add Item</button></div><div id="bmLines" class="space-y-2"></div></section>${logisticsHtml()}${field('Remark',`<textarea id="bmRemark" rows="2" class="${cls} mt-1"></textarea>`)}<button id="bmSave" class="w-full bg-red-600 py-3 rounded-lg text-sm font-bold">Start Movement</button></form>`;}
function syncTop(){const a=action(),s=$('bmSource'),d=$('bmDestination');if(!s||!d)return;s.innerHTML=options(sourceList(),'Source');d.innerHTML=options(destinationList(),'Destination');const sl=s.closest('label'),dl=d.closest('label');if(sl)sl.childNodes[0].textContent=a.from==='warehouse'?'Source Warehouse':a.from==='supplier'?'Source Supplier':'Source Client';if(dl)dl.childNodes[0].textContent=a.to==='warehouse'?'Destination Warehouse':'Destination Client';refreshPicker();}
function bindReference(){const mode=$('bmGroupMode'),existing=$('bmExistingGroup');if(!mode)return;const apply=()=>{const ex=mode.value==='existing';$('bmExistingWrap')?.classList.toggle('hidden',!ex);$('bmNewRefWrap')?.classList.toggle('hidden',ex);if(ex)applyExistingGroup();};mode.onchange=apply;if(existing)existing.onchange=applyExistingGroup;apply();}
function applyExistingGroup(){const g=groups.find(x=>x.id===$('bmExistingGroup')?.value);if(!g)return;const a=action(),s=$('bmSource'),d=$('bmDestination');if($('bmReference'))$('bmReference').value=groupNumber(g);if(a.refType==='internal_transfer'){if(g.fromId&&[...s.options].some(o=>o.value===g.fromId))s.value=g.fromId;if(g.toId){d.innerHTML=options(destinationList(),'Destination');if([...d.options].some(o=>o.value===g.toId))d.value=g.toId;}}else if(g.partyId){if(a.from==='supplier'||a.from==='client'){if([...s.options].some(o=>o.value===g.partyId))s.value=g.partyId;d.innerHTML=options(destinationList(),'Destination');}else if(a.to==='client'&&[...d.options].some(o=>o.value===g.partyId))d.value=g.partyId;}if($('bmGroupInfo'))$('bmGroupInfo').textContent=`Existing ${a.refLabel} ${groupNumber(g)} · ${g.batchCount||0} prior batch(es).`;clearItems();}
function renderDynamic(){$('bmReferenceWrap').innerHTML=referenceHtml();$('bmCommercialWrap').innerHTML=commercialHtml();$('bmReservationWrap').innerHTML=reservationHtml();bindReference();if($('bmReservation'))$('bmReservation').onchange=applyReservation;}
function applyReservation(){const rr=selectedReservation(),d=$('bmDestination'),info=$('bmReservationInfo');if(!rr){if(info)info.textContent='Reserved items, substitutes, fewer units or extra Available units may be moved.';clearItems();return;}const r=rr.reservation;if(r.clientId&&[...d.options].some(o=>o.value===r.clientId))d.value=r.clientId;if($('bmReference')&&r.reference&&$('bmGroupMode')?.value==='new')$('bmReference').value=r.reference;if(info)info.textContent=`Reserved ${rr.total} across ${rr.lines.length} item line(s) for ${r.clientName||'client'}.`;clearItems();}
function changeAction(){const current=$('bmAction').value,form=$('batchMoveForm'),remark=$('bmRemark')?.value||'';form.outerHTML=formHtml(current);$('bmRemark').value=remark;bindForm();syncTop();renderDynamic();}
function bindForm(){$('bmAction').onchange=changeAction;$('bmSource').onchange=()=>{$('bmDestination').innerHTML=options(destinationList(),'Destination');clearItems();};$('bmDestination').onchange=clearItems;$('bmAddItem').onclick=addItem;$('batchMoveForm').onsubmit=save;}
function collect(){return[...document.querySelectorAll('.bmLine')].map(r=>{const item=inventory.find(x=>x.id===r.dataset.itemId),b=item?eligibleBalance(item):null,qty=Number(r.querySelector('.bmQty')?.value||0);return{item,b,qty};}).filter(x=>x.item&&x.b);}
async function resolveGroup(){const a=action(),mode=$('bmGroupMode')?.value||'new',s=source(),d=destination();if(mode==='existing'){const g=groups.find(x=>x.id===$('bmExistingGroup')?.value);if(!g)throw new Error(`Select an existing ${a.refLabel}.`);return{...g,ref:doc(db,'movement_groups',g.id),existing:true,reference:groupNumber(g)};}const reference=$('bmReference')?.value.trim()||'';if(!reference)throw new Error(`${a.refLabel} is required.`);const party=a.from==='supplier'||a.from==='client'?s:a.to==='client'?d:null;const dup=groups.find(g=>groupMatches(g,a)&&norm(groupNumber(g))===norm(reference)&&(a.refType==='internal_transfer'||norm(g.partyId)===norm(party?.id||'')));if(dup)throw new Error(`${a.refLabel} already exists. Select Existing ${a.refLabel}.`);const ref=doc(collection(db,'movement_groups'));return{id:ref.id,ref,existing:false,reference,partyId:party?.id||'',partyName:party?.name||'',batchCount:0,status:'open'};}
async function save(e){e.preventDefault();if(saving||!can('movement.add'))return;try{const a=action(),s=source(),d=destination(),lines=collect(),g=await resolveGroup(),rr=a.to==='client'?selectedReservation():null;if(!s||!d||!lines.length)throw new Error('Complete source, destination and add at least one item.');if(a.from===a.to&&String(s.id)===String(d.id))throw new Error('Source and destination must be different.');if(rr&&String(rr.reservation.clientId||'')!==String(d.id))throw new Error('Selected Reservation belongs to a different Client.');for(const l of lines){const max=singleItem(l.item)?1:l.b.qty;if(!Number.isInteger(l.qty)||l.qty<1||l.qty>max)throw new Error(`${l.item.alias||l.item.itemCode}: invalid quantity.`);}const poAmount=$('bmPOAmount')?.value===''||!$('bmPOAmount')?null:Number($('bmPOAmount').value),currency=$('bmCurrency')?.value||'',periodFrom=$('bmPeriodFrom')?.value||'',periodTo=$('bmPeriodTo')?.value||'';if(poAmount!==null&&(!Number.isFinite(poAmount)||poAmount<0))throw new Error('PO Total Amount must be valid.');if((periodFrom&&!periodTo)||(!periodFrom&&periodTo)||(periodTo&&periodTo<periodFrom))throw new Error('Check rental dates.');const lp=$('bmLogisticsProvider'),logisticsProviderId=lp?.value||'',logisticsProviderName=lp?.selectedOptions?.[0]?.dataset?.name||'',contactPerson=$('bmContactPerson')?.value.trim()||'',contactNumber=$('bmContactNumber')?.value.trim()||'',transportNo=$('bmTransportNo')?.value.trim()||'',logisticsReference=$('bmLogisticsRef')?.value.trim()||'',movementDate=$('bmMovementDate')?.value||'',deliveryTicket=$('bmDeliveryTicket')?.value.trim()||'',receivingTicket=$('bmReceivingTicket')?.value.trim()||'',remark=$('bmRemark')?.value.trim()||'';saving=true;const btn=$('bmSave');btn.disabled=true;btn.textContent='Saving...';const u=auth.currentUser,p=await getDoc(doc(db,'users',u.uid));if(!p.exists()||p.data().status!=='active')throw new Error('Active user required.');const user=p.data(),email=user.email||u.email||'',batchId=doc(collection(db,'movements')).id,at=now(),movementRefs=lines.map(()=>doc(collection(db,'movements'))),actualByItem=new Map();for(const l of lines)actualByItem.set(l.item.id,(actualByItem.get(l.item.id)||0)+l.qty);let reservationAudit=null;
 await runTransaction(db,async tx=>{const ids=new Set(lines.map(l=>l.item.id));if(rr)for(const x of rr.lines)ids.add(x.item.id);const state=new Map();for(const id of ids){const r=doc(db,'inventory',id),snap=await tx.get(r);if(!snap.exists())throw new Error('Item missing.');state.set(id,{ref:r,data:snap.data(),balances:balances(snap.data())});}
 let reservedTotal=0;if(rr){for(const x of rr.lines){const st=state.get(x.item.id),active=st.data.activeReservation;if(!active||String(active.reservationId||'')!==String(rr.id))throw new Error(`${x.item.alias||x.item.itemCode}: reservation changed.`);const lineReserved=Number(active.lineQty||x.qty||0);let released=0;for(const b of st.balances.filter(b=>b.status==='Reserved'&&(!b.reservationId||String(b.reservationId)===String(rr.id)))){const q=b.qty;b.qty=0;let dst=st.balances.find(v=>v!==b&&v.status==='Available'&&v.locationType===b.locationType&&v.locationId===b.locationId&&v.locationName===b.locationName);dst?dst.qty+=q:st.balances.push({qty:q,locationType:b.locationType,locationId:b.locationId||'',locationName:b.locationName,status:'Available'});released+=q;}if(released<lineReserved)throw new Error(`${x.item.alias||x.item.itemCode}: reserved stock changed.`);reservedTotal+=lineReserved;}}
 for(let n=0;n<lines.length;n++){const l=lines[n],st=state.get(l.item.id),target={locationType:a.from,locationId:s.id,locationName:s.name};let remaining=l.qty;for(const b of st.balances.filter(b=>b.status==='Available'&&b.locationType===target.locationType&&((target.locationId&&String(b.locationId)===String(target.locationId))||norm(b.locationName)===norm(target.locationName)))){const take=Math.min(b.qty,remaining);b.qty-=take;remaining-=take;if(!remaining)break;}if(remaining>0)throw new Error(`${l.item.alias||l.item.itemCode}: insufficient source stock.`);const mr=movementRefs[n];st.balances.push({qty:l.qty,locationType:'transit',locationId:mr.id,locationName:`Transit to ${d.name}`,status:'In Transit'});tx.set(mr,{movementId:mr.id,movementBatchId:batchId,movementGroupId:g.id,referenceType:a.refType,referenceLabel:a.refLabel,referenceNumber:g.reference,poType:a.legacyType,poLabel:a.refLabel,poNumber:a.refType==='wellora_po'||a.refType==='client_po'?g.reference:'',internalTransferNumber:a.refType==='internal_transfer'?g.reference:'',receivingNumber:a.refType==='receiving_no'?g.reference:'',clientPONumber:a.refType==='client_po'?g.reference:'',welloraPONumber:a.refType==='wellora_po'?g.reference:'',itemId:l.item.id,itemCode:l.item.itemCode,itemAlias:l.item.alias||'',itemNameSnapshot:l.item.name,action:$('bmAction').value,actionLabel:a.label,fromType:a.from,fromId:s.id,fromName:s.name,toType:a.to,toId:d.id,toName:d.name,toStatus:a.toStatus,qty:l.qty,unit:l.item.unit||'',remark,status:'in_transit',createdAt:at,createdBy:email,createdByRole:user.role||window.IMS_ROLE||'',clientPOAmount:a.refType==='client_po'?poAmount:null,currency:a.refType==='client_po'?currency:'',reservationId:rr?.id||'',periodFrom,periodTo,logisticsProviderId,logisticsProviderName,contactPerson,contactNumber,transportNo,logisticsReference,movementDate,deliveryTicket,receivingTicket});}
 for(const[id,st]of state){const clean=st.balances.filter(b=>b.qty>0),sum=summary(clean),patch={stockBalances:clean,status:sum.status,currentLocation:sum.location,lastEditedBy:email,lastEditedAt:at};if(rr&&rr.lines.some(x=>x.item.id===id)){const active=st.data.activeReservation,lineReserved=Number(active?.lineQty||0),actual=actualByItem.get(id)||0;patch.activeReservation=null;patch.lastReservation={...active,status:'Fulfilled',fulfilledAt:at,fulfilledBy:email,actualMovedQty:actual,reservedUsed:Math.min(lineReserved,actual),releasedBack:Math.max(0,lineReserved-actual),extraAvailableUsed:Math.max(0,actual-lineReserved),movementBatchId:batchId};}tx.update(st.ref,patch);}const groupPatch={movementGroupId:g.id,referenceType:a.refType,referenceLabel:a.refLabel,referenceNumber:g.reference,poType:a.legacyType,poLabel:a.refLabel,poNumber:a.refType==='wellora_po'||a.refType==='client_po'?g.reference:'',internalTransferNumber:a.refType==='internal_transfer'?g.reference:'',receivingNumber:a.refType==='receiving_no'?g.reference:'',partyId:g.partyId||'',partyName:g.partyName||'',status:'open',batchCount:g.existing?Number(g.batchCount||0)+1:1,updatedAt:at,lastBatchId:batchId,fromId:s.id,fromName:s.name,toId:d.id,toName:d.name};if(!g.existing){groupPatch.createdAt=at;groupPatch.createdBy=email;}tx.set(g.ref,groupPatch,{merge:true});if(rr){reservationAudit={reservationId:rr.id,reservedQty:reservedTotal,actualQty:[...actualByItem.values()].reduce((n,q)=>n+q,0),releasedBack:Math.max(0,reservedTotal-[...actualByItem.values()].reduce((n,q)=>n+q,0)),extraAvailableUsed:Math.max(0,[...actualByItem.values()].reduce((n,q)=>n+q,0)-reservedTotal)};tx.set(doc(db,'reservation_events',rr.id),{status:'Fulfilled',fulfilledAt:at,fulfilledBy:email,movementBatchId:batchId,movementGroupId:g.id,actualMovedQty:reservationAudit.actualQty,reservedUsed:Math.min(reservedTotal,reservationAudit.actualQty),releasedBack:reservationAudit.releasedBack,extraAvailableUsed:reservationAudit.extraAvailableUsed},{merge:true});}});
 for(let n=0;n<lines.length;n++){const l=lines[n],mr=movementRefs[n];await addDoc(collection(db,'operational_logs'),{logVersion:3,date:at,activity:$('bmAction').value,activityLabel:a.label,status:'In Transit',movementGroupId:g.id,movementBatchId:batchId,movementId:mr.id,referenceType:a.refType,referenceNumber:g.reference,poType:a.legacyType,poNumber:a.refType==='wellora_po'||a.refType==='client_po'?g.reference:'',internalTransferNumber:a.refType==='internal_transfer'?g.reference:'',receivingNumber:a.refType==='receiving_no'?g.reference:'',fromType:a.from,fromName:s.name,toType:a.to,toName:d.name,qty:l.qty,unit:l.item.unit||'',itemId:l.item.id,itemCode:l.item.itemCode,itemAlias:l.item.alias||'',itemName:l.item.name,clientId:a.to==='client'?d.id:a.from==='client'?s.id:'',clientName:a.to==='client'?d.name:a.from==='client'?s.name:'',supplierId:a.from==='supplier'?s.id:'',supplierName:a.from==='supplier'?s.name:'',logisticsProviderId,logisticsProviderName,contactPerson,contactNumber,transportNo,logisticsReference,movementDate,deliveryTicket,receivingTicket,performedBy:email,performedByRole:user.role||window.IMS_ROLE||'',remark});}
 await addDoc(collection(db,'audit_traces'),{traceVersion:3,actionType:'START_MOVEMENT_BATCH',module:'Movement',targetType:'movement_batch',targetName:`${g.reference} · ${a.label} · ${lines.length} line(s)`,targetId:batchId,summary:`Start Movement Batch under ${a.refLabel} ${g.reference}`,beforeValue:rr?{reservationId:rr.id,reservedQty:rr.total}:null,afterValue:{movementGroupId:g.id,referenceType:a.refType,referenceNumber:g.reference,company:g.partyName||'',source:s.name,destination:d.name,reservation:reservationAudit,lines:lines.map(l=>({welloraSN:l.item.alias||'',itemCode:l.item.itemCode,qty:l.qty}))},changedFields:['movementGroupId','referenceNumber','source','destination','lines','logistics'],remark,performedBy:email,performedByRole:user.role||window.IMS_ROLE||'',performedAt:at});alert(`${lines.length} movement line(s) started under ${a.refLabel} ${g.reference}.`);location.reload();}catch(err){alert('Movement failed: '+(err?.message||err));saving=false;const btn=$('bmSave');if(btn){btn.disabled=false;btn.textContent='Start Movement';}}}
async function arriveMovement(id){if(!can('movement.edit'))return;await load();const m=movements.find(x=>x.id===id);if(!m||m.status!=='in_transit')return;const email=auth.currentUser?.email||'',at=now(),ref=doc(db,'inventory',m.itemId);await runTransaction(db,async tx=>{const snap=await tx.get(ref);if(!snap.exists())throw new Error('Item missing.');const bal=balances(snap.data()),tr=bal.find(b=>b.locationType==='transit'&&b.locationId===m.movementId);if(!tr||tr.qty<m.qty)throw new Error('Transit balance missing.');tr.qty-=m.qty;let dst=bal.find(b=>b.locationType===m.toType&&((m.toId&&String(b.locationId)===String(m.toId))||norm(b.locationName)===norm(m.toName)));if(dst){dst.qty+=m.qty;dst.status=m.toStatus;}else bal.push({qty:m.qty,locationType:m.toType,locationId:m.toId||'',locationName:m.toName,status:m.toStatus});const clean=bal.filter(x=>x.qty>0),sum=summary(clean);tx.update(ref,{stockBalances:clean,status:sum.status,currentLocation:sum.location,lastEditedBy:email,lastEditedAt:at});tx.update(doc(db,'movements',id),{status:'arrived',arrivedAt:at,arrivedBy:email});});location.reload();}
async function mount(){if(!can('movement.view'))return;const core=$('moveForm');if(!core||$('batchMoveForm'))return;try{await load();}catch(err){console.error('IMS Movement load failed:',err);core.innerHTML=`<div class="border border-red-900 rounded-xl p-3 text-xs text-red-300">Unable to load Movement: ${esc(err?.message||err)}</div>`;return;}const w=document.createElement('div');w.innerHTML=formHtml('DELIVER_CLIENT');core.replaceWith(w.firstElementChild);bindForm();syncTop();renderDynamic();}
let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(()=>mount().catch(console.error),35);}).observe(document.body,{childList:true,subtree:true});mount().catch(console.error);window.arriveMovement=arriveMovement;window.IMSMovement=Object.freeze({mount,load,arriveMovement});window.dispatchEvent(new CustomEvent('ims:movement-ready'));export{mount,load,arriveMovement};