import { auth, db } from '../../firebase-config.js';
import { collection, addDoc, getDocs, doc, updateDoc } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';
import { can } from '../../ims-permissions.js';
const inputCls='w-full min-w-0 bg-slate-950 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-red-500';
const SYSTEM_ROLES=Object.freeze([['supplier','Supplier'],['client','Client'],['maintenance_provider','Maintenance Provider'],['inspection_provider','Inspection Provider'],['transport','Transport'],['shipping','Shipping']]);
let allBusinesses=[],activeKind='';
const byId=id=>document.getElementById(id),nowISO=()=>new Date().toISOString(),norm=s=>String(s??'').trim().replace(/\s+/g,' ').toLowerCase(),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=(txt,html)=>`<label class="block min-w-0 text-xs text-slate-400"><span class="block mb-1">${txt}</span>${html}</label>`,card=(title,body)=>`<section class="w-full bg-slate-900 border border-slate-800 rounded-2xl p-4 sm:p-5 shadow-xl"><h2 class="font-bold text-sm sm:text-base mb-4">${title}</h2>${body}</section>`,roleLabel=id=>SYSTEM_ROLES.find(x=>x[0]===id)?.[1]||id;
function normalizeTags(raw){const seen=new Set();return String(raw||'').split(',').map(x=>x.trim().replace(/\s+/g,' ')).filter(x=>{const n=norm(x);if(!n||seen.has(n))return false;seen.add(n);return true;});}
function rolesFor(x){const roles=Array.isArray(x.businessRoles)?x.businessRoles.filter(Boolean):[];return roles.length?[...new Set(roles)]:[x.sourceKind||'supplier'];}
function tagsFor(x){return Array.isArray(x.businessTags)?x.businessTags.filter(Boolean):[];}
function dataFor(kind){return allBusinesses.filter(x=>rolesFor(x).includes(kind));}
async function loadCollection(name,sourceKind){const snap=await getDocs(collection(db,name));return snap.docs.map(d=>({id:d.id,sourceCollection:name,sourceKind,...d.data()}));}
async function reload(){const[s,c]=await Promise.all([loadCollection('supplier_profiles','supplier'),loadCollection('client_profiles','client')]);allBusinesses=[...s,...c];return allBusinesses;}
async function writeAudit(actionType,module,targetType,targetName,beforeValue=null,afterValue=null,remark='',targetId=''){const user=auth.currentUser;if(!user)return;await addDoc(collection(db,'audit_traces'),{traceVersion:3,actionType,module,targetType,targetName:String(targetName||''),targetId:String(targetId||''),summary:`${String(actionType||'').replace(/_/g,' ')}: ${targetName||targetType||module}`,beforeValue,afterValue,changedFields:[],remark:String(remark||''),metadata:{source:'business-module'},performedBy:user.email||'',performedByRole:window.IMS_ROLE||'',performedAt:nowISO()});}
function roleChecks(kind,x={}){const selected=new Set(x.id?rolesFor(x):[kind]);return`<div class="sm:col-span-2 xl:col-span-4"><div class="text-xs text-slate-400 mb-2">Business Roles</div><div class="flex flex-wrap gap-2">${SYSTEM_ROLES.map(([id,name])=>`<label class="flex items-center gap-2 bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-xs"><input class="bizRole" type="checkbox" value="${id}" ${selected.has(id)?'checked':''}>${esc(name)}</label>`).join('')}</div><div class="text-[10px] text-slate-500 mt-2">One profile may appear in several directories through its roles. No duplicate company is required.</div></div>`;}
function businessFields(kind,x={}){return`<input type="hidden" id="bizId" value="${esc(x.id||'')}"><input type="hidden" id="bizSourceCollection" value="${esc(x.sourceCollection||'')}"><div class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-3 items-end">${label('Company Name',`<input id="bizCompany" required class="${inputCls}" value="${esc(x.companyName||x.supplierName||x.clientName||'')}">`)}${label('Registration No.',`<input id="bizReg" class="${inputCls}" value="${esc(x.registrationNo||'')}">`)}${label('Contact Person',`<input id="bizContact" class="${inputCls}" value="${esc(x.contactPerson||x.contact||'')}">`)}${label('Telephone',`<input id="bizTel" class="${inputCls}" value="${esc(x.tel||'')}">`)}${label('Mobile',`<input id="bizMobile" class="${inputCls}" value="${esc(x.mobile||'')}">`)}${label('Fax',`<input id="bizFax" class="${inputCls}" value="${esc(x.fax||'')}">`)}${label('Email',`<input type="email" id="bizEmail" class="${inputCls}" value="${esc(x.email||'')}">`)}${label('Website',`<input id="bizWebsite" class="${inputCls}" value="${esc(x.website||'')}">`)}<div class="sm:col-span-2 xl:col-span-4">${label('Address',`<textarea id="bizAddress" rows="2" class="${inputCls}">${esc(x.address||'')}</textarea>`)}</div>${label('Country',`<input id="bizCountry" class="${inputCls}" value="${esc(x.country||'Malaysia')}">`)}${label('Business Code',`<input id="bizCode" class="${inputCls}" value="${esc(x.businessCode||'')}">`)}<div class="sm:col-span-2">${label('Custom Tags',`<input id="bizTags" class="${inputCls}" value="${esc(tagsFor(x).join(', '))}" placeholder="Oil & Gas, Offshore, Sabah...">`)}</div>${roleChecks(kind,x)}<div class="sm:col-span-2 xl:col-span-4">${label('Remark',`<textarea id="bizRemark" rows="2" class="${inputCls}">${esc(x.remark||'')}</textarea>`)}</div></div>`;}
function setHeader(kind){const title=kind==='supplier'?'Suppliers':'Clients',tabId=kind==='supplier'?'suppliers':'clients';if(byId('pageTitle'))byId('pageTitle').textContent=title;if(byId('pageSubtitle'))byId('pageSubtitle').textContent='Shared Business Profiles filtered by role and custom tags.';document.querySelectorAll('.navBtn[data-tab]').forEach(btn=>btn.className=`navBtn text-left px-3 py-2.5 rounded-xl text-xs font-semibold ${btn.dataset.tab===tabId?'bg-red-600 text-white':'bg-slate-800/50 hover:bg-slate-800'}`);}
function render(kind){activeKind=kind;const title=kind==='supplier'?'Suppliers':'Clients',singular=kind==='supplier'?'Supplier':'Client',mount=byId('appContent');if(!mount)return;setHeader(kind);const roleOptions=SYSTEM_ROLES.map(([id,name])=>`<option value="${id}">${esc(name)}</option>`).join('');mount.innerHTML=`<div class="w-full space-y-5">${card(`${singular} Details`,`<form id="bizForm" class="space-y-4">${businessFields(kind)}<div class="flex flex-wrap gap-2"><button class="flex-1 min-w-[180px] bg-red-600 py-2.5 rounded-lg text-sm font-bold">Save Business</button><button type="button" id="bizReset" class="bg-slate-700 px-4 py-2.5 rounded-lg text-xs">Clear</button></div></form>`)}${card(`${title} Directory`,`<div class="grid sm:grid-cols-3 gap-2"><input id="bizSearch" class="${inputCls}" placeholder="Search company, contact, role, tag..."><select id="bizRoleFilter" class="${inputCls}"><option value="">All Roles</option>${roleOptions}</select><input id="bizTagFilter" class="${inputCls}" placeholder="Filter custom tag"></div><div id="bizList" class="mt-3 space-y-2 max-h-[70vh] overflow-y-auto"></div>`)}</div>`;byId('bizForm').onsubmit=e=>saveBusiness(e,kind);byId('bizReset').onclick=()=>render(kind);['bizSearch','bizRoleFilter','bizTagFilter'].forEach(id=>byId(id).oninput=()=>renderList(kind));renderList(kind);}
function renderList(kind){const data=dataFor(kind),q=norm(byId('bizSearch')?.value||''),role=byId('bizRoleFilter')?.value||'',tag=norm(byId('bizTagFilter')?.value||''),mount=byId('bizList');mount.innerHTML=data.filter(x=>{const r=rolesFor(x),tags=tagsFor(x),hay=norm(`${JSON.stringify(x)} ${r.map(roleLabel).join(' ')} ${tags.join(' ')}`);return(!q||hay.includes(q))&&(!role||r.includes(role))&&(!tag||tags.some(t=>norm(t).includes(tag)));}).map(x=>{const r=rolesFor(x),tags=tagsFor(x),editBtn=can(`${kind}.edit`)?`<button data-biz-key="${x.sourceCollection}|${x.id}" class="bizEdit bg-slate-700 px-2 py-1 rounded text-[10px]">Edit</button>`:'',statusBtn=can(`${kind}.status`)?`<button data-biz-key="${x.sourceCollection}|${x.id}" class="bizStatus bg-slate-700 px-2 py-1 rounded text-[10px]">${x.status==='inactive'?'Activate':'Deactivate'}</button>`:'';return`<div class="bg-slate-950 border border-slate-800 rounded-xl p-3"><div class="flex justify-between gap-2"><div class="min-w-0"><div class="font-semibold text-sm">${esc(x.companyName||x.supplierName||x.clientName||'')}</div><div class="text-[11px] text-slate-500">${esc(x.contactPerson||x.contact||'')} · ${esc(x.tel||x.mobile||'')} · ${esc(x.email||'')}</div><div class="flex flex-wrap gap-1 mt-2">${r.map(v=>`<span class="text-[10px] bg-cyan-950/50 border border-cyan-900 rounded px-2 py-1">${esc(roleLabel(v))}</span>`).join('')}${tags.map(t=>`<span class="text-[10px] bg-slate-800 rounded px-2 py-1">${esc(t)}</span>`).join('')}</div><div class="text-[10px] mt-2 ${x.status==='inactive'?'text-amber-400':'text-emerald-400'}">${x.status||'active'}</div></div><div class="flex gap-1 shrink-0">${editBtn}${statusBtn}</div></div></div>`;}).join('')||'<div class="text-sm text-slate-500">No records.</div>';mount.querySelectorAll('.bizEdit').forEach(btn=>btn.onclick=()=>editBusiness(kind,btn.dataset.bizKey));mount.querySelectorAll('.bizStatus').forEach(btn=>btn.onclick=()=>toggleBusiness(kind,btn.dataset.bizKey));}
function findKey(key){const [sourceCollection,id]=String(key).split('|');return allBusinesses.find(x=>x.sourceCollection===sourceCollection&&x.id===id);}
function editBusiness(kind,key){if(!can(`${kind}.edit`))return;const x=findKey(key),form=byId('bizForm');if(!x||!form)return;form.innerHTML=`${businessFields(kind,x)}<div class="flex flex-wrap gap-2"><button class="flex-1 min-w-[180px] bg-red-600 py-2.5 rounded-lg text-sm font-bold">Save Changes</button><button type="button" id="bizCancel" class="bg-slate-700 px-4 py-2.5 rounded-lg text-xs">Cancel</button></div>`;form.onsubmit=e=>saveBusiness(e,kind);byId('bizCancel').onclick=()=>render(kind);}
async function saveBusiness(e,kind){e.preventDefault();const id=byId('bizId').value,sourceCollection=byId('bizSourceCollection').value,old=id?allBusinesses.find(x=>x.id===id&&x.sourceCollection===sourceCollection):null,permission=old?`${kind}.edit`:`${kind}.add`;if(!can(permission))return;const company=byId('bizCompany').value.trim();if(!company)return;const businessRoles=[...document.querySelectorAll('.bizRole:checked')].map(x=>x.value);if(!businessRoles.length)return alert('Select at least one Business Role.');const businessTags=normalizeTags(byId('bizTags').value),rec={companyName:company,supplierName:company,clientName:company,registrationNo:byId('bizReg').value.trim(),contactPerson:byId('bizContact').value.trim(),contact:byId('bizContact').value.trim(),tel:byId('bizTel').value.trim(),mobile:byId('bizMobile').value.trim(),fax:byId('bizFax').value.trim(),email:byId('bizEmail').value.trim(),website:byId('bizWebsite').value.trim(),address:byId('bizAddress').value.trim(),country:byId('bizCountry').value.trim(),businessCode:byId('bizCode').value.trim(),businessRoles,businessTags,businessTagsNormalized:businessTags.map(norm),remark:byId('bizRemark').value.trim(),status:old?.status||'active',updatedAt:nowISO(),updatedBy:auth.currentUser?.email||''};if(old){const reason=prompt('Reason for editing this business record (required)','');if(!reason?.trim())return;await updateDoc(doc(db,sourceCollection,id),rec);await writeAudit('EDIT_BUSINESS','Businesses','business',company,old,rec,reason.trim(),id);}else{rec.createdAt=nowISO();rec.createdBy=auth.currentUser?.email||'';const collectionName=kind==='client'?'client_profiles':'supplier_profiles',ref=await addDoc(collection(db,collectionName),rec);await writeAudit('CREATE_BUSINESS','Businesses','business',company,null,rec,'',ref.id);}await reload();render(kind);}
async function toggleBusiness(kind,key){if(!can(`${kind}.status`))return;const x=findKey(key);if(!x)return;const status=x.status==='inactive'?'active':'inactive',reason=prompt(`Reason for ${status==='inactive'?'deactivating':'activating'} this business (required)`,'');if(!reason?.trim())return;await updateDoc(doc(db,x.sourceCollection,x.id),{status,updatedAt:nowISO(),updatedBy:auth.currentUser?.email||''});await writeAudit('CHANGE_BUSINESS_STATUS','Businesses','business',x.companyName||x.supplierName||x.clientName,{status:x.status||'active'},{status},reason.trim(),x.id);await reload();render(kind);}
function interceptNavigation(){document.addEventListener('click',async event=>{const btn=event.target.closest?.('.navBtn[data-tab="suppliers"], .navBtn[data-tab="clients"]');if(!btn)return;const kind=btn.dataset.tab==='suppliers'?'supplier':'client';if(!can(`${kind}.view`))return;event.preventDefault();event.stopImmediatePropagation();try{await reload();render(kind);}catch(error){console.error('IMS business module failed:',error);}},true);}
interceptNavigation();window.IMSBusinesses=Object.freeze({reload,render,SYSTEM_ROLES});window.dispatchEvent(new CustomEvent('ims:businesses-ready'));export {reload,render,SYSTEM_ROLES};