import { auth, db } from '../../firebase-config.js';
import { addDoc, collection, getCountFromServer, getDocs, limit, orderBy, query, startAfter, where } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';
import { can } from '../../ims-permissions.js';

const PAGE_SIZE=50,EXPORT_BATCH=500;
let records=[],page=0,total=0,loading=false,cursors=[null];
const byId=id=>document.getElementById(id),nowISO=()=>new Date().toISOString();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const friendly=s=>String(s||'').toLowerCase().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const displayDate=v=>v?new Date(v).toLocaleString():'';
function baseQuery(){return query(collection(db,'audit_traces'),orderBy('performedAt','desc'));}
function pageQuery(base,cursor,batchSize=PAGE_SIZE){const parts=[];if(cursor)parts.push(startAfter(cursor));parts.push(limit(batchSize));return query(base,...parts);}
function exportRange(){const from=byId('imsAuditFrom')?.value||'',to=byId('imsAuditTo')?.value||'';if(from&&to&&to<from)throw new Error('To Date cannot be before From Date.');return{from,to};}
function exportBase(){const{from,to}=exportRange(),parts=[];if(from)parts.push(where('performedAt','>=',`${from}T00:00:00.000Z`));if(to)parts.push(where('performedAt','<=',`${to}T23:59:59.999Z`));parts.push(orderBy('performedAt','desc'));return{base:query(collection(db,'audit_traces'),...parts),from,to};}
async function reload(reset=false){if(!can('audit.view')){records=[];total=0;return records;}if(loading)return records;loading=true;if(reset){page=0;cursors=[null];}if(byId('imsAuditBody'))byId('imsAuditBody').innerHTML='<tr><td colspan="8" class="p-5 text-center text-slate-500">Loading...</td></tr>';try{const base=baseQuery(),cursor=page>0?cursors[page]:null;const[snap,countSnap]=await Promise.all([getDocs(pageQuery(base,cursor)),getCountFromServer(base)]);records=snap.docs.map(d=>({id:d.id,...d.data()}));total=countSnap.data().count||0;if(snap.docs.length)cursors[page+1]=snap.docs.at(-1);renderRows();return records;}finally{loading=false;}}
async function writeAudit(actionType,targetName,afterValue={}){const user=auth.currentUser;if(!user)return;await addDoc(collection(db,'audit_traces'),{traceVersion:3,actionType,module:'Audit',targetType:'audit_export',targetName,targetId:'',summary:`${friendly(actionType)}: ${targetName}`,beforeValue:null,afterValue,changedFields:[],remark:'',metadata:{source:'audit-module'},performedBy:user.email||'',performedByRole:window.IMS_ROLE||'',performedAt:nowISO()});}
function setHeader(){if(byId('pageTitle'))byId('pageTitle').textContent='Audit / Trace';if(byId('pageSubtitle'))byId('pageSubtitle').textContent='Superadmin audit history · newest first · server paginated.';document.querySelectorAll('.navBtn[data-tab]').forEach(btn=>btn.className=`navBtn text-left px-3 py-2.5 rounded-xl text-xs font-semibold ${btn.dataset.tab==='audit'?'bg-red-600 text-white':'bg-slate-800/50 hover:bg-slate-800'}`);}
function render(){if(!can('audit.view'))return;const mount=byId('appContent');if(!mount)return;setHeader();const exportTools=can('audit.export.csv')?`<div class="flex flex-wrap items-end gap-2"><label class="text-[10px] text-slate-500">From Date<input id="imsAuditFrom" type="date" class="block mt-1 bg-slate-950 border border-slate-700 rounded-lg px-2 py-2 text-xs"></label><label class="text-[10px] text-slate-500">To Date<input id="imsAuditTo" type="date" class="block mt-1 bg-slate-950 border border-slate-700 rounded-lg px-2 py-2 text-xs"></label><button id="imsAuditExport" class="bg-cyan-700 px-4 py-2 rounded-lg text-xs font-bold">Export CSV</button></div>`:'';mount.innerHTML=`<div id="imsAuditModule"><section class="bg-slate-900 border border-slate-800 rounded-2xl p-4 sm:p-5"><div class="flex flex-wrap items-end justify-between gap-3"><div><div class="font-semibold text-sm">System Audit</div><div class="text-[11px] text-slate-500 mt-1">Browsing is server paginated. Export can be bounded by date for large histories.</div></div>${exportTools}</div></section><section class="bg-slate-900 border border-slate-800 rounded-2xl p-4 sm:p-5 mt-5"><div id="imsAuditCount" class="text-xs text-slate-500 mb-3"></div><div class="overflow-auto max-h-[68vh] border border-slate-800 rounded-xl"><table class="w-full min-w-[1150px] text-xs"><thead class="sticky top-0 bg-slate-950 text-slate-400"><tr>${['Date','User','Role','Module','Action','Target','Changed','Remark'].map(n=>`<th class="p-2 text-left">${n}</th>`).join('')}</tr></thead><tbody id="imsAuditBody"></tbody></table></div><div class="flex items-center justify-between gap-2 mt-3"><button id="imsAuditPrev" class="bg-slate-700 px-4 py-2 rounded-lg text-xs font-bold disabled:opacity-40">Previous</button><button id="imsAuditNext" class="bg-slate-700 px-4 py-2 rounded-lg text-xs font-bold disabled:opacity-40">Next</button></div></section></div>`;byId('imsAuditPrev').onclick=()=>{if(page>0){page--;reload(false).catch(()=>{});}};byId('imsAuditNext').onclick=()=>{if((page+1)*PAGE_SIZE<total){page++;reload(false).catch(()=>{});}};if(byId('imsAuditExport'))byId('imsAuditExport').onclick=()=>exportAudit().catch(error=>alert('Audit CSV export failed: '+(error?.message||error)));}
function renderRows(){const body=byId('imsAuditBody');if(!body)return;body.innerHTML=records.map(x=>`<tr class="border-t border-slate-900"><td class="p-2 whitespace-nowrap">${esc(displayDate(x.performedAt))}</td><td class="p-2">${esc(x.performedBy||'')}</td><td class="p-2">${esc(x.performedByRole||'')}</td><td class="p-2">${esc(x.module||'')}</td><td class="p-2">${esc(friendly(x.actionType))}</td><td class="p-2">${esc(x.targetName||'')}</td><td class="p-2">${esc((x.changedFields||[]).join(', ')||'—')}</td><td class="p-2 max-w-[280px]">${esc(x.remark||'')}</td></tr>`).join('')||'<tr><td colspan="8" class="p-4 text-center text-slate-500">No audit records.</td></tr>';const start=total?page*PAGE_SIZE+1:0,end=Math.min(page*PAGE_SIZE+records.length,total);if(byId('imsAuditCount'))byId('imsAuditCount').textContent=`Showing ${start}–${end} of ${total} audit record(s) · Page ${page+1} of ${Math.max(1,Math.ceil(total/PAGE_SIZE))}`;if(byId('imsAuditPrev'))byId('imsAuditPrev').disabled=page===0;if(byId('imsAuditNext'))byId('imsAuditNext').disabled=end>=total;}
function csvCell(v){return`"${String(v??'').replace(/"/g,'""')}"`;}
async function exportAudit(){if(!can('audit.export.csv'))return;const btn=byId('imsAuditExport');if(btn){btn.disabled=true;btn.textContent='Exporting...';}try{const{base,from,to}=exportBase(),chunks=[];let cursor=null,count=0;const headers=['Date','User','Role','Module','Action','Target','Changed','Before','After','Remark'];chunks.push(headers.map(csvCell).join(','));while(true){const snap=await getDocs(pageQuery(base,cursor,EXPORT_BATCH));for(const d of snap.docs){const x=d.data(),row=[x.performedAt||'',x.performedBy||'',x.performedByRole||'',x.module||'',friendly(x.actionType),x.targetName||'',(x.changedFields||[]).join(', '),JSON.stringify(x.beforeValue??null),JSON.stringify(x.afterValue??null),x.remark||''];chunks.push(row.map(csvCell).join(','));count++;}if(snap.size<EXPORT_BATCH)break;cursor=snap.docs.at(-1);}if(!count)return alert('No audit records in the selected range.');const text='\ufeff'+chunks.join('\n'),url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`IMS_Audit_${from||'START'}_to_${to||'LATEST'}.csv`;a.click();URL.revokeObjectURL(url);try{await writeAudit('EXPORT_AUDIT','Audit CSV Export',{count,from,to});}catch(error){console.warn('Audit CSV exported but export trace failed:',error);}}finally{if(btn){btn.disabled=false;btn.textContent='Export CSV';}}}
async function renderAndLoad(){render();try{await reload(true);}catch(error){console.error('IMS audit module failed:',error);}}
document.addEventListener('click',event=>{const btn=event.target.closest?.('.navBtn[data-tab="audit"]');if(!btn||!can('audit.view'))return;event.preventDefault();event.stopImmediatePropagation();renderAndLoad();},true);
window.IMSAudit=Object.freeze({reload,render:renderAndLoad});window.dispatchEvent(new CustomEvent('ims:audit-ready'));export {reload,renderAndLoad as render};
