import { auth, db, firebaseConfig } from '../../firebase-config.js';
import { getAuth, createUserWithEmailAndPassword } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-auth.js';
import { initializeApp, deleteApp } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-app.js';
import { collection, addDoc, documentId, getCountFromServer, getDocs, doc, setDoc, updateDoc, query, where, limit, orderBy, startAfter } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';
import { can } from '../../ims-permissions.js';

const inputCls='w-full min-w-0 bg-slate-950 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-red-500';
const PAGE_SIZE=50;
let users=[],page=0,total=0,cursors=[null],lastDoc=null,loading=false;
const byId=id=>document.getElementById(id);
const nowISO=()=>new Date().toISOString();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=(txt,html)=>`<label class="block min-w-0 text-xs text-slate-400"><span class="block mb-1">${txt}</span>${html}</label>`;
const card=(title,body)=>`<section class="w-full bg-slate-900 border border-slate-800 rounded-2xl p-4 sm:p-5 shadow-xl"><h2 class="font-bold text-sm sm:text-base mb-4">${title}</h2>${body}</section>`;

function baseQuery(){const c=collection(db,'users');return can('users.role.edit')?query(c,orderBy('email','asc'),orderBy(documentId(),'asc')):query(c,where('role','==','admin'),orderBy(documentId(),'asc'));}
async function reload(reset=false){if(!can('users.view')){users=[];total=0;return users;}if(loading)return users;loading=true;if(reset){page=0;cursors=[null];}try{const base=baseQuery(),cursor=cursors[page]||null,q=cursor?query(base,startAfter(cursor),limit(PAGE_SIZE)):query(base,limit(PAGE_SIZE)),[snap,countSnap]=await Promise.all([getDocs(q),getCountFromServer(base)]);users=snap.docs.map(d=>({id:d.id,...d.data()}));lastDoc=snap.docs.at(-1)||null;total=countSnap.data().count||0;if(lastDoc)cursors[page+1]=lastDoc;return users;}finally{loading=false;}}
async function writeAudit(actionType,targetName,beforeValue=null,afterValue=null,remark='',targetId=''){const user=auth.currentUser;if(!user)return;await addDoc(collection(db,'audit_traces'),{traceVersion:3,actionType,module:'User Management',targetType:'user',targetName:String(targetName||''),targetId:String(targetId||''),summary:`${String(actionType||'').replace(/_/g,' ')}: ${targetName||'user'}`,beforeValue,afterValue,changedFields:[],remark:String(remark||''),metadata:{source:'users-module'},performedBy:window.IMSUser?.email||user.email||'',performedByRole:window.IMS_ROLE||'',performedAt:nowISO()});}
function setHeader(){if(byId('pageTitle'))byId('pageTitle').textContent='User Management';if(byId('pageSubtitle'))byId('pageSubtitle').textContent='Server-paginated account directory · no user deletion.';document.querySelectorAll('.navBtn[data-tab]').forEach(btn=>{btn.className=`navBtn text-left px-3 py-2.5 rounded-xl text-xs font-semibold ${btn.dataset.tab==='users'?'bg-red-600 text-white':'bg-slate-800/50 hover:bg-slate-800'}`;});}
function createRoleOptions(){return can('users.role.edit')?['admin','manager','superadmin']:['admin'];}
function canManageTarget(user){if(!can('users.status'))return false;if(user.uid===auth.currentUser?.uid||user.id===auth.currentUser?.uid)return false;if(user.role==='admin')return true;return can('users.role.edit');}
function pagerHtml(){const start=total?page*PAGE_SIZE+1:0,end=Math.min(page*PAGE_SIZE+users.length,total),prev=page>0,next=end<total&&users.length===PAGE_SIZE;return`<div class="flex items-center justify-between gap-2 mt-3"><div class="text-[11px] text-slate-500">${start}-${end} of ${total} account(s) · Page ${page+1}</div><div class="flex gap-2"><button id="imsUserPrev" ${prev?'':'disabled'} class="px-3 py-2 rounded-lg text-xs ${prev?'bg-slate-700':'bg-slate-900 text-slate-600'}">Previous</button><button id="imsUserNext" ${next?'':'disabled'} class="px-3 py-2 rounded-lg text-xs ${next?'bg-slate-700':'bg-slate-900 text-slate-600'}">Next</button></div></div>`;}
function render(){if(!can('users.view'))return;const mount=byId('appContent');if(!mount)return;setHeader();const createCard=can('users.add')?card('Create Account',`<form id="imsUserForm" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 items-end">${label('Email',`<input type="email" id="imsUserEmail" required class="${inputCls}">`)}${label('Temporary Password',`<input type="password" id="imsUserPassword" minlength="8" required class="${inputCls}">`)}${label('Role',`<select id="imsUserRole" class="${inputCls}">${createRoleOptions().map(x=>`<option value="${x}">${x}</option>`).join('')}</select>`)}<button class="sm:col-span-2 lg:col-span-3 w-full bg-red-600 py-2.5 rounded-lg text-sm font-bold">Create Account</button></form>`):'';const directory=card('Account Directory',`<div class="overflow-x-auto"><table class="w-full min-w-[700px] text-xs"><thead class="text-slate-500"><tr><th class="p-2 text-left">Email</th><th class="p-2">Role</th><th class="p-2">Status</th><th class="p-2">Created</th><th class="p-2">Actions</th></tr></thead><tbody>${users.map(u=>{const statusAction=canManageTarget(u)?`<button data-user-status="${u.id}" class="bg-slate-700 px-2 py-1 rounded text-[10px]">${u.status==='inactive'?'Activate':'Deactivate'}</button>`:'',roleAction=can('users.role.edit')&&u.uid!==auth.currentUser?.uid&&u.id!==auth.currentUser?.uid?` <button data-user-role="${u.id}" class="bg-violet-700 px-2 py-1 rounded text-[10px]">Role</button>`:'';return `<tr class="border-t border-slate-800"><td class="p-2">${esc(u.email)}</td><td class="p-2 text-center">${esc(u.role)}</td><td class="p-2 text-center">${esc(u.status||'active')}</td><td class="p-2 text-center">${esc(u.createdAt?.slice(0,10)||'')}</td><td class="p-2 text-center">${statusAction}${roleAction||''}${!statusAction&&!roleAction?'—':''}</td></tr>`;}).join('')||'<tr><td colspan="5" class="p-4 text-center text-slate-500">No visible accounts.</td></tr>'}</tbody></table></div>${pagerHtml()}`);mount.innerHTML=`<div id="imsUsersModule" class="w-full space-y-5">${createCard}${directory}</div>`;if(byId('imsUserForm'))byId('imsUserForm').onsubmit=createUserAccount;mount.querySelectorAll('[data-user-status]').forEach(btn=>btn.onclick=()=>toggleUser(btn.dataset.userStatus));mount.querySelectorAll('[data-user-role]').forEach(btn=>btn.onclick=()=>changeRole(btn.dataset.userRole));if(byId('imsUserPrev'))byId('imsUserPrev').onclick=()=>changePage(-1);if(byId('imsUserNext'))byId('imsUserNext').onclick=()=>changePage(1);}
async function changePage(delta){if(delta>0){const end=Math.min(page*PAGE_SIZE+users.length,total);if(end>=total||!lastDoc)return;page++;}else if(page>0)page--;else return;await reload(false);render();}
async function createUserAccount(e){e.preventDefault();if(!can('users.add'))return;const email=byId('imsUserEmail').value.trim().toLowerCase(),password=byId('imsUserPassword').value,role=byId('imsUserRole').value,allowedRoles=createRoleOptions();if(!allowedRoles.includes(role))return;if(password.length<8){alert('Password must be at least 8 characters.');return;}let app;try{app=initializeApp(firebaseConfig,`ims-provision-${Date.now()}`);const secondaryAuth=getAuth(app),cred=await createUserWithEmailAndPassword(secondaryAuth,email,password);await setDoc(doc(db,'users',cred.user.uid),{uid:cred.user.uid,email,role,status:'active',createdAt:nowISO(),createdBy:window.IMSUser?.email||auth.currentUser?.email||''});await writeAudit('CREATE_USER',email,null,{role,status:'active'},'',cred.user.uid);await reload(true);render();alert('Account created.');}catch(err){alert('Create user failed: '+(err?.message||String(err)));}finally{if(app)try{await deleteApp(app);}catch{}}}
async function toggleUser(id){const u=users.find(x=>x.id===id);if(!u||!canManageTarget(u))return;const status=u.status==='inactive'?'active':'inactive',reason=prompt(`Reason for ${status==='inactive'?'deactivating':'activating'} ${u.email} (required)`,'');if(!reason?.trim())return;await updateDoc(doc(db,'users',id),{status});await writeAudit('CHANGE_USER_STATUS',u.email,{status:u.status||'active'},{status},reason.trim(),id);await reload(false);render();}
async function changeRole(id){if(!can('users.role.edit'))return;const u=users.find(x=>x.id===id);if(!u||u.uid===auth.currentUser?.uid||u.id===auth.currentUser?.uid)return;const role=prompt('New role: admin, manager or superadmin',u.role);if(!['admin','manager','superadmin'].includes(role)||role===u.role)return;const reason=prompt('Reason for role change (required)','');if(!reason?.trim())return;await updateDoc(doc(db,'users',id),{role});await writeAudit('CHANGE_USER_ROLE',u.email,{role:u.role},{role},reason.trim(),id);await reload(true);render();}
function interceptNavigation(){document.addEventListener('click',async event=>{const btn=event.target.closest?.('.navBtn[data-tab="users"]');if(!btn||!can('users.view'))return;event.preventDefault();event.stopImmediatePropagation();try{await reload(true);render();}catch(error){console.error('IMS users module failed:',error);}},true);}
interceptNavigation();window.IMSUsers=Object.freeze({reload,render});window.dispatchEvent(new CustomEvent('ims:users-ready'));export {reload,render};