import { db } from '../../firebase-config.js';
import { collection, getCountFromServer, getDocs, limit, orderBy, query, startAfter } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';
import { can } from '../../ims-permissions.js';

const PAGE_SIZE=25;
let page=0,cursors=[null],pageDocs=[],total=0,loading=false;
const byId=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fmt(v){if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return `${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;}
function build(withPage=true){const a=[orderBy('date','desc')];if(withPage&&page>0&&cursors[page])a.push(startAfter(cursors[page]));if(withPage)a.push(limit(PAGE_SIZE));return query(collection(db,'operational_logs'),...a);}
function display(x){const arrival=String(x.activity||'').toUpperCase()==='ARRIVAL';let activity=x.activityLabel||x.activity||'',from=x.fromName||'',to=x.toName||'',status=x.status||'';if(arrival){from='Transit';if(x.toType==='client')activity='Arrival at Client';else if(x.toType==='warehouse')activity='Arrival at Warehouse';else if(x.toType==='maintenance')activity='Arrival at Maintenance';else activity='Arrival';}return{activity,from,to,status};}
function rowData(x){const d=display(x);return{date:x.date||'',activity:d.activity,itemCode:x.itemCode||'',item:x.itemName||x.itemNameSnapshot||'',status:d.status,from:d.from,to:d.to,qty:x.qty??'',unit:x.unit||'',client:x.clientName||'',supplier:x.supplierName||'',invoice:x.invoiceNumber||'',user:x.performedBy||'',remark:x.remark||''};}
function setHeader(){document.querySelectorAll('.navBtn').forEach(b=>b.className='navBtn text-left px-3 py-2.5 rounded-xl text-xs font-semibold bg-slate-800/50 hover:bg-slate-800');const tab=document.querySelector('.navBtn[data-tab="logs"]');if(tab)tab.className='navBtn text-left px-3 py-2.5 rounded-xl text-xs font-semibold bg-red-600 text-white';if(byId('pageTitle'))byId('pageTitle').textContent='Logs / Records';if(byId('pageSubtitle'))byId('pageSubtitle').textContent='Operational history · newest first · server paginated.';}
function renderRows(){const body=byId('rmBody');if(!body)return;const rows=pageDocs.map(x=>rowData(x.data));body.innerHTML=rows.map(x=>`<tr class="border-t border-slate-900"><td class="p-2 whitespace-nowrap">${esc(fmt(x.date))}</td><td class="p-2">${esc(x.activity)}</td><td class="p-2">${esc(x.itemCode)}</td><td class="p-2">${esc(x.item)}</td><td class="p-2">${esc(x.status)}</td><td class="p-2">${esc(x.from)}</td><td class="p-2">${esc(x.to)}</td><td class="p-2 text-right">${esc(x.qty)}</td><td class="p-2">${esc(x.unit)}</td><td class="p-2">${esc(x.client)}</td><td class="p-2">${esc(x.supplier)}</td><td class="p-2">${esc(x.invoice)}</td><td class="p-2">${esc(x.user)}</td><td class="p-2">${esc(x.remark)}</td></tr>`).join('')||'<tr><td colspan="14" class="p-5 text-center text-slate-500">No records.</td></tr>';const start=total?page*PAGE_SIZE+1:0,end=Math.min((page+1)*PAGE_SIZE,total);if(byId('rmCount'))byId('rmCount').textContent=`Showing ${start}–${end} of ${total} records · Page ${page+1} of ${Math.max(1,Math.ceil(total/PAGE_SIZE))} · Newest first`;if(byId('rmPrev'))byId('rmPrev').disabled=page===0;if(byId('rmNext'))byId('rmNext').disabled=end>=total;}
async function load(reset=false){if(loading)return;loading=true;if(reset){page=0;cursors=[null];}if(byId('rmBody'))byId('rmBody').innerHTML='<tr><td colspan="14" class="p-5 text-center text-slate-500">Loading...</td></tr>';try{const[snap,countSnap]=await Promise.all([getDocs(build(true)),getCountFromServer(build(false))]);pageDocs=snap.docs.map(d=>({id:d.id,data:d.data()}));total=countSnap.data().count;if(snap.docs.length)cursors[page+1]=snap.docs[snap.docs.length-1];renderRows();window.IMSTableUI?.scan?.();}catch(err){console.error('IMS record query failed:',err);if(byId('rmCount'))byId('rmCount').textContent=`Logs unavailable: ${err?.message||err}`;}finally{loading=false;}}
function exportRows(){return pageDocs.map(x=>rowData(x.data)).map(x=>({Date:fmt(x.date),Activity:x.activity,'IMS Item ID':x.itemCode,Description:x.item,Status:x.status,From:x.from,To:x.to,Qty:x.qty,Unit:x.unit,Client:x.client,Supplier:x.supplier,'Invoice No.':x.invoice,User:x.user,Remark:x.remark}));}
function csv(){if(!can('records.export.csv'))return;const rows=exportRows();if(!rows.length)return alert('No rows on this page.');const heads=Object.keys(rows[0]),q=v=>`"${String(v??'').replace(/"/g,'""')}"`,text=[heads,...rows.map(Object.values)].map(r=>r.map(q).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download=`IMS_Logs_Page_${page+1}.csv`;a.click();URL.revokeObjectURL(a.href);}
function excel(){if(!can('records.export.csv'))return;const rows=exportRows();if(!rows.length)return alert('No rows on this page.');if(typeof XLSX==='undefined')return alert('Excel library unavailable.');const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Logs');XLSX.writeFile(wb,`IMS_Logs_Page_${page+1}.xlsx`);}
function printRecords(){if(can('records.print.pdf'))window.print();}
async function render(){if(!can('records.view'))return;setHeader();const th=n=>`<th class="p-2 text-left whitespace-nowrap font-semibold">${n}</th>`,exportButtons=can('records.export.csv')?`<button id="rmExcel" class="bg-emerald-700 px-4 py-2 rounded-lg text-xs font-bold">Export Page Excel</button><button id="rmCsv" class="bg-cyan-700 px-4 py-2 rounded-lg text-xs font-bold">Export Page CSV</button>`:'',printButton=can('records.print.pdf')?'<button id="rmPrint" class="bg-slate-700 px-4 py-2 rounded-lg text-xs font-bold">Print / Save PDF</button>':'';byId('appContent').innerHTML=`<div id="imsRecordsModule"><section class="bg-slate-900 border border-slate-800 rounded-2xl p-4 sm:p-5"><div class="flex flex-wrap gap-2">${exportButtons}${printButton}</div></section><section class="bg-slate-900 border border-slate-800 rounded-2xl p-4 sm:p-5 mt-5"><div id="rmCount" class="text-xs text-slate-500 mb-3"></div><div class="overflow-x-auto border border-slate-800 rounded-xl"><table class="w-full min-w-[1450px] text-xs"><thead class="bg-slate-950 text-slate-400"><tr>${th('Date')}${th('Activity')}${th('IMS Item ID')}${th('Description')}${th('Status')}${th('From')}${th('To')}<th class="p-2 text-right whitespace-nowrap font-semibold">Qty</th>${th('Unit')}${th('Client')}${th('Supplier')}${th('Invoice')}${th('User')}${th('Remark')}</tr></thead><tbody id="rmBody"></tbody></table></div><div class="flex items-center justify-between gap-2 mt-3"><button id="rmPrev" class="bg-slate-700 px-4 py-2 rounded-lg text-xs font-bold disabled:opacity-40">Previous</button><button id="rmNext" class="bg-slate-700 px-4 py-2 rounded-lg text-xs font-bold disabled:opacity-40">Next</button></div></section></div>`;byId('rmPrev').onclick=()=>{if(page>0){page--;load(false);}};byId('rmNext').onclick=()=>{if((page+1)*PAGE_SIZE<total){page++;load(false);}};if(byId('rmExcel'))byId('rmExcel').onclick=excel;if(byId('rmCsv'))byId('rmCsv').onclick=csv;if(byId('rmPrint'))byId('rmPrint').onclick=printRecords;window.IMSTableUI?.scan?.();await load(true);}
window.IMSRecords=Object.freeze({render,load});window.dispatchEvent(new CustomEvent('ims:records-ready'));export { render, load };
