import { db } from '../../firebase-config.js';
import { collection, getDocs } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';
import { can } from '../../ims-permissions.js';
const byId=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),norm=s=>String(s??'').trim().replace(/\s+/g,' ').toLowerCase(),pageSize=10;
let inventory=[],movements=[],initialShown=false,showing=false,activeTab='register';
const listState={transit:{page:0,q:'',sort:'newest'},supplier:{page:0,q:'',sort:'alias'},client:{page:0,q:'',sort:'alias'},maintenance:{page:0,q:'',sort:'alias'},inspection:{page:0,q:'',sort:'alias'}};
function balances(i){return(Array.isArray(i.stockBalances)?i.stockBalances:[]).filter(x=>Number(x.qty||0)>0);}function itemQty(i){const b=balances(i);return b.length?b.reduce((n,x)=>n+Number(x.qty||0),0):Number(i.quantity??i.qty??0);}function identity(i){return `<div class="font-semibold text-sm"><span class="text-cyan-300">${esc(i.alias||'No Alias')}</span> · <span class="font-mono text-xs">${esc(i.itemCode||'')}</span> · ${esc(i.name||'')}</div>`;}
async function load(){const[a,b]=await Promise.all([getDocs(collection(db,'inventory')),getDocs(collection(db,'movements'))]);inventory=a.docs.map(d=>({id:d.id,...d.data()}));movements=b.docs.map(d=>({id:d.id,...d.data()}));}
function setHead(){if(byId('pageTitle'))byId('pageTitle').textContent='Main Workspace';if(byId('pageSubtitle'))byId('pageSubtitle').textContent='Registration, movement, maintenance and inspection kept in focused operational views.';document.querySelectorAll('.navBtn').forEach(b=>b.className=`navBtn text-left px-3 py-2.5 rounded-xl text-xs font-semibold ${b.dataset.tab==='workspace'?'bg-red-600 text-white':'bg-slate-800/50 hover:bg-slate-800'}`);}
function card(title,id,body=''){return `<section class="w-full bg-slate-900 border border-slate-800 rounded-2xl p-4 sm:p-5 shadow-xl"><div class="flex items-center justify-between gap-3 mb-4"><h2 class="font-bold text-sm sm:text-base">${esc(title)}</h2></div><div id="${id}">${body}</div></section>`;}
function recentRegisteredHtml(){const r=[...inventory].sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).slice(0,10);return`<div class="space-y-2">${r.map(i=>`<button class="workspaceOpenItem w-full text-left bg-slate-950 border border-slate-800 rounded-lg p-2" data-id="${i.id}">${identity(i)}<div class="text-[10px] text-slate-500">${esc(i.serialNumber?`SN ${i.serialNumber} · `:'')}${esc(i.category||'')} · ${esc(i.createdAt||'')}</div></button>`).join('')||'<div class="text-xs text-slate-500">No registered items.</div>'}</div>`;}
function movementItems(kind){if(kind==='transit')return movements.filter(m=>m.status==='in_transit').map(m=>({kind,m,item:inventory.find(i=>i.id===m.itemId),alias:m.itemAlias||'',name:m.itemNameSnapshot||'',code:m.itemCode||'',location:`${m.fromName||''} → ${m.toName||''}`,createdAt:m.createdAt||'',qty:Number(m.qty||0),unit:m.unit||''}));const status=kind==='supplier'?'At Supplier':'At Client',rows=[];for(const i of inventory){for(const b of balances(i).filter(b=>b.status===status))rows.push({kind,item:i,alias:i.alias||'',name:i.name||'',code:i.itemCode||'',location:b.locationName||i.currentLocation||'',createdAt:i.createdAt||'',qty:Number(b.qty||0),unit:i.unit||'',balance:b});}return rows;}
function serviceItems(kind){const st=kind==='inspection'?'Inspection':'Maintenance';return inventory.filter(i=>balances(i).some(b=>b.status===st)||i.status===st).map(i=>({kind,item:i,alias:i.alias||'',code:i.itemCode||'',name:i.name||'',location:i.currentLocation||'',createdAt:i.createdAt||'',qty:itemQty(i),unit:i.unit||''}));}
function listRows(kind){const s=listState[kind],q=norm(s.q);let rows=(kind==='maintenance'||kind==='inspection'?serviceItems(kind):movementItems(kind)).filter(r=>!q||norm(`${r.alias} ${r.code} ${r.name} ${r.location} ${r.qty} ${r.unit}`).includes(q));rows.sort((a,b)=>{if(s.sort==='newest')return String(b.createdAt||'').localeCompare(String(a.createdAt||''));if(s.sort==='location')return String(a.location||'').localeCompare(String(b.location||''),undefined,{numeric:true,sensitivity:'base'});return String(a.alias||a.code).localeCompare(String(b.alias||b.code),undefined,{numeric:true,sensitivity:'base'});});return rows;}
function listMeta(kind){const all=listRows(kind),s=listState[kind],pages=Math.max(1,Math.ceil(all.length/pageSize));s.page=Math.min(s.page,pages-1);return{all,pages,slice:all.slice(s.page*pageSize,(s.page+1)*pageSize),s};}
function controls(kind){const s=listState[kind];return`<div class="grid sm:grid-cols-[minmax(0,1fr)_180px] gap-2 mb-3"><input class="workspaceListSearch w-full bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-xs" data-kind="${kind}" value="${esc(s.q)}" placeholder="Search Alias, IMS ID, Item, location..."><select class="workspaceListSort w-full bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-xs" data-kind="${kind}"><option value="alias" ${s.sort==='alias'?'selected':''}>Sort: Alias</option><option value="location" ${s.sort==='location'?'selected':''}>Sort: Location</option><option value="newest" ${s.sort==='newest'?'selected':''}>Sort: Newest</option></select></div>`;}
function listRowHtml(kind,r){if(kind==='maintenance'||kind==='inspection')return`<button class="workspaceOpenItem w-full text-left bg-slate-950 border border-slate-800 rounded-lg p-2" data-id="${r.item.id}">${identity(r.item)}<div class="text-[10px] text-slate-500">${esc(r.location)}</div></button>`;return`<div class="bg-slate-950 border border-slate-800 rounded-xl p-3 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><button class="workspaceOpenItem text-left min-w-0" data-id="${esc(r.item?.id||r.m?.itemId||'')}"><div class="font-semibold text-sm"><span class="text-cyan-300">${esc(r.alias||'No Alias')}</span> · <span class="font-mono text-xs">${esc(r.code||'')}</span> · ${esc(r.name||'')}</div><div class="text-[11px] text-slate-500">${esc(r.location)} · ${r.qty} ${esc(r.unit)}</div></button>${kind==='transit'&&can('movement.edit')?`<button class="imsArrive shrink-0 bg-emerald-600 hover:bg-emerald-500 px-4 py-2 rounded-lg text-xs font-bold" data-id="${r.m.id}">Arrive</button>`:''}</div>`;}
function listSection(kind,title){const {all,pages,slice,s}=listMeta(kind);return`<section class="w-full bg-slate-900 border border-slate-800 rounded-2xl p-4" data-workspace-list="${kind}"><div class="flex flex-wrap justify-between gap-2 items-center mb-3"><div><div class="font-bold">${esc(title)}</div><div id="workspaceListCount-${kind}" class="text-[10px] text-slate-500">${all.length} ${kind==='maintenance'||kind==='inspection'?'active item(s)':'line(s)'} · ${pageSize} per page</div></div><div id="workspaceListPageLabel-${kind}" class="text-xs text-slate-500">${s.page+1}/${pages}</div></div>${controls(kind)}<div id="workspaceListRows-${kind}" class="space-y-2">${slice.map(r=>listRowHtml(kind,r)).join('')||'<div class="text-sm text-slate-500">No matching records.</div>'}</div><div class="flex justify-between mt-3"><button class="workspaceListPage bg-slate-800 px-3 py-2 rounded text-xs disabled:opacity-40" data-kind="${kind}" data-dir="-1" ${s.page<=0?'disabled':''}>Previous</button><button class="workspaceListPage bg-slate-800 px-3 py-2 rounded text-xs disabled:opacity-40" data-kind="${kind}" data-dir="1" ${s.page>=pages-1?'disabled':''}>Next</button></div></section>`;}
function workspaceTabs(){return`<div class="flex flex-wrap gap-2 mb-5">${[['register','Register Item'],['movement','Movement'],['maintenance','Maintenance'],['inspection','Inspection']].map(([id,label])=>`<button class="workspaceTab px-4 py-2 rounded-lg text-xs font-bold ${activeTab===id?'bg-red-600 text-white':'bg-slate-800'}" data-workspace-tab="${id}">${label}</button>`).join('')}</div>`;}
function operationHtml(){if(activeTab==='register')return`<div class="space-y-5">${card('Register Item','registerForm','Loading Registration…')}${card('Recently Added','workspaceRecent',recentRegisteredHtml())}</div>`;if(activeTab==='movement')return`<div class="space-y-5">${card('Movement — Supplier / Warehouse / Client','moveForm','Loading Movement…')}${listSection('transit','In Transit / Arrival')}${listSection('supplier','At Supplier')}${listSection('client','At Client')}</div>`;if(activeTab==='maintenance')return`<div class="space-y-5">${card('Maintenance','maintenanceForm','Loading Maintenance…')}${listSection('maintenance','Currently Under Maintenance')}</div>`;return`<div class="space-y-5">${card('Inspection','inspectionForm','Loading Inspection…')}${listSection('inspection','Currently Under Inspection')}</div>`;}
function bindOpenItems(root=document){root.querySelectorAll('.workspaceOpenItem').forEach(b=>b.onclick=()=>b.dataset.id&&(window.IMSItems?.showItem?window.IMSItems.showItem(b.dataset.id):window.openItem?.(b.dataset.id)));}
function bindArrive(root=document){root.querySelectorAll('.imsArrive').forEach(b=>b.onclick=()=>window.IMSMovement?.arriveMovement?window.IMSMovement.arriveMovement(b.dataset.id):window.arriveMovement?.(b.dataset.id));}
function refreshList(kind){const root=document.querySelector(`[data-workspace-list="${kind}"]`);if(!root)return;const {all,pages,slice,s}=listMeta(kind),rows=byId(`workspaceListRows-${kind}`),count=byId(`workspaceListCount-${kind}`),label=byId(`workspaceListPageLabel-${kind}`);if(rows)rows.innerHTML=slice.map(r=>listRowHtml(kind,r)).join('')||'<div class="text-sm text-slate-500">No matching records.</div>';if(count)count.textContent=`${all.length} ${kind==='maintenance'||kind==='inspection'?'active item(s)':'line(s)'} · ${pageSize} per page`;if(label)label.textContent=`${s.page+1}/${pages}`;const buttons=root.querySelectorAll('.workspaceListPage');buttons.forEach(b=>{const dir=Number(b.dataset.dir||0);b.disabled=dir<0?s.page<=0:s.page>=pages-1;});bindOpenItems(root);bindArrive(root);}
function bindLists(){document.querySelectorAll('.workspaceListSearch').forEach(e=>e.oninput=()=>{const s=listState[e.dataset.kind];s.q=e.value;s.page=0;refreshList(e.dataset.kind);});document.querySelectorAll('.workspaceListSort').forEach(e=>e.onchange=()=>{const s=listState[e.dataset.kind];s.sort=e.value;s.page=0;refreshList(e.dataset.kind);});document.querySelectorAll('.workspaceListPage').forEach(b=>b.onclick=()=>{const s=listState[b.dataset.kind];s.page=Math.max(0,s.page+Number(b.dataset.dir||0));refreshList(b.dataset.kind);});}
async function mountActiveOperation(){try{if(activeTab==='register'){if(window.IMSRegistration?.mount)return window.IMSRegistration.mount();window.addEventListener('ims:registration-ready',()=>window.IMSRegistration?.mount?.(),{once:true});return;}if(activeTab==='movement'){if(window.IMSMovement?.mount)return window.IMSMovement.mount();window.addEventListener('ims:movement-ready',()=>window.IMSMovement?.mount?.(),{once:true});return;}if(activeTab==='maintenance'){if(window.IMSMaintenance?.mount)return window.IMSMaintenance.mount();window.addEventListener('ims:maintenance-ready',()=>window.IMSMaintenance?.mount?.(),{once:true});return;}if(activeTab==='inspection'){if(window.IMSInspection?.mount)return window.IMSInspection.mount();window.addEventListener('ims:inspection-ready',()=>window.IMSInspection?.mount?.(),{once:true});}}catch(err){console.error(`IMS ${activeTab} mount failed:`,err);const id=activeTab==='register'?'registerForm':activeTab==='movement'?'moveForm':activeTab==='maintenance'?'maintenanceForm':'inspectionForm',m=byId(id);if(m)m.innerHTML=`<div class="border border-red-900 rounded-xl p-3 text-xs text-red-300">Unable to load ${esc(activeTab)}: ${esc(err?.message||err)}</div>`;}}
function bind(){document.querySelectorAll('.workspaceTab').forEach(b=>b.onclick=()=>{activeTab=b.dataset.workspaceTab;render();});bindOpenItems();bindArrive();bindLists();}
async function render(){setHead();byId('appContent').innerHTML=`<div data-ims-workspace-module="1">${workspaceTabs()}<div id="workspaceOperation">${operationHtml()}</div><div id="itemDetailMount" class="mt-5"></div></div>`;bind();await mountActiveOperation();window.dispatchEvent(new CustomEvent('ims:workspace-rendered',{detail:{tab:activeTab}}));}
async function show(tab=activeTab){if(!can('app.view')||showing)return;activeTab=tab||'register';showing=true;try{await load();await render();}catch(err){console.error('IMS workspace failed:',err);}finally{showing=false;}}
function takeOwnership(){const b=document.querySelector('[data-tab="workspace"]');if(!b)return;b.dataset.imsWorkspaceOwned='1';b.onclick=()=>show();const open=/Main Workspace/i.test(byId('pageTitle')?.textContent||'')&&!document.querySelector('[data-ims-workspace-module="1"]');if(open&&!initialShown){initialShown=true;show();}}
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(takeOwnership,30);}).observe(document.body,{childList:true,subtree:true});takeOwnership();window.IMSWorkspace=Object.freeze({show,load,render,mountActiveOperation,refreshList});window.dispatchEvent(new CustomEvent('ims:workspace-ready'));export {show,load,render,mountActiveOperation,refreshList};