import { db } from '../../firebase-config.js';
import { collection, doc, getDoc, getDocs, limit, orderBy, query, where } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';
import { can } from '../../ims-permissions.js';

const byId=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),norm=s=>String(s??'').trim().replace(/\s+/g,' ').toLowerCase(),pageSize=10;
let inventory=[],movements=[],items=[],currentQuery='',pages={client:0,supplier:0,transit:0,maintenance:0};
function balances(i){return(Array.isArray(i.stockBalances)?i.stockBalances:[]).filter(x=>Number(x.qty||0)>0);}
function itemQty(i){const b=balances(i);return b.length?b.reduce((n,x)=>n+Number(x.qty||0),0):Number(i.quantity??i.qty??0);}
function itemHaystack(i){return norm(`${i.alias||''} ${i.itemCode||''} ${i.name||''} ${i.category||''} ${i.brand||''} ${i.model||''} ${i.grade||''} ${i.specification||''} ${i.supplierName||''} ${i.currentLocation||''} ${i.status||''} ${JSON.stringify(i.stockBalances||[])}`);}
function mergeUnique(list){const m=new Map();list.forEach(x=>{if(x?.id)m.set(x.id,x);});return[...m.values()];}
async function load(){const[a,b]=await Promise.all([getDocs(collection(db,'inventory')),getDocs(collection(db,'movements'))]);inventory=a.docs.map(d=>({id:d.id,...d.data()}));movements=b.docs.map(d=>({id:d.id,...d.data()}));}
function setHead(){if(byId('pageTitle'))byId('pageTitle').textContent='Main Workspace';if(byId('pageSubtitle'))byId('pageSubtitle').textContent='Daily operations — register, move, arrive, maintain and find items.';document.querySelectorAll('.navBtn').forEach(b=>b.className=`navBtn text-left px-3 py-2.5 rounded-xl text-xs font-semibold ${b.dataset.tab==='workspace'?'bg-red-600 text-white':'bg-slate-800/50 hover:bg-slate-800'}`);}
function card(title,id,body=''){return `<section class="bg-slate-900 border border-slate-800 rounded-2xl p-4 sm:p-5 shadow-xl"><div class="flex items-center justify-between gap-3 mb-4"><h2 class="font-bold text-sm sm:text-base">${esc(title)}</h2></div><div id="${id}">${body}</div></section>`;}
function stat(label,value){return `<div class="bg-slate-900 border border-slate-800 rounded-xl p-3"><div class="text-xl font-black">${value}</div><div class="text-[10px] text-slate-500">${esc(label)}</div></div>`;}
function statusCount(status){return inventory.reduce((n,i)=>n+balances(i).filter(b=>b.status===status).reduce((a,b)=>a+Number(b.qty||0),0),0);}
function activeMovements(){return movements.filter(x=>x.status==='in_transit').sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')));}
function arrivalHtml(){const a=activeMovements();return a.length?`<div class="space-y-2">${a.map(m=>`<div class="bg-slate-950 border border-slate-800 rounded-xl p-3"><div class="flex flex-col sm:flex-row sm:items-center justify-between gap-2"><div><div class="text-sm font-semibold"><span class="text-cyan-300">${esc(m.itemAlias||'No Alias')}</span> · ${esc(m.actionLabel||m.action||'Movement')}</div><div class="text-xs text-slate-400"><span class="font-mono">${esc(m.itemCode||'')}</span> · ${esc(m.itemNameSnapshot||'')} · ${esc(m.qty)} ${esc(m.unit||'')}</div><div class="text-[11px] text-slate-500">${esc(m.fromName||'')} → ${esc(m.toName||'')}</div></div>${can('movement.edit')?`<button class="imsArrive bg-emerald-600 hover:bg-emerald-500 px-4 py-2 rounded-lg text-xs font-bold" data-id="${m.id}">Arrive</button>`:''}</div></div>`).join('')}</div>`:'<div class="text-sm text-slate-500">No active movements.</div>';}
function identity(i){return `<div class="font-semibold text-sm"><span class="text-cyan-300">${esc(i.alias||'No Alias')}</span> · <span class="font-mono text-xs">${esc(i.itemCode||'')}</span> · ${esc(i.name||'')}</div>`;}
async function latestItems(){return [...inventory].sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).slice(0,pageSize);}
async function searchItems(raw){const qn=norm(raw);if(!qn)return latestItems();const found=inventory.filter(i=>itemHaystack(i).includes(qn));if(found.length)return found.slice(0,100);for(const field of ['itemCode','alias'])try{const exact=await getDocs(query(collection(db,'inventory'),where(field,'==',raw.trim()),limit(10)));exact.forEach(d=>found.push({id:d.id,...d.data()}));}catch{}try{const refs=await getDocs(query(collection(db,'document_refs'),where('refNumber','==',raw.trim()),limit(20)));for(const r of refs.docs){const id=r.data().itemId;if(id)try{const s=await getDoc(doc(db,'inventory',id));if(s.exists())found.push({id:s.id,...s.data()});}catch{}}}catch{}return mergeUnique(found).slice(0,100);}
function renderFinder(){const mount=byId('itemFindResults');if(!mount)return;const label=currentQuery?`${items.length} matching item${items.length===1?'':'s'}`:`Latest ${items.length} items`;mount.innerHTML=`<div class="flex items-center justify-between gap-3 mb-2"><div class="text-xs font-semibold text-slate-400">${esc(label)}</div><div class="text-[10px] text-slate-600">Alias · IMS Item ID · Item Name</div></div>`+(items.map(i=>`<button class="workspaceOpenItem w-full text-left bg-slate-950 hover:bg-slate-800 border border-slate-800 rounded-xl p-3 mb-2" data-id="${i.id}">${identity(i)}<div class="text-[11px] text-slate-500">${esc([i.category,i.brand,i.model,i.specification].filter(Boolean).join(' · ')||'No classification')}</div><div class="text-[10px] text-slate-500 mt-1">${esc(i.status||'')} · ${esc(i.currentLocation||'')} · ${esc(itemQty(i))} ${esc(i.unit||'')}</div></button>`).join('')||'<div class="text-sm text-slate-500">No matching items.</div>');bindOpenItems(mount);}
async function runSearch(){const raw=byId('itemFind')?.value||'';currentQuery=norm(raw);items=await searchItems(raw);renderFinder();}
function hasBalance(i,status){return balances(i).some(b=>Number(b.qty||0)>0&&b.status===status);}
function groupItems(key){if(key==='client')return inventory.filter(i=>hasBalance(i,'At Client')||i.status==='At Client');if(key==='supplier')return inventory.filter(i=>hasBalance(i,'At Supplier')||i.status==='At Supplier');if(key==='transit')return inventory.filter(i=>hasBalance(i,'In Transit')||i.status==='In Transit');return inventory.filter(i=>hasBalance(i,'Maintenance')||i.status==='Maintenance');}
function groupCard(key,title){const list=groupItems(key).sort((a,b)=>String(a.alias||a.itemCode).localeCompare(String(b.alias||b.itemCode),undefined,{numeric:true,sensitivity:'base'})),max=Math.max(1,Math.ceil(list.length/pageSize));pages[key]=Math.min(pages[key],max-1);const slice=list.slice(pages[key]*pageSize,(pages[key]+1)*pageSize);return `<section class="bg-slate-900 border border-slate-800 rounded-2xl p-4"><div class="flex justify-between items-center mb-3"><div><div class="font-bold">${esc(title)}</div><div class="text-[10px] text-slate-500">${list.length} active item${list.length===1?'':'s'} · Alias first</div></div><div class="text-xs text-slate-500">${pages[key]+1}/${max}</div></div><div class="space-y-2">${slice.map(i=>`<button class="workspaceOpenItem w-full text-left bg-slate-950 border border-slate-800 rounded-lg p-2" data-id="${i.id}">${identity(i)}<div class="text-[10px] text-slate-500">${esc(i.currentLocation||i.status||'')}</div></button>`).join('')||'<div class="text-xs text-slate-600">No active items.</div>'}</div>${list.length>pageSize?`<div class="flex justify-end gap-2 mt-3"><button data-active-page="${key}" data-d="-1" class="bg-slate-800 px-3 py-1.5 rounded text-xs" ${pages[key]===0?'disabled':''}>Previous</button><button data-active-page="${key}" data-d="1" class="bg-slate-800 px-3 py-1.5 rounded text-xs" ${pages[key]>=max-1?'disabled':''}>Next</button></div>`:''}</section>`;}
function renderActive(){const mount=byId('imsActiveItems');if(!mount)return;mount.innerHTML=groupCard('client','At Client')+groupCard('supplier','At Supplier')+groupCard('transit','In Transit')+groupCard('maintenance','Maintenance');bindOpenItems(mount);mount.querySelectorAll('[data-active-page]').forEach(b=>b.onclick=()=>{pages[b.dataset.activePage]+=Number(b.dataset.d);renderActive();});}
function bindOpenItems(root=document){root.querySelectorAll('.workspaceOpenItem').forEach(b=>b.onclick=()=>window.IMSItems?.showItem?window.IMSItems.showItem(b.dataset.id):window.openItem?.(b.dataset.id));}
function bind(){byId('itemFindBtn').onclick=runSearch;byId('itemFind').onkeyup=e=>{if(e.key==='Enter')runSearch();};document.querySelectorAll('.imsArrive').forEach(b=>b.onclick=()=>window.IMSMovement?.arriveMovement?window.IMSMovement.arriveMovement(b.dataset.id):window.arriveMovement?.(b.dataset.id));}
async function render(){setHead();const totalQty=inventory.reduce((n,i)=>n+itemQty(i),0),available=statusCount('Available');byId('appContent').innerHTML=`<div data-ims-workspace-module="1"><div class="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-7 gap-2 mb-5">${stat('Item Records',inventory.length)}${stat('Total Qty',totalQty)}${stat('Available',available)}${stat('At Supplier',statusCount('At Supplier'))}${stat('In Transit',statusCount('In Transit'))}${stat('At Client',statusCount('At Client'))}${stat('Maintenance',statusCount('Maintenance'))}</div><div class="grid xl:grid-cols-2 gap-5">${card('Register Item','registerForm','Loading Registration…')}${card('Move Item','moveForm','Loading Movement…')}${card('Active Transit / Arrival','arrivalMount',arrivalHtml())}${card('Maintenance / Inspection','maintenanceForm','Loading Maintenance…')}</div><section class="bg-slate-900 border border-slate-800 rounded-2xl p-4 sm:p-5 shadow-xl mt-5"><h2 class="font-bold text-sm sm:text-base mb-4">Find Item</h2><div class="grid sm:grid-cols-[1fr_auto] gap-2"><input id="itemFind" class="w-full bg-slate-950 border border-slate-700 rounded-lg px-3 py-2.5 text-sm" placeholder="Search Alias, IMS Item ID, Item Name, supplier, location or document ref..."><button id="itemFindBtn" class="bg-slate-700 hover:bg-slate-600 px-5 py-2 rounded-lg text-sm font-bold">Search</button></div><div id="itemFindResults" class="mt-3 space-y-2"></div></section><div id="imsActiveItems" class="grid gap-5 mt-5"></div><div id="itemDetailMount" class="mt-5"></div></div>`;items=await latestItems();renderFinder();renderActive();bind();window.dispatchEvent(new CustomEvent('ims:workspace-rendered'));}
async function show(){if(!can('app.view'))return;try{await load();await render();}catch(err){console.error('IMS workspace failed:',err);}}
function takeOwnership(){const b=document.querySelector('[data-tab="workspace"]');if(!b||b.dataset.imsWorkspaceOwned==='1')return;b.dataset.imsWorkspaceOwned='1';b.onclick=show;}
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(takeOwnership,30);}).observe(document.body,{childList:true,subtree:true});takeOwnership();
window.IMSWorkspace=Object.freeze({show,load,render});window.dispatchEvent(new CustomEvent('ims:workspace-ready'));
export { show, load, render };
