import {auth,db} from '../../firebase-config.js';
import {addDoc,collection,doc,getDocs,runTransaction,setDoc} from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';
import {can} from '../../ims-permissions.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),cls='w-full bg-slate-950 border border-slate-700 rounded-lg px-3 py-2.5 text-sm',now=()=>new Date().toISOString();
let items=[],clients=[];
function balances(i){return(Array.isArray(i.stockBalances)?i.stockBalances:[]).filter(b=>Number(b.qty||0)>0).map(b=>({...b,qty:Number(b.qty||0)}));}
function available(i){return balances(i).filter(b=>b.status==='Available').reduce((a,b)=>a+b.qty,0);}
function name(x){return x.companyName||x.clientName||x.supplierName||'';}
function summary(b){const p=b.filter(x=>x.qty>0),priority=['In Transit','Maintenance','At Client','Reserved','Missing','Stolen','Not Available','At Supplier','Available'];return!p.length?{status:'Not Available',location:'No Stock'}:{status:priority.find(s=>p.some(x=>x.status===s))||'Not Available',location:p.length===1?p[0].locationName:`${p.length} Locations`};}
async function load(){const[a,b,c]=await Promise.all(['inventory','client_profiles','supplier_profiles'].map(n=>getDocs(collection(db,n))));items=a.docs.map(d=>({id:d.id,...d.data()}));clients=[...b.docs.map(d=>({id:d.id,sourceKind:'client',...d.data()})),...c.docs.map(d=>({id:d.id,sourceKind:'supplier',...d.data()}))].filter(x=>x.status!=='inactive'&&((x.businessRoles||[]).includes('client')||(!(x.businessRoles||[]).length&&x.sourceKind==='client')));}
function setHead(){if($('pageTitle'))$('pageTitle').textContent='Reservation';if($('pageSubtitle'))$('pageSubtitle').textContent='Temporarily lock Available stock. Movement consumes, releases or exceeds the reserved quantity automatically.';}
function html(){const active=items.filter(i=>i.activeReservation);return`<div class="space-y-5"><section class="bg-slate-900 border border-slate-800 rounded-2xl p-4 space-y-3"><div><h2 class="font-bold">New Reservation</h2><div class="text-xs text-slate-500 mt-1">Reservation only locks stock. The actual Client movement may be less, equal or more than the reserved quantity.</div></div><div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-2"><label class="text-xs">Item / Stock<select id="resItem" class="${cls} mt-1"><option value="">-</option>${items.filter(i=>available(i)>0).map(i=>`<option value="${i.id}">${esc(i.alias||i.itemCode)} · ${esc(i.name)} · ${available(i)} available</option>`).join('')}</select></label><label class="text-xs">Reserve Qty<input id="resQty" type="number" min="1" step="1" value="1" class="${cls} mt-1"></label><label class="text-xs">Client<select id="resClient" class="${cls} mt-1"><option value="">-</option>${clients.map(c=>`<option value="${c.id}">${esc(name(c))}</option>`).join('')}</select></label><label class="text-xs">Expected Date<input id="resDate" type="date" class="${cls} mt-1"></label><label class="text-xs lg:col-span-2">Client PO / Booking Reference<input id="resRef" class="${cls} mt-1" placeholder="PO can be entered now or confirmed later"></label><label class="text-xs lg:col-span-2">Remark<input id="resRemark" class="${cls} mt-1"></label></div><button id="resSave" class="bg-red-600 px-4 py-2 rounded-lg text-xs font-bold">Reserve Stock</button></section><section class="bg-slate-900 border border-slate-800 rounded-2xl p-4"><h2 class="font-bold mb-3">Active Reservations</h2><div class="space-y-2">${active.map(i=>{const r=i.activeReservation||{};return`<div class="border border-slate-800 rounded-xl p-3 flex flex-wrap justify-between gap-2"><div><b class="text-cyan-300">${esc(i.alias||i.itemCode)}</b> · ${esc(i.name)}<div class="text-xs text-slate-500">${esc(r.clientName||'')} · Reserved ${esc(r.qty||1)} · ${esc(r.reference||'PO pending')}</div><div class="text-[10px] text-slate-600">Use this reservation directly from Movement → Send to Client.</div></div><button class="resCancel bg-slate-700 px-3 py-2 rounded-lg text-xs" data-id="${i.id}">Cancel Reservation</button></div>`}).join('')||'<div class="text-sm text-slate-500">No active reservations.</div>'}</div></section></div>`;}
async function reserve(){if(!can('reservation.add'))return;const id=$('resItem').value,i=items.find(x=>x.id===id),qty=Number($('resQty').value),client=clients.find(x=>x.id===$('resClient').value);if(!i||!client||!Number.isInteger(qty)||qty<1||qty>available(i))return alert('Complete item, reserve quantity and client.');const at=now(),email=auth.currentUser?.email||'',reference=$('resRef').value.trim(),remark=$('resRemark').value.trim(),eventRef=doc(collection(db,'reservation_events')),reservation={reservationId:eventRef.id,qty,clientId:client.id,clientName:name(client),reference,expectedDate:$('resDate').value||'',remark,status:'Open',createdAt:at,createdBy:email,itemId:id,itemAlias:i.alias||'',itemCode:i.itemCode||'',itemName:i.name||''};await runTransaction(db,async tx=>{const r=doc(db,'inventory',id),s=await tx.get(r);if(!s.exists())throw new Error('Item missing.');const b=balances(s.data()),src=b.find(x=>x.status==='Available'&&x.qty>=qty);if(!src)throw new Error('Available stock changed.');src.qty-=qty;b.push({qty,locationType:src.locationType,locationId:src.locationId||'',locationName:src.locationName,status:'Reserved',reservationId:eventRef.id});const clean=b.filter(x=>x.qty>0),sum=summary(clean);tx.update(r,{stockBalances:clean,status:sum.status,currentLocation:sum.location,activeReservation:reservation,lastEditedAt:at,lastEditedBy:email});tx.set(eventRef,{...reservation,sourceLocationType:src.locationType,sourceLocationId:src.locationId||'',sourceLocationName:src.locationName});});await addDoc(collection(db,'operational_logs'),{date:at,activity:'RESERVE_ITEM',activityLabel:'Reserve Item',itemId:id,itemAlias:i.alias||'',itemCode:i.itemCode||'',itemName:i.name||'',qty,status:'Reserved',reservationId:eventRef.id,clientId:client.id,clientName:name(client),clientPONumber:reference,performedBy:email,remark});await show();}
async function cancel(id){if(!can('reservation.cancel'))return;const i=items.find(x=>x.id===id),r=i?.activeReservation;if(!r)return;const at=now(),email=auth.currentUser?.email||'',q=Number(r.qty||1);await runTransaction(db,async tx=>{const ref=doc(db,'inventory',id),s=await tx.get(ref);if(!s.exists())throw new Error('Item missing.');const b=balances(s.data()),reserved=b.filter(x=>x.status==='Reserved'&&(!r.reservationId||!x.reservationId||x.reservationId===r.reservationId));let remaining=q;for(const src of reserved){const take=Math.min(src.qty,remaining);if(take<=0)continue;src.qty-=take;let dst=b.find(x=>x.status==='Available'&&x.locationType===src.locationType&&x.locationId===src.locationId&&x.locationName===src.locationName);dst?dst.qty+=take:b.push({qty:take,locationType:src.locationType,locationId:src.locationId||'',locationName:src.locationName,status:'Available'});remaining-=take;}if(remaining>0)throw new Error('Reserved balance changed.');const clean=b.filter(x=>x.qty>0),sum=summary(clean);tx.update(ref,{stockBalances:clean,status:sum.status,currentLocation:sum.location,activeReservation:null,lastReservation:{...r,status:'Cancelled',cancelledAt:at,cancelledBy:email,releasedBack:q},lastEditedAt:at,lastEditedBy:email});if(r.reservationId)tx.set(doc(db,'reservation_events',r.reservationId),{status:'Cancelled',cancelledAt:at,cancelledBy:email,releasedBack:q},{merge:true});});await addDoc(collection(db,'operational_logs'),{date:at,activity:'CANCEL_RESERVATION',activityLabel:'Cancel Reservation',itemId:id,itemAlias:i.alias||'',itemCode:i.itemCode||'',itemName:i.name||'',qty:q,status:'Available',reservationId:r.reservationId||'',performedBy:email,remark:r.remark||''});await show();}
function bind(){if($('resSave'))$('resSave').onclick=reserve;document.querySelectorAll('.resCancel').forEach(b=>b.onclick=()=>cancel(b.dataset.id));}
async function show(){if(!can('reservation.view'))return;await load();setHead();$('appContent').innerHTML=html();bind();}
function install(){const nav=$('navTabs');if(!nav||nav.querySelector('[data-tab="reservation"]'))return;const b=document.createElement('button');b.dataset.tab='reservation';b.className='navBtn text-left px-3 py-2.5 rounded-xl text-xs font-semibold bg-slate-800/50 hover:bg-slate-800';b.textContent='Reservation';b.onclick=show;nav.appendChild(b);}
let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(install,30)}).observe(document.body,{childList:true,subtree:true});install();window.IMSReservation=Object.freeze({show});window.dispatchEvent(new CustomEvent('ims:reservation-ready'));export{show};