import {db} from '../../firebase-config.js';
import {collection,getDocs,query,where} from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';

const $=id=>document.getElementById(id);
const allowedRole=()=>['manager','superadmin'].includes(String(window.IMS_ROLE||'').toLowerCase());
const blank=v=>/^--\s+.*\s+--$/.test(String(v??'').trim())?'':String(v??'');

function requireXlsx(){if(typeof XLSX==='undefined')throw new Error('Excel library is unavailable. Reload IMS and try again.');return XLSX;}
function workbookRows(file){return file.arrayBuffer().then(buf=>{const X=requireXlsx(),wb=X.read(buf,{type:'array',cellDates:false,raw:false});if(!wb.SheetNames.length)throw new Error('Excel workbook has no worksheet.');const ws=wb.Sheets[wb.SheetNames[0]],rows=X.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});return rows.filter(r=>r.some(v=>String(v??'').trim()!==''));});}
function sheetRows(headers,rows=[]){const X=requireXlsx(),ws=X.utils.aoa_to_sheet([headers,...rows]);ws['!freeze']={xSplit:0,ySplit:1};ws['!cols']=headers.map(h=>({wch:Math.min(28,Math.max(12,String(h).length+2))}));return ws;}
function downloadXlsx(filename,sheetName,headers,rows=[]){const X=requireXlsx(),wb=X.utils.book_new(),ws=sheetRows(headers,rows);X.utils.book_append_sheet(wb,ws,sheetName);X.writeFile(wb,filename,{compression:true});}
function regRow(i){const b=(Array.isArray(i.stockBalances)?i.stockBalances:[]).find(x=>Number(x.qty||0)>0)||{},pos=b.locationType==='supplier'?'Supplier':'Warehouse';return[i.type,1,i.unit,i.name,i.alias,blank(i.coc),i.category,blank(i.size),blank(i.grade),blank(i.ppf),blank(i.connection),blank(i.range),blank(i.brand),blank(i.model),i.weight??'',i.weightUnit,i.supplierName,i.ourPONumber,i.ourPOAmount??'',i.currency,pos,pos==='Warehouse'?b.locationName:'',i.deliveryTicket,i.receivingTicket,i.remark];}
function r2rRow(i){const b=(Array.isArray(i.stockBalances)?i.stockBalances:[]).find(x=>Number(x.qty||0)>0)||{},wh=b.toType==='warehouse'?b.toName:b.locationType==='warehouse'?b.locationName:'';return[i.type,1,i.unit,i.name,i.alias,blank(i.coc),i.category,blank(i.size),blank(i.grade),blank(i.ppf),blank(i.connection),blank(i.range),blank(i.brand),blank(i.model),i.weight??'',i.weightUnit,i.supplierName||i.ownerBusinessName,i.ourPONumber,i.ourPOAmount??'',i.currency,wh,i.rentalStartDate,i.rentalDueDate,i.remark];}
async function exportExcel(mode){if(!allowedRole())return;const api=window.IMSRegistrationCSV;if(!api)throw new Error('Registration import/export module is unavailable.');const own=mode==='registration'?'owned':'third_party',snap=await getDocs(query(collection(db,'inventory'),where('ownershipType','==',own))),headers=mode==='registration'?api.REG_HEADERS:api.R2R_HEADERS,rows=snap.docs.map(d=>mode==='registration'?regRow(d.data()):r2rRow(d.data()));downloadXlsx(`IMS_${mode==='registration'?'Registration':'R2R'}_Export_${new Date().toISOString().slice(0,10)}.xlsx`,mode==='registration'?'Registration':'R2R',headers,rows);}
function toDelimited(rows){return rows.map(r=>r.map(v=>{const s=String(v??'');return /["\t\n\r]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;}).join('\t')).join('\r\n');}
async function feedExistingImporter(root,file){const rows=await workbookRows(file);if(!rows.length)throw new Error('Excel workbook is empty.');const text=toDelimited(rows),input=root.querySelector('.imsCsvFile');if(!input)throw new Error('Import control is unavailable.');const dt=new DataTransfer();dt.items.add(new File([text],file.name.replace(/\.xlsx?$/i,'.tsv'),{type:'text/tab-separated-values'}));input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));}
function enhance(mode){if(!allowedRole())return;const id=mode==='registration'?'regCsvTools':'r2rCsvTools',root=$(id);if(!root||root.dataset.imsExcel==='1')return;root.dataset.imsExcel='1';const api=window.IMSRegistrationCSV;if(!api)return;const title=root.querySelector('.font-semibold');if(title)title.textContent=`${mode==='registration'?'Registration':'R2R Registration'} Excel Import / Export`;const note=root.querySelector('.text-slate-500');if(note)note.textContent='Manager / Superadmin · real Excel .xlsx workbook · first worksheet only · row 1 is header · one physical IMS item per row, Qty 1.';
 const template=root.querySelector('.imsCsvTemplate'),imp=root.querySelector('.imsCsvImport'),exp=root.querySelector('.imsCsvExport'),oldInput=root.querySelector('.imsCsvFile');
 if(template){template.textContent='Download Excel Template';template.onclick=()=>{const h=mode==='registration'?api.REG_HEADERS:api.R2R_HEADERS;downloadXlsx(mode==='registration'?'IMS_Registration_Template.xlsx':'IMS_R2R_Registration_Template.xlsx',mode==='registration'?'Registration':'R2R',h);};}
 if(exp){exp.textContent='Export Excel';exp.onclick=()=>exportExcel(mode).catch(e=>alert('Excel export failed: '+(e?.message||e)));}
 if(imp&&oldInput){let picker=root.querySelector('.imsExcelFile');if(!picker){picker=document.createElement('input');picker.type='file';picker.accept='.xlsx,.xls,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel';picker.className='imsExcelFile hidden';root.appendChild(picker);}imp.textContent='Import Excel';imp.onclick=()=>{picker.value='';picker.click();};picker.onchange=()=>{const f=picker.files?.[0];if(!f)return;feedExistingImporter(root,f).catch(e=>{const p=root.querySelector('.imsCsvPreview');if(p){p.classList.remove('hidden');p.innerHTML=`<div class="border border-red-900/60 rounded-lg p-3 text-sm text-red-300">Excel import blocked: ${String(e?.message||e)}</div>`;}});};oldInput.accept='.csv,.tsv,text/csv,text/tab-separated-values';}
}
function install(){enhance('registration');enhance('r2r');}
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(install,30);}).observe(document.body,{childList:true,subtree:true});
['ims:registration-csv-ready','ims:registration-ready','ims:renttorent-ready','ims:workspace-rendered','ims:modules-ready'].forEach(n=>window.addEventListener(n,install));
install();
window.IMSRegistrationExcel=Object.freeze({install,exportExcel,downloadXlsx});
window.dispatchEvent(new CustomEvent('ims:registration-excel-ready'));
export{install,exportExcel,downloadXlsx};