import { auth, db } from '../../firebase-config.js';
import { addDoc, collection, deleteDoc, doc, documentId, getDoc, getDocs, limit, orderBy, query, startAfter, Timestamp, writeBatch } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';
import { can } from '../../ims-permissions.js';
import { rebuildInventorySummary } from '../inventory/inventory-summary.js';

const BACKUP_VERSION=7;
const READ_BATCH=500,WRITE_BATCH=400,PORTABLE_WARNING_AT=50000;
const BACKUP_COLLECTIONS=Object.freeze([
  'registration_batches','inventory',
  'movement_groups','movements','reservation_events','service_cycles',
  'client_docs','supplier_docs','document_refs',
  'operational_logs','audit_traces',
  'supplier_profiles','client_profiles','settings','users'
]);
const RESET_COLLECTIONS=Object.freeze(BACKUP_COLLECTIONS.filter(x=>x!=='users'));
const DERIVED_RESET_COLLECTIONS=Object.freeze(['inventory_summary']);
const byId=id=>document.getElementById(id),nowISO=()=>new Date().toISOString();

async function activeActor(allowedRoles=['superadmin']){
  const user=auth.currentUser;if(!user)throw new Error('Sign in required.');
  const snap=await getDoc(doc(db,'users',user.uid));if(!snap.exists())throw new Error('User profile missing.');
  const profile=snap.data();if(profile.status!=='active'||!allowedRoles.includes(profile.role))throw new Error(`Active ${allowedRoles.join(' / ')} profile required.`);
  return{uid:user.uid,email:profile.email||user.email||'',role:profile.role};
}
const activeSuperadmin=()=>activeActor(['superadmin']);
function encodeValue(v){if(v===null||v===undefined||typeof v!=='object')return v;if(typeof v.toDate==='function'&&typeof v.seconds==='number')return{__imsType:'timestamp',seconds:v.seconds,nanoseconds:v.nanoseconds||0};if(Array.isArray(v))return v.map(encodeValue);const out={};Object.keys(v).forEach(k=>out[k]=encodeValue(v[k]));return out;}
function decodeValue(v){if(v===null||v===undefined||typeof v!=='object')return v;if(v.__imsType==='timestamp'&&Number.isFinite(Number(v.seconds)))return new Timestamp(Number(v.seconds),Number(v.nanoseconds||0));if(Array.isArray(v))return v.map(decodeValue);const out={};Object.keys(v).forEach(k=>out[k]=decodeValue(v[k]));return out;}
function downloadJson(name,payload){const blob=new Blob([JSON.stringify(payload)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
async function readCollection(name){const rows=[];let cursor=null;while(true){const parts=[orderBy(documentId()),limit(READ_BATCH)];if(cursor)parts.splice(1,0,startAfter(cursor));const snap=await getDocs(query(collection(db,name),...parts));for(const d of snap.docs)rows.push({id:d.id,data:encodeValue(d.data())});if(snap.size<READ_BATCH)break;cursor=snap.docs.at(-1);}return rows;}
async function clearCollection(name){let deleted=0;while(true){const snap=await getDocs(query(collection(db,name),orderBy(documentId()),limit(WRITE_BATCH)));if(snap.empty)break;const batch=writeBatch(db);snap.docs.forEach(d=>batch.delete(d.ref));await batch.commit();deleted+=snap.size;}return deleted;}
async function writeAudit(action,afterValue,remark='',metadata={},actor=null){const user=actor||await activeSuperadmin();await addDoc(collection(db,'audit_traces'),{traceVersion:3,actionType:action,module:'Backup / Recovery',targetType:'backup',targetName:action==='CREATE_SYSTEM_BACKUP'?'Portable IMS Backup':action==='RESTORE_SYSTEM_BACKUP'?'Portable IMS Restore':action==='CLEAN_TEST_RESET'?'Clean Testing Reset':'System Reload',targetId:'',summary:String(action).replace(/_/g,' '),beforeValue:null,afterValue,changedFields:Object.keys(afterValue||{}),remark,metadata,performedBy:user.email,performedByRole:user.role,performedAt:nowISO()});}

async function createBackup(){if(!can('backup.create'))return;const btn=byId('imsFullBackup');if(btn){btn.disabled=true;btn.textContent='Preparing Portable Backup...';}try{const actor=await activeSuperadmin(),payload={imsBackupVersion:BACKUP_VERSION,createdAt:nowISO(),createdBy:actor.email,backupClass:'portable-browser',productionDisasterRecovery:false,restoreMode:'replace matching document IDs; preserve documents absent from backup; rebuild derived inventory summary after restore',firebaseAuthIncluded:false,derivedCollectionsExcluded:['inventory_summary'],collections:{}};let total=0;for(const name of BACKUP_COLLECTIONS){payload.collections[name]=await readCollection(name);total+=payload.collections[name].length;}payload.counts=Object.fromEntries(BACKUP_COLLECTIONS.map(name=>[name,payload.collections[name].length]));if(total>=PORTABLE_WARNING_AT&&!confirm(`This portable browser backup contains ${total.toLocaleString()} records. It may use substantial browser memory.\n\nFor production-scale disaster recovery use Firestore managed/scheduled backups.\n\nContinue creating the portable JSON file?`))return;await writeAudit('CREATE_SYSTEM_BACKUP',{backupVersion:BACKUP_VERSION,collections:BACKUP_COLLECTIONS.length,records:total,backupClass:'portable-browser'},'Portable browser backup created. Production disaster recovery should use Firestore managed/scheduled backup.',{},actor);downloadJson(`IMS_Portable_Backup_${payload.createdAt.slice(0,10)}.json`,payload);alert(`Portable IMS backup created.\n\nRecords: ${total}\nCollections: ${BACKUP_COLLECTIONS.length}\n\nThis JSON is for portable/test recovery. Production-scale disaster recovery should use Firestore managed/scheduled backups.`);}catch(err){console.error('IMS backup failed:',err);alert('Backup failed: '+(err?.message||err));}finally{if(btn){btn.disabled=false;btn.textContent='Download Portable Backup JSON';}}}
function validateBackup(payload){if(!payload||Number(payload.imsBackupVersion)!==BACKUP_VERSION||!payload.collections||typeof payload.collections!=='object')throw new Error(`Unsupported IMS portable backup. Current backup version required: ${BACKUP_VERSION}.`);for(const name of BACKUP_COLLECTIONS)if(!Array.isArray(payload.collections[name]))throw new Error(`Backup is incomplete: missing collection ${name}.`);return BACKUP_COLLECTIONS;}
function backupSummary(payload,names){return{text:names.map(name=>`${name}: ${payload.collections[name].length}`).join('\n'),total:names.reduce((n,name)=>n+payload.collections[name].length,0)};}
async function restoreBackup(file){if(!can('backup.restore')||!file)return;let payload,names;try{payload=JSON.parse(await file.text());names=validateBackup(payload);}catch(err){alert(err?.message||'Invalid backup file.');return;}const summary=backupSummary(payload,names);if(!confirm(`PORTABLE IMS RESTORE\n\nBackup date: ${payload.createdAt||'Unknown'}\nRecords: ${summary.total}\n\n${summary.text}\n\nMatching IDs will be restored; documents absent from the backup are kept. Continue?`))return;if(prompt('Type RESTORE IMS to confirm.','')!=='RESTORE IMS')return;const btn=byId('imsFullRestore');if(btn){btn.disabled=true;btn.textContent='Restoring...';}let restored=0,skipped=0;const errors=[];try{const actor=await activeSuperadmin(),uid=actor.uid;for(const name of names){const rows=payload.collections[name];for(let i=0;i<rows.length;i+=WRITE_BATCH){const part=rows.slice(i,i+WRITE_BATCH),batch=writeBatch(db);let queued=0;for(const row of part){if(!row?.id||row.data===undefined){errors.push(`${name}: invalid record`);continue;}if(name==='users'&&row.id===uid){skipped++;continue;}batch.set(doc(db,name,row.id),decodeValue(row.data));queued++;}if(queued){try{await batch.commit();restored+=queued;}catch(err){errors.push(`${name} batch ${Math.floor(i/WRITE_BATCH)+1}: ${err?.message||err}`);}}}}const rebuilt=await rebuildInventorySummary(actor.email);await writeAudit('RESTORE_SYSTEM_BACKUP',{restored,skippedCurrentUser:skipped,errors:errors.length,backupCreatedAt:payload.createdAt||'',backupVersion:payload.imsBackupVersion,backupClass:'portable-browser',inventorySummaryRebuilt:true,inventorySummarySourceRecords:rebuilt.recordCount},'Portable IMS restore completed. Production-scale disaster recovery should use Firestore managed restore.',{fileName:file.name},actor);if(errors.length)console.error('IMS restore errors:',errors);alert(`Portable IMS restore completed.\n\nRestored: ${restored}\nCurrent signed-in profile preserved: ${skipped}\nErrors: ${errors.length}\nInventory Summary rebuilt from ${rebuilt.recordCount} inventory record(s).`);location.reload();}catch(err){console.error('IMS restore failed:',err);alert('Restore failed: '+(err?.message||err));}finally{if(btn){btn.disabled=false;btn.textContent='Restore Portable Backup JSON';}}}
async function cleanTestingReset(){if(!can('system.test.reset'))return;const actor=await activeSuperadmin();if(!confirm('CLEAN TESTING RESET\n\nThis permanently clears IMS test/business data while preserving users and Firebase Auth. Continue?'))return;if(prompt('Type CLEAN RESET to confirm.','')!=='CLEAN RESET')return;const btn=byId('imsResetDataBtn');if(btn){btn.disabled=true;btn.textContent='Cleaning...';}let deleted=0;try{for(const name of RESET_COLLECTIONS)deleted+=await clearCollection(name);for(const name of DERIVED_RESET_COLLECTIONS)deleted+=await clearCollection(name);await writeAudit('CLEAN_TEST_RESET',{deleted,collections:RESET_COLLECTIONS.length+DERIVED_RESET_COLLECTIONS.length,inventorySummaryCleared:true},'Clean testing reset completed; users and Firebase Auth preserved.',{},actor);alert(`Clean testing reset completed.\nDeleted ${deleted} Firestore record(s).`);location.reload();}catch(err){console.error('IMS clean testing reset failed:',err);alert('Reset failed: '+(err?.message||err));}finally{if(btn){btn.disabled=false;btn.textContent='Clean Reset All Test Data';}}}
async function reloadSystem(){if(!can('backup.create'))return;try{const actor=await activeSuperadmin();await writeAudit('SYSTEM_RELOAD',{requestedAt:nowISO()},'Superadmin manually reloaded IMS.',{},actor);}catch(err){console.warn('IMS reload audit failed:',err);}location.reload();}
function recoverySection(){const backup=can('backup.create')?'<button id="imsFullBackup" type="button" class="bg-cyan-700 hover:bg-cyan-600 px-4 py-2 rounded-lg text-xs font-bold">Download Portable Backup JSON</button>':'';const restore=can('backup.restore')?'<button id="imsFullRestore" type="button" class="bg-amber-700 hover:bg-amber-600 px-4 py-2 rounded-lg text-xs font-bold">Restore Portable Backup JSON</button><input id="imsFullRestoreFile" type="file" accept=".json,application/json" class="hidden">':'';const reload=can('backup.create')?'<button id="imsReloadSystem" type="button" class="bg-slate-700 hover:bg-slate-600 px-4 py-2 rounded-lg text-xs font-bold">Reload IMS</button>':'';const reset=can('system.test.reset')?'<div class="mt-4 border-t border-red-900/60 pt-4"><div class="font-bold text-red-300 text-sm">Clean Testing Reset</div><p class="text-xs text-slate-400 mt-1 mb-3">Testing only. Deletes IMS data in server-side batches while preserving users and Firebase Auth.</p><button id="imsResetDataBtn" type="button" class="bg-red-700 hover:bg-red-600 px-4 py-2.5 rounded-lg text-xs font-bold">Clean Reset All Test Data</button></div>':'';return`<section id="imsBackupRecoveryModule" class="bg-slate-900 border border-slate-800 rounded-2xl p-4 sm:p-5 shadow-xl"><h2 class="font-bold text-sm sm:text-base mb-2">System Backup / Recovery</h2><p class="text-xs text-slate-400 mb-2">Superadmin only. Portable JSON backup/restore is for testing, migration and smaller recovery jobs.</p><div class="border border-amber-900/60 bg-amber-950/20 rounded-lg p-3 text-[11px] text-amber-200 mb-3"><b>Production disaster recovery:</b> use Firestore managed/scheduled backups for very large databases. Do not rely on a browser JSON file for million-record recovery.</div><div class="flex flex-wrap gap-2">${backup}${restore}${reload}</div>${reset}</section>`;}
function bindRecovery(){if(byId('imsFullBackup'))byId('imsFullBackup').onclick=createBackup;if(byId('imsFullRestore'))byId('imsFullRestore').onclick=()=>byId('imsFullRestoreFile')?.click();if(byId('imsFullRestoreFile'))byId('imsFullRestoreFile').onchange=e=>restoreBackup(e.target.files?.[0]);if(byId('imsReloadSystem'))byId('imsReloadSystem').onclick=reloadSystem;if(byId('imsResetDataBtn'))byId('imsResetDataBtn').onclick=()=>cleanTestingReset().catch(err=>{console.error(err);alert('Reset failed: '+(err?.message||err));});}
function mount(){if(!can('backup.create')&&!can('backup.restore')&&!can('system.test.reset'))return;if(byId('pageTitle')?.textContent!=='Global Settings')return;const host=byId('imsBackupRecoveryHost')||byId('appContent');if(!host)return;if(byId('imsBackupRecoveryModule')){bindRecovery();return;}host.insertAdjacentHTML('beforeend',recoverySection());bindRecovery();}
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(mount,30)}).observe(document.body,{childList:true,subtree:true});mount();
window.IMSBackup=Object.freeze({createBackup,restoreBackup,cleanTestingReset,reloadSystem,mount,BACKUP_COLLECTIONS,RESET_COLLECTIONS,DERIVED_RESET_COLLECTIONS});window.dispatchEvent(new CustomEvent('ims:backup-ready'));
export { createBackup, restoreBackup, cleanTestingReset, reloadSystem, mount };
